import '../../core/localization/app_locale.dart';

/// Reviewed product copy added after the initial screen catalogue.
///
/// Keeping this dictionary separate prevents the generic text widget from
/// becoming the owner of feature behavior. Keys are always the pt-BR source.
const supplementalUiTranslations = <SupportedAppLocale, Map<String, String>>{
  SupportedAppLocale.enUs: {
    'Atualizar reserva de emergência': 'Update emergency fund',
    'Reserva de emergência': 'Emergency fund',
    'Cadastre despesas para visualizar a participação na renda.':
        'Add expenses to see their share of your income.',
    'Origem dos ganhos': 'Income sources',
    'Nenhum resultado local. O cadastro manual continua disponível.':
        'No local results. Manual entry is still available.',
    'Ela sairá da carteira, mas poderá ser restaurada por alguns segundos.':
        'It will leave the portfolio, but can be restored for a few seconds.',
    'Evolução patrimonial': 'Wealth evolution',
    'Aplicado + rendimento confirmado': 'Invested amount + confirmed return',
    'Estimativa educacional. Não é promessa de rentabilidade nem recomendação.':
        'Educational estimate. It is neither a return guarantee nor advice.',
    'Estimativa baseada em uma cesta média; não representa sua inflação pessoal.': 'Estimate based on an average basket; it does not represent your personal inflation.',
    'A alocação aparecerá quando você cadastrar uma posição.':
        'Allocation will appear after you add a holding.',
    'Não foi possível gerar o relatório. Tente novamente.':
        'The report could not be generated. Try again.',
    'Este documento contém informações financeiras pessoais. Compartilhe somente com pessoas de confiança.': 'This document contains personal financial information. Share it only with people you trust.',
    'O aplicativo agenda notificações locais. A entrega depende das permissões, economia de bateria, modo silencioso e políticas do aparelho.': 'The app schedules local notifications. Delivery depends on permissions, battery saving, silent mode and device policies.',
    'Todos os planos preservam seus dados e a navegação completa. Recursos avançados são explicados no ponto de uso.': 'Every plan keeps your data and full navigation. Advanced features are explained where they are used.',
    'Toque em um plano para visualizar os recursos disponíveis.':
        'Tap a plan to view its available features.',
    'Uma indicação elegível pode oferecer até 40% de desconto. Benefícios não são cumulativos: prevalece sempre o maior desconto válido.': 'An eligible referral may offer up to 40% off. Benefits cannot be combined: the highest valid discount always applies.',
    'O convite seguro será habilitado quando contas e validação do servidor estiverem disponíveis.': 'Secure invitations will be enabled when accounts and server validation are available.',
    'Benefícios úteis e transparentes para apoiar sua educação, bem-estar e vida prática.': 'Useful and transparent benefits to support your education, well-being and everyday life.',
    'O Oscar Finanças poderá receber uma comissão se você contratar ou comprar por este link. Você será direcionado ao ambiente do parceiro.': 'Oscar Finanças may receive a commission if you buy through this link. You will be directed to the partner environment.',
    'O link deste parceiro ainda não está disponível.':
        'This partner link is not available yet.',
    'Região': 'Region',
    'Primeiro dia da semana': 'First day of the week',
    'Ocultar valores ao abrir': 'Hide values on launch',
    'As Telas 1, 2 e 3 começam protegidas.':
        'Screens 1, 2 and 3 start protected.',
    'Ocultar valores ao sair': 'Hide values when leaving',
    'Oculta os valores quando o aplicativo vai para segundo plano.':
        'Hides values when the app goes to the background.',
    'Vibração e resposta tátil': 'Vibration and haptic feedback',
    'Lembrete padrão para novos eventos': 'Default reminder for new events',
    'Cotações e indicadores': 'Rates and indicators',
    'O último snapshot válido é usado offline. Atualizações indisponíveis aparecem como desatualizadas.': 'The latest valid snapshot is used offline. Unavailable updates appear as outdated.',
    'O Oscar Finanças não se conecta a contas bancárias nem movimenta dinheiro. Informações, simulações e projeções têm caráter informativo e usam dados fornecidos por você e referências de mercado atualizadas. Cotações podem apresentar atrasos ou diferenças em relação ao mercado.': 'Oscar Finanças does not connect to bank accounts or move money. Information, simulations and projections are informational and use data you provide and up-to-date market references. Quotes may be delayed or differ from the market.',
    'Atualização oficial disponível após configurar os provedores.':
        'Official updates become available after providers are configured.',
    'Atualizar agora': 'Update now',
    'Oscar Finanças — Clareza que transforma escolhas em patrimônio.':
        'Oscar Finanças — Clarity that turns choices into wealth.',
    'Organiza receitas, despesas, ganhos extras, saúde financeira, relatórios, agenda e investimentos sem movimentar seu dinheiro nem oferecer recomendação individual.': 'Organizes income, expenses, extra earnings, financial health, reports, calendar and investments without moving your money or giving individual advice.',
    'Saldo atual': 'Current balance',
    'Aporte deste mês': 'This month contribution',
    'O aporte será incluído na lista de gastos do mês.':
        'The contribution will be included in this month’s expense list.',
    'Tipo de aporte': 'Contribution type',
    'Aporte único': 'One-time contribution',
    'Mensal fixo': 'Fixed monthly',
    'Variável ou intermitente': 'Variable or intermittent',
    'Meta de cobertura': 'Coverage target',
    'Salário simulado': 'Sample salary',
    'Aluguel simulado': 'Sample rent',
    'Luz simulada': 'Sample electricity',
    'Água simulada': 'Sample water',
    'Internet simulada': 'Sample internet',
    'Mercado simulado': 'Sample groceries',
    'Reserva de emergência simulada': 'Sample emergency fund',
    'Faculdade simulada': 'Sample tuition',
    'Carro simulado': 'Sample car',
    'TV simulada': 'Sample TV',
    'Freelance de design simulado': 'Sample design freelance',
    'Projeto pontual simulado': 'Sample one-off project',
    'Manutenção de computador simulada': 'Sample computer maintenance',
    'Serviço técnico simulado': 'Sample technical service',
    'Venda de bicicleta simulada': 'Sample bicycle sale',
    'Venda ocasional simulada': 'Sample occasional sale',
    'Venda de doces simulada': 'Sample sweets sale',
    'Renda complementar simulada': 'Sample additional income',
    'Tesouro Selic simulado': 'Sample Treasury bond',
    'CDB simulado': 'Sample bank fixed income',
    'Fundo imobiliário simulado': 'Sample real estate fund',
    'Ação simulada': 'Sample stock',
    'Versão 0.1.0 · compilação 1': 'Version 0.1.0 · build 1',
  },
  SupportedAppLocale.deDe: {
    'Atualizar reserva de emergência': 'Notgroschen aktualisieren',
    'Reserva de emergência': 'Notgroschen',
    'Cadastre despesas para visualizar a participação na renda.':
        'Erfassen Sie Ausgaben, um deren Anteil am Einkommen zu sehen.',
    'Origem dos ganhos': 'Einnahmequellen',
    'Nenhum resultado local. O cadastro manual continua disponível.':
        'Keine lokalen Ergebnisse. Die manuelle Eingabe bleibt verfügbar.',
    'Ela sairá da carteira, mas poderá ser restaurada por alguns segundos.': 'Die Position wird entfernt, kann aber einige Sekunden lang wiederhergestellt werden.',
    'Evolução patrimonial': 'Vermögensentwicklung',
    'Aplicado + rendimento confirmado': 'Anlagebetrag + bestätigte Rendite',
    'Estimativa educacional. Não é promessa de rentabilidade nem recomendação.':
        'Schätzung zu Bildungszwecken. Keine Renditezusage oder Empfehlung.',
    'Estimativa baseada em uma cesta média; não representa sua inflação pessoal.': 'Schätzung anhand eines Durchschnittswarenkorbs; sie entspricht nicht Ihrer persönlichen Inflation.',
    'A alocação aparecerá quando você cadastrar uma posição.':
        'Die Aufteilung erscheint, sobald Sie eine Position erfassen.',
    'Não foi possível gerar o relatório. Tente novamente.':
        'Der Bericht konnte nicht erstellt werden. Versuchen Sie es erneut.',
    'Este documento contém informações financeiras pessoais. Compartilhe somente com pessoas de confiança.': 'Dieses Dokument enthält persönliche Finanzdaten. Teilen Sie es nur mit vertrauenswürdigen Personen.',
    'O aplicativo agenda notificações locais. A entrega depende das permissões, economia de bateria, modo silencioso e políticas do aparelho.': 'Die App plant lokale Benachrichtigungen. Die Zustellung hängt von Berechtigungen, Energiesparen, Lautlosmodus und Geräterichtlinien ab.',
    'Todos os planos preservam seus dados e a navegação completa. Recursos avançados são explicados no ponto de uso.': 'Alle Tarife bewahren Ihre Daten und die vollständige Navigation. Erweiterte Funktionen werden am Einsatzort erklärt.',
    'Toque em um plano para visualizar os recursos disponíveis.':
        'Tippen Sie auf einen Tarif, um die verfügbaren Funktionen anzuzeigen.',
    'Uma indicação elegível pode oferecer até 40% de desconto. Benefícios não são cumulativos: prevalece sempre o maior desconto válido.': 'Eine berechtigte Empfehlung kann bis zu 40 % Rabatt bieten. Vorteile sind nicht kombinierbar; es gilt stets der höchste gültige Rabatt.',
    'O convite seguro será habilitado quando contas e validação do servidor estiverem disponíveis.': 'Sichere Einladungen werden aktiviert, sobald Konten und Serverprüfung verfügbar sind.',
    'Benefícios úteis e transparentes para apoiar sua educação, bem-estar e vida prática.': 'Nützliche und transparente Vorteile zur Unterstützung von Bildung, Wohlbefinden und Alltag.',
    'O Oscar Finanças poderá receber uma comissão se você contratar ou comprar por este link. Você será direcionado ao ambiente do parceiro.': 'Oscar Finanças kann eine Provision erhalten, wenn Sie über diesen Link kaufen. Sie werden zum Partner weitergeleitet.',
    'O link deste parceiro ainda não está disponível.':
        'Der Link dieses Partners ist noch nicht verfügbar.',
    'Região': 'Region',
    'Primeiro dia da semana': 'Erster Wochentag',
    'Ocultar valores ao abrir': 'Werte beim Start ausblenden',
    'As Telas 1, 2 e 3 começam protegidas.':
        'Die Ansichten 1, 2 und 3 starten geschützt.',
    'Ocultar valores ao sair': 'Werte beim Verlassen ausblenden',
    'Oculta os valores quando o aplicativo vai para segundo plano.':
        'Blendet Werte aus, wenn die App in den Hintergrund wechselt.',
    'Vibração e resposta tátil': 'Vibration und haptisches Feedback',
    'Lembrete padrão para novos eventos': 'Standarderinnerung für neue Termine',
    'Cotações e indicadores': 'Kurse und Indikatoren',
    'O último snapshot válido é usado offline. Atualizações indisponíveis aparecem como desatualizadas.': 'Der letzte gültige Stand wird offline genutzt. Nicht verfügbare Aktualisierungen erscheinen als veraltet.',
    'O Oscar Finanças não se conecta a contas bancárias nem movimenta dinheiro. Informações, simulações e projeções têm caráter informativo e usam dados fornecidos por você e referências de mercado atualizadas. Cotações podem apresentar atrasos ou diferenças em relação ao mercado.': 'Oscar Finanças verbindet sich nicht mit Bankkonten und bewegt kein Geld. Informationen, Simulationen und Prognosen dienen der Orientierung und nutzen Ihre Angaben sowie aktuelle Marktreferenzen. Kurse können verzögert sein oder vom Markt abweichen.',
    'Atualização oficial disponível após configurar os provedores.': 'Offizielle Aktualisierungen sind nach Einrichtung der Anbieter verfügbar.',
    'Atualizar agora': 'Jetzt aktualisieren',
    'Oscar Finanças — Clareza que transforma escolhas em patrimônio.':
        'Oscar Finanças — Klarheit, die Entscheidungen in Vermögen verwandelt.',
    'Organiza receitas, despesas, ganhos extras, saúde financeira, relatórios, agenda e investimentos sem movimentar seu dinheiro nem oferecer recomendação individual.': 'Ordnet Einnahmen, Ausgaben, Zusatzeinkünfte, Finanzgesundheit, Berichte, Kalender und Anlagen, ohne Geld zu bewegen oder individuell zu beraten.',
    'Saldo atual': 'Aktueller Saldo',
    'Aporte deste mês': 'Beitrag dieses Monats',
    'O aporte será incluído na lista de gastos do mês.':
        'Der Beitrag wird in die Ausgabenliste dieses Monats aufgenommen.',
    'Tipo de aporte': 'Beitragsart',
    'Aporte único': 'Einmaliger Beitrag',
    'Mensal fixo': 'Fester Monatsbeitrag',
    'Variável ou intermitente': 'Variabel oder unregelmäßig',
    'Meta de cobertura': 'Deckungsziel',
    'Salário simulado': 'Beispielgehalt',
    'Aluguel simulado': 'Beispielmiete',
    'Luz simulada': 'Beispielstrom',
    'Água simulada': 'Beispielwasser',
    'Internet simulada': 'Beispielinternet',
    'Mercado simulado': 'Beispieleinkäufe',
    'Reserva de emergência simulada': 'Beispiel-Notfallreserve',
    'Faculdade simulada': 'Beispiel-Studiengebühr',
    'Carro simulado': 'Beispielauto',
    'TV simulada': 'Beispiel-TV',
    'Freelance de design simulado': 'Beispiel-Designauftrag',
    'Projeto pontual simulado': 'Einmaliges Beispielprojekt',
    'Manutenção de computador simulada': 'Beispiel-Computerwartung',
    'Serviço técnico simulado': 'Technischer Beispieldienst',
    'Venda de bicicleta simulada': 'Beispiel-Fahrradverkauf',
    'Venda ocasional simulada': 'Gelegentlicher Beispielverkauf',
    'Venda de doces simulada': 'Beispiel-Süßwarenverkauf',
    'Renda complementar simulada': 'Beispiel-Zusatzeinkommen',
    'Tesouro Selic simulado': 'Beispiel-Staatsanleihe',
    'CDB simulado': 'Beispiel-Bankanlage',
    'Fundo imobiliário simulado': 'Beispiel-Immobilienfonds',
    'Ação simulada': 'Beispielaktie',
    'Versão 0.1.0 · compilação 1': 'Version 0.1.0 · Build 1',
  },
  SupportedAppLocale.frFr: {
    'Atualizar reserva de emergência': "Mettre à jour le fonds d'urgence",
    'Reserva de emergência': "Fonds d'urgence",
    'Cadastre despesas para visualizar a participação na renda.':
        'Ajoutez des dépenses pour voir leur part dans vos revenus.',
    'Origem dos ganhos': 'Sources de revenus',
    'Nenhum resultado local. O cadastro manual continua disponível.':
        'Aucun résultat local. La saisie manuelle reste disponible.',
    'Ela sairá da carteira, mas poderá ser restaurada por alguns segundos.': 'La position sera retirée, mais pourra être restaurée pendant quelques secondes.',
    'Evolução patrimonial': 'Évolution du patrimoine',
    'Aplicado + rendimento confirmado': 'Montant investi + rendement confirmé',
    'Estimativa educacional. Não é promessa de rentabilidade nem recomendação.': 'Estimation pédagogique. Ce n’est ni une promesse de rendement ni un conseil.',
    'Estimativa baseada em uma cesta média; não representa sua inflação pessoal.': 'Estimation fondée sur un panier moyen ; elle ne représente pas votre inflation personnelle.',
    'A alocação aparecerá quando você cadastrar uma posição.':
        'La répartition apparaîtra après l’ajout d’une position.',
    'Não foi possível gerar o relatório. Tente novamente.':
        'Impossible de générer le rapport. Réessayez.',
    'Este documento contém informações financeiras pessoais. Compartilhe somente com pessoas de confiança.': 'Ce document contient des informations financières personnelles. Partagez-le uniquement avec des personnes de confiance.',
    'O aplicativo agenda notificações locais. A entrega depende das permissões, economia de bateria, modo silencioso e políticas do aparelho.': 'L’application programme des notifications locales. Leur réception dépend des autorisations, de l’économie d’énergie, du mode silencieux et des règles de l’appareil.',
    'Todos os planos preservam seus dados e a navegação completa. Recursos avançados são explicados no ponto de uso.': 'Tous les forfaits conservent vos données et la navigation complète. Les fonctions avancées sont expliquées au moment de leur utilisation.',
    'Toque em um plano para visualizar os recursos disponíveis.':
        'Touchez un forfait pour voir les fonctionnalités disponibles.',
    'Uma indicação elegível pode oferecer até 40% de desconto. Benefícios não são cumulativos: prevalece sempre o maior desconto válido.': 'Un parrainage éligible peut offrir jusqu’à 40 % de remise. Les avantages ne se cumulent pas : la remise valide la plus élevée s’applique.',
    'O convite seguro será habilitado quando contas e validação do servidor estiverem disponíveis.': 'Les invitations sécurisées seront activées lorsque les comptes et la validation serveur seront disponibles.',
    'Benefícios úteis e transparentes para apoiar sua educação, bem-estar e vida prática.': 'Des avantages utiles et transparents pour soutenir votre éducation, votre bien-être et votre vie quotidienne.',
    'O Oscar Finanças poderá receber uma comissão se você contratar ou comprar por este link. Você será direcionado ao ambiente do parceiro.': 'Oscar Finanças peut recevoir une commission si vous achetez via ce lien. Vous serez redirigé vers l’espace du partenaire.',
    'O link deste parceiro ainda não está disponível.':
        'Le lien de ce partenaire n’est pas encore disponible.',
    'Região': 'Région',
    'Primeiro dia da semana': 'Premier jour de la semaine',
    'Ocultar valores ao abrir': 'Masquer les montants au démarrage',
    'As Telas 1, 2 e 3 começam protegidas.':
        'Les écrans 1, 2 et 3 démarrent protégés.',
    'Ocultar valores ao sair': 'Masquer les montants en quittant',
    'Oculta os valores quando o aplicativo vai para segundo plano.':
        'Masque les montants lorsque l’application passe en arrière-plan.',
    'Vibração e resposta tátil': 'Vibration et retour haptique',
    'Lembrete padrão para novos eventos':
        'Rappel par défaut pour les nouveaux événements',
    'Cotações e indicadores': 'Taux et indicateurs',
    'O último snapshot válido é usado offline. Atualizações indisponíveis aparecem como desatualizadas.': 'Le dernier instantané valide est utilisé hors ligne. Les mises à jour indisponibles apparaissent comme obsolètes.',
    'O Oscar Finanças não se conecta a contas bancárias nem movimenta dinheiro. Informações, simulações e projeções têm caráter informativo e usam dados fornecidos por você e referências de mercado atualizadas. Cotações podem apresentar atrasos ou diferenças em relação ao mercado.': 'Oscar Finanças ne se connecte pas aux comptes bancaires et ne déplace aucun argent. Les informations, simulations et projections sont indicatives et utilisent vos données ainsi que des références de marché actualisées. Les cours peuvent être retardés ou différer du marché.',
    'Atualização oficial disponível após configurar os provedores.': 'Les mises à jour officielles seront disponibles après configuration des fournisseurs.',
    'Atualizar agora': 'Mettre à jour',
    'Oscar Finanças — Clareza que transforma escolhas em patrimônio.':
        'Oscar Finanças — La clarté qui transforme les choix en patrimoine.',
    'Organiza receitas, despesas, ganhos extras, saúde financeira, relatórios, agenda e investimentos sem movimentar seu dinheiro nem oferecer recomendação individual.': 'Organise revenus, dépenses, gains complémentaires, santé financière, rapports, agenda et placements sans déplacer votre argent ni fournir de conseil individuel.',
    'Saldo atual': 'Solde actuel',
    'Aporte deste mês': 'Versement de ce mois',
    'O aporte será incluído na lista de gastos do mês.':
        'Le versement sera inclus dans la liste des dépenses de ce mois.',
    'Tipo de aporte': 'Type de versement',
    'Aporte único': 'Versement unique',
    'Mensal fixo': 'Mensuel fixe',
    'Variável ou intermitente': 'Variable ou intermittent',
    'Meta de cobertura': 'Objectif de couverture',
    'Salário simulado': 'Salaire d’exemple',
    'Aluguel simulado': 'Loyer d’exemple',
    'Luz simulada': 'Électricité d’exemple',
    'Água simulada': 'Eau d’exemple',
    'Internet simulada': 'Internet d’exemple',
    'Mercado simulado': 'Courses d’exemple',
    'Reserva de emergência simulada': 'Fonds d’urgence d’exemple',
    'Faculdade simulada': 'Frais d’études d’exemple',
    'Carro simulado': 'Voiture d’exemple',
    'TV simulada': 'TV d’exemple',
    'Freelance de design simulado': 'Mission design d’exemple',
    'Projeto pontual simulado': 'Projet ponctuel d’exemple',
    'Manutenção de computador simulada': 'Maintenance informatique d’exemple',
    'Serviço técnico simulado': 'Service technique d’exemple',
    'Venda de bicicleta simulada': 'Vente de vélo d’exemple',
    'Venda ocasional simulada': 'Vente occasionnelle d’exemple',
    'Venda de doces simulada': 'Vente de confiseries d’exemple',
    'Renda complementar simulada': 'Revenu complémentaire d’exemple',
    'Tesouro Selic simulado': 'Obligation publique d’exemple',
    'CDB simulado': 'Placement bancaire d’exemple',
    'Fundo imobiliário simulado': 'Fonds immobilier d’exemple',
    'Ação simulada': 'Action d’exemple',
    'Versão 0.1.0 · compilação 1': 'Version 0.1.0 · build 1',
  },
  SupportedAppLocale.hiIn: {
    'Atualizar reserva de emergência': 'आपातकालीन निधि अपडेट करें',
    'Reserva de emergência': 'आपातकालीन निधि',
    'Cadastre despesas para visualizar a participação na renda.':
        'आय में खर्च का हिस्सा देखने के लिए खर्च जोड़ें।',
    'Origem dos ganhos': 'आय के स्रोत',
    'Nenhum resultado local. O cadastro manual continua disponível.':
        'कोई स्थानीय परिणाम नहीं। मैन्युअल एंट्री अभी भी उपलब्ध है।',
    'Ela sairá da carteira, mas poderá ser restaurada por alguns segundos.': 'यह पोर्टफोलियो से हटेगा, लेकिन कुछ सेकंड तक पुनःस्थापित किया जा सकेगा।',
    'Evolução patrimonial': 'संपत्ति की वृद्धि',
    'Aplicado + rendimento confirmado': 'निवेशित राशि + पुष्टि किया गया रिटर्न',
    'Estimativa educacional. Não é promessa de rentabilidade nem recomendação.':
        'शैक्षिक अनुमान। यह रिटर्न का वादा या सलाह नहीं है।',
    'Estimativa baseada em uma cesta média; não representa sua inflação pessoal.':
        'औसत टोकरी पर आधारित अनुमान; यह आपकी व्यक्तिगत महंगाई नहीं दर्शाता।',
    'A alocação aparecerá quando você cadastrar uma posição.':
        'होल्डिंग जोड़ने के बाद आवंटन दिखेगा।',
    'Não foi possível gerar o relatório. Tente novamente.':
        'रिपोर्ट नहीं बन सकी। फिर कोशिश करें।',
    'Este documento contém informações financeiras pessoais. Compartilhe somente com pessoas de confiança.': 'इस दस्तावेज़ में व्यक्तिगत वित्तीय जानकारी है। केवल विश्वसनीय लोगों के साथ साझा करें।',
    'O aplicativo agenda notificações locais. A entrega depende das permissões, economia de bateria, modo silencioso e políticas do aparelho.': 'ऐप स्थानीय सूचनाएं निर्धारित करता है। वितरण अनुमति, बैटरी बचत, साइलेंट मोड और डिवाइस नीतियों पर निर्भर है।',
    'Todos os planos preservam seus dados e a navegação completa. Recursos avançados são explicados no ponto de uso.': 'सभी प्लान आपका डेटा और पूरा नेविगेशन बनाए रखते हैं। उन्नत सुविधाएं उपयोग के स्थान पर समझाई जाती हैं।',
    'Toque em um plano para visualizar os recursos disponíveis.':
        'उपलब्ध सुविधाएं देखने के लिए किसी प्लान पर टैप करें।',
    'Uma indicação elegível pode oferecer até 40% de desconto. Benefícios não são cumulativos: prevalece sempre o maior desconto válido.': 'योग्य रेफरल पर 40% तक छूट मिल सकती है। लाभ जोड़े नहीं जाते; सबसे बड़ी मान्य छूट लागू होती है।',
    'O convite seguro será habilitado quando contas e validação do servidor estiverem disponíveis.':
        'खाते और सर्वर सत्यापन उपलब्ध होने पर सुरक्षित आमंत्रण सक्रिय होंगे।',
    'Benefícios úteis e transparentes para apoiar sua educação, bem-estar e vida prática.': 'आपकी शिक्षा, कल्याण और दैनिक जीवन में मदद के लिए उपयोगी और पारदर्शी लाभ।',
    'O Oscar Finanças poderá receber uma comissão se você contratar ou comprar por este link. Você será direcionado ao ambiente do parceiro.': 'इस लिंक से खरीदने पर Oscar Finanças को कमीशन मिल सकता है। आपको पार्टनर के पेज पर भेजा जाएगा।',
    'O link deste parceiro ainda não está disponível.':
        'इस पार्टनर का लिंक अभी उपलब्ध नहीं है।',
    'Região': 'क्षेत्र',
    'Primeiro dia da semana': 'सप्ताह का पहला दिन',
    'Ocultar valores ao abrir': 'ऐप खुलने पर राशि छिपाएं',
    'As Telas 1, 2 e 3 começam protegidas.':
        'स्क्रीन 1, 2 और 3 सुरक्षित रूप से शुरू होती हैं।',
    'Ocultar valores ao sair': 'बाहर जाने पर राशि छिपाएं',
    'Oculta os valores quando o aplicativo vai para segundo plano.':
        'ऐप के बैकग्राउंड में जाने पर राशि छिपाता है।',
    'Vibração e resposta tátil': 'वाइब्रेशन और हैप्टिक फीडबैक',
    'Lembrete padrão para novos eventos': 'नए इवेंट के लिए डिफ़ॉल्ट रिमाइंडर',
    'Cotações e indicadores': 'दरें और संकेतक',
    'O último snapshot válido é usado offline. Atualizações indisponíveis aparecem como desatualizadas.': 'अंतिम मान्य स्नैपशॉट ऑफ़लाइन उपयोग होता है। अनुपलब्ध अपडेट पुराने के रूप में दिखाई देते हैं।',
    'O Oscar Finanças não se conecta a contas bancárias nem movimenta dinheiro. Informações, simulações e projeções têm caráter informativo e usam dados fornecidos por você e referências de mercado atualizadas. Cotações podem apresentar atrasos ou diferenças em relação ao mercado.': 'Oscar Finanças बैंक खातों से नहीं जुड़ता और पैसे का लेन-देन नहीं करता। जानकारी, सिमुलेशन और अनुमान केवल सूचनात्मक हैं तथा आपके डेटा और अपडेट किए गए बाज़ार संदर्भों का उपयोग करते हैं। बाज़ार भाव में देरी या अंतर हो सकता है।',
    'Atualização oficial disponível após configurar os provedores.':
        'प्रदाता कॉन्फ़िगर होने के बाद आधिकारिक अपडेट उपलब्ध होंगे।',
    'Atualizar agora': 'अभी अपडेट करें',
    'Oscar Finanças — Clareza que transforma escolhas em patrimônio.':
        'Oscar Finanças — स्पष्टता जो चुनावों को संपत्ति में बदलती है।',
    'Organiza receitas, despesas, ganhos extras, saúde financeira, relatórios, agenda e investimentos sem movimentar seu dinheiro nem oferecer recomendação individual.': 'आपके पैसे को हिलाए बिना या व्यक्तिगत सलाह दिए बिना आय, खर्च, अतिरिक्त कमाई, वित्तीय स्वास्थ्य, रिपोर्ट, कैलेंडर और निवेश को व्यवस्थित करता है।',
    'Saldo atual': 'वर्तमान शेष',
    'Aporte deste mês': 'इस महीने का योगदान',
    'O aporte será incluído na lista de gastos do mês.':
        'योगदान इस महीने की खर्च सूची में शामिल होगा।',
    'Tipo de aporte': 'योगदान का प्रकार',
    'Aporte único': 'एकमुश्त योगदान',
    'Mensal fixo': 'निश्चित मासिक',
    'Variável ou intermitente': 'परिवर्तनशील या रुक-रुक कर',
    'Meta de cobertura': 'कवरेज लक्ष्य',
    'Salário simulado': 'उदाहरण वेतन',
    'Aluguel simulado': 'उदाहरण किराया',
    'Luz simulada': 'उदाहरण बिजली',
    'Água simulada': 'उदाहरण पानी',
    'Internet simulada': 'उदाहरण इंटरनेट',
    'Mercado simulado': 'उदाहरण किराना',
    'Reserva de emergência simulada': 'उदाहरण आपातकालीन निधि',
    'Faculdade simulada': 'उदाहरण कॉलेज शुल्क',
    'Carro simulado': 'उदाहरण कार',
    'TV simulada': 'उदाहरण टीवी',
    'Freelance de design simulado': 'उदाहरण डिज़ाइन फ्रीलांस',
    'Projeto pontual simulado': 'उदाहरण एकमुश्त परियोजना',
    'Manutenção de computador simulada': 'उदाहरण कंप्यूटर रखरखाव',
    'Serviço técnico simulado': 'उदाहरण तकनीकी सेवा',
    'Venda de bicicleta simulada': 'उदाहरण साइकिल बिक्री',
    'Venda ocasional simulada': 'उदाहरण आकस्मिक बिक्री',
    'Venda de doces simulada': 'उदाहरण मिठाई बिक्री',
    'Renda complementar simulada': 'उदाहरण अतिरिक्त आय',
    'Tesouro Selic simulado': 'उदाहरण सरकारी बॉन्ड',
    'CDB simulado': 'उदाहरण बैंक निवेश',
    'Fundo imobiliário simulado': 'उदाहरण रियल एस्टेट फंड',
    'Ação simulada': 'उदाहरण शेयर',
    'Versão 0.1.0 · compilação 1': 'संस्करण 0.1.0 · बिल्ड 1',
  },
  SupportedAppLocale.ptBr: {},
};
