import '../../core/localization/app_locale.dart';

/// Final global UI catalogue. Keys are interface copy only; user-entered text
/// must be rendered with Flutter's native Text widget and never reaches here.
const globalUiTranslations = <SupportedAppLocale, Map<String, String>>{
  SupportedAppLocale.enUs: {
    'Ativos relacionados': 'Related assets',
    'Deslize para ver mais': 'Swipe to see more',
    'Dados simulados': 'Simulated data',
    'Aguardando cotação': 'Waiting for quote',
    'Cotação atualizada': 'Quote updated',
    'Última cotação salva': 'Last saved quote',
    'Privacidade dos valores': 'Value privacy',
    'Notificações': 'Notifications',
    'Lembretes da Agenda': 'Calendar reminders',
    'Fechamento mensal': 'Monthly closing',
    'Lançamentos recorrentes': 'Recurring entries',
    'Relatório mensal disponível': 'Monthly report available',
    'Plano e assinatura': 'Plan and subscription',
    'Domingo': 'Sunday',
    'Segunda-feira': 'Monday',
    'Escolher': 'Choose',
    'por mês': 'per month',
    'mês': 'month',
    'por ano': 'per year',
    'equivalente a': 'equivalent to',
    'economize': 'save',
    'Serviços do mês': 'Services this month',
    'Vendas do mês': 'Sales this month',
    'Adicionar serviço': 'Add service',
    'Adicionar venda': 'Add sale',
    'Somado à Tela 1': 'Included on Screen 1',
    'Nenhuma entrada neste mês.': 'No income this month.',
    'Nenhum gasto neste mês.': 'No expenses this month.',
    'Nenhuma parcela neste mês.': 'No installments this month.',
    'Adicionar entrada': 'Add income',
    'Adicionar gasto': 'Add expense',
    'Adicionar parcela': 'Add installment',
    'Sobra': 'Balance',
    'Déficit': 'Deficit',
    'Não calculado': 'Not calculated',
    'Não avaliado': 'Not evaluated',
    'Não avaliada': 'Not evaluated',
    'Cadastre gastos para calcular a cobertura':
        'Add expenses to calculate coverage',
    'Investimentos: Não avaliado': 'Investments: Not evaluated',
    'Valor do desconto': 'Discount amount',
    'Títulos públicos': 'Government bonds',
    'Renda fixa bancária': 'Bank fixed income',
    'Títulos empresariais': 'Corporate bonds',
    'Imobiliários': 'Real estate',
    'Ações': 'Stocks',
    'Cadastro manual': 'Manual entry',
    'Cotações indisponíveis': 'Quotes unavailable',
    'Cotações atualizadas com sucesso.': 'Quotes updated successfully.',
    'Não foi possível atualizar as cotações.': 'Quotes could not be updated.',
    'Sem conexão. O último valor disponível foi mantido.':
        'Offline. The latest available value was kept.',
    'Cotações demonstrativas desatualizadas · dados reais serão atualizados por adaptador seguro':
        'Outdated demonstration quotes · real data will be updated securely',
    'Cotações atualizadas · fonte de mercado': 'Quotes updated · market source',
    'Aviso educacional financeiro': 'Financial education notice',
    'Como funciona o Oscar Score': 'How Oscar Score works',
    'Tecnologia e Vida Prática': 'Technology and Everyday Life',
    'Dispositivos, software, conectividade, casa, estudo e trabalho.':
        'Devices, software, connectivity, home, study and work.',
    'Cotações e indicadores': 'Quotes and indicators',
    'DOM': 'SUN',
    'SEG': 'MON',
    'TER': 'TUE',
    'QUA': 'WED',
    'QUI': 'THU',
    'SEX': 'FRI',
    'SÁB': 'SAT',
  },
  SupportedAppLocale.deDe: {
    'Ativos relacionados': 'Zugehörige Anlagen',
    'Deslize para ver mais': 'Wischen für weitere',
    'Dados simulados': 'Simulierte Daten',
    'Aguardando cotação': 'Kurs wird erwartet',
    'Cotação atualizada': 'Kurs aktualisiert',
    'Última cotação salva': 'Zuletzt gespeicherter Kurs',
    'Privacidade dos valores': 'Werteschutz',
    'Notificações': 'Benachrichtigungen',
    'Lembretes da Agenda': 'Kalendererinnerungen',
    'Fechamento mensal': 'Monatsabschluss',
    'Lançamentos recorrentes': 'Wiederkehrende Einträge',
    'Relatório mensal disponível': 'Monatsbericht verfügbar',
    'Plano e assinatura': 'Tarif und Abonnement',
    'Domingo': 'Sonntag',
    'Segunda-feira': 'Montag',
    'Escolher': 'Wählen',
    'por mês': 'pro Monat',
    'mês': 'Monat',
    'por ano': 'pro Jahr',
    'equivalente a': 'entspricht',
    'economize': 'sparen',
    'Serviços do mês': 'Dienstleistungen dieses Monats',
    'Vendas do mês': 'Verkäufe dieses Monats',
    'Adicionar serviço': 'Dienstleistung hinzufügen',
    'Adicionar venda': 'Verkauf hinzufügen',
    'Somado à Tela 1': 'In Ansicht 1 enthalten',
    'Nenhuma entrada neste mês.': 'Keine Einnahmen in diesem Monat.',
    'Nenhum gasto neste mês.': 'Keine Ausgaben in diesem Monat.',
    'Nenhuma parcela neste mês.': 'Keine Raten in diesem Monat.',
    'Adicionar entrada': 'Einnahme hinzufügen',
    'Adicionar gasto': 'Ausgabe hinzufügen',
    'Adicionar parcela': 'Rate hinzufügen',
    'Sobra': 'Überschuss',
    'Déficit': 'Defizit',
    'Não calculado': 'Nicht berechnet',
    'Não avaliado': 'Nicht bewertet',
    'Não avaliada': 'Nicht bewertet',
    'Cadastre gastos para calcular a cobertura':
        'Erfassen Sie Ausgaben, um die Deckung zu berechnen',
    'Valor do desconto': 'Rabattbetrag',
    'Títulos públicos': 'Staatsanleihen',
    'Renda fixa bancária': 'Bank-Festgeld',
    'Títulos empresariais': 'Unternehmensanleihen',
    'Imobiliários': 'Immobilien',
    'Ações': 'Aktien',
    'Cadastro manual': 'Manueller Eintrag',
    'Cotações indisponíveis': 'Kurse nicht verfügbar',
    'Cotações atualizadas com sucesso.': 'Kurse erfolgreich aktualisiert.',
    'Não foi possível atualizar as cotações.':
        'Kurse konnten nicht aktualisiert werden.',
    'Sem conexão. O último valor disponível foi mantido.':
        'Offline. Der letzte verfügbare Wert wurde beibehalten.',
    'Cotações demonstrativas desatualizadas · dados reais serão atualizados por adaptador seguro':
        'Veraltete Demokurse · Marktdaten werden sicher aktualisiert',
    'Cotações atualizadas · fonte de mercado':
        'Kurse aktualisiert · Marktquelle',
    'Aviso educacional financeiro': 'Finanzieller Bildungshinweis',
    'Como funciona o Oscar Score': 'So funktioniert der Oscar Score',
    'Dispositivos, software, conectividade, casa, estudo e trabalho.':
        'Geräte, Software, Konnektivität, Zuhause, Studium und Arbeit.',
    'DOM': 'SO',
    'SEG': 'MO',
    'TER': 'DI',
    'QUA': 'MI',
    'QUI': 'DO',
    'SEX': 'FR',
    'SÁB': 'SA',
  },
  SupportedAppLocale.frFr: {
    'Ativos relacionados': 'Actifs associés',
    'Deslize para ver mais': 'Balayez pour en voir plus',
    'Dados simulados': 'Données simulées',
    'Aguardando cotação': 'En attente de cotation',
    'Cotação atualizada': 'Cotation actualisée',
    'Última cotação salva': 'Dernière cotation enregistrée',
    'Privacidade dos valores': 'Confidentialité des montants',
    'Notificações': 'Notifications',
    'Lembretes da Agenda': 'Rappels du calendrier',
    'Fechamento mensal': 'Clôture mensuelle',
    'Lançamentos recorrentes': 'Écritures récurrentes',
    'Relatório mensal disponível': 'Rapport mensuel disponible',
    'Plano e assinatura': 'Forfait et abonnement',
    'Domingo': 'Dimanche',
    'Segunda-feira': 'Lundi',
    'Escolher': 'Choisir',
    'por mês': 'par mois',
    'mês': 'mois',
    'por ano': 'par an',
    'equivalente a': 'équivaut à',
    'economize': 'économisez',
    'Serviços do mês': 'Services du mois',
    'Vendas do mês': 'Ventes du mois',
    'Adicionar serviço': 'Ajouter un service',
    'Adicionar venda': 'Ajouter une vente',
    'Somado à Tela 1': 'Inclus dans l’écran 1',
    'Nenhuma entrada neste mês.': 'Aucun revenu ce mois-ci.',
    'Nenhum gasto neste mês.': 'Aucune dépense ce mois-ci.',
    'Nenhuma parcela neste mês.': 'Aucune échéance ce mois-ci.',
    'Adicionar entrada': 'Ajouter un revenu',
    'Adicionar gasto': 'Ajouter une dépense',
    'Adicionar parcela': 'Ajouter une échéance',
    'Sobra': 'Solde',
    'Déficit': 'Déficit budgétaire',
    'Não calculado': 'Non calculé',
    'Não avaliado': 'Non évalué',
    'Não avaliada': 'Non évaluée',
    'Cadastre gastos para calcular a cobertura':
        'Ajoutez des dépenses pour calculer la couverture',
    'Valor do desconto': 'Montant de la remise',
    'Títulos públicos': 'Obligations d’État',
    'Renda fixa bancária': 'Revenu fixe bancaire',
    'Títulos empresariais': 'Obligations d’entreprise',
    'Imobiliários': 'Immobilier',
    'Ações': 'Actions',
    'Cadastro manual': 'Saisie manuelle',
    'Cotações indisponíveis': 'Cours indisponibles',
    'Cotações atualizadas com sucesso.': 'Cours mis à jour.',
    'Não foi possível atualizar as cotações.':
        'Impossible de mettre à jour les cours.',
    'Sem conexão. O último valor disponível foi mantido.':
        'Hors ligne. La dernière valeur disponible a été conservée.',
    'Cotações demonstrativas desatualizadas · dados reais serão atualizados por adaptador seguro': 'Cours de démonstration obsolètes · les données réelles seront mises à jour en sécurité',
    'Cotações atualizadas · fonte de mercado':
        'Cours actualisés · source de marché',
    'Aviso educacional financeiro': 'Avertissement pédagogique financier',
    'Como funciona o Oscar Score': 'Fonctionnement de l’Oscar Score',
    'Dispositivos, software, conectividade, casa, estudo e trabalho.':
        'Appareils, logiciels, connectivité, maison, études et travail.',
    'DOM': 'DIM',
    'SEG': 'LUN',
    'TER': 'MAR',
    'QUA': 'MER',
    'QUI': 'JEU',
    'SEX': 'VEN',
    'SÁB': 'SAM',
  },
  SupportedAppLocale.hiIn: {
    'Ativos relacionados': 'संबंधित परिसंपत्तियाँ',
    'Deslize para ver mais': 'और देखने के लिए स्वाइप करें',
    'Dados simulados': 'अनुमानित डेटा',
    'Aguardando cotação': 'भाव की प्रतीक्षा',
    'Cotação atualizada': 'भाव अपडेट हुआ',
    'Última cotação salva': 'अंतिम सहेजा गया भाव',
    'Privacidade dos valores': 'राशियों की गोपनीयता',
    'Notificações': 'सूचनाएं',
    'Lembretes da Agenda': 'कैलेंडर रिमाइंडर',
    'Fechamento mensal': 'मासिक समापन',
    'Lançamentos recorrentes': 'आवर्ती प्रविष्टियां',
    'Relatório mensal disponível': 'मासिक रिपोर्ट उपलब्ध',
    'Plano e assinatura': 'योजना और सदस्यता',
    'Domingo': 'रविवार',
    'Segunda-feira': 'सोमवार',
    'Escolher': 'चुनें',
    'por mês': 'प्रति माह',
    'mês': 'माह',
    'por ano': 'प्रति वर्ष',
    'equivalente a': 'के बराबर',
    'economize': 'बचाएं',
    'Serviços do mês': 'इस महीने की सेवाएं',
    'Vendas do mês': 'इस महीने की बिक्री',
    'Adicionar serviço': 'सेवा जोड़ें',
    'Adicionar venda': 'बिक्री जोड़ें',
    'Somado à Tela 1': 'स्क्रीन 1 में शामिल',
    'Nenhuma entrada neste mês.': 'इस महीने कोई आय नहीं।',
    'Nenhum gasto neste mês.': 'इस महीने कोई खर्च नहीं।',
    'Nenhuma parcela neste mês.': 'इस महीने कोई किस्त नहीं।',
    'Adicionar entrada': 'आय जोड़ें',
    'Adicionar gasto': 'खर्च जोड़ें',
    'Adicionar parcela': 'किस्त जोड़ें',
    'Sobra': 'शेष',
    'Déficit': 'घाटा',
    'Não calculado': 'गणना नहीं हुई',
    'Não avaliado': 'मूल्यांकन नहीं हुआ',
    'Não avaliada': 'मूल्यांकन नहीं हुआ',
    'Cadastre gastos para calcular a cobertura':
        'कवरेज की गणना के लिए खर्च जोड़ें',
    'Valor do desconto': 'छूट की राशि',
    'Títulos públicos': 'सरकारी बॉन्ड',
    'Renda fixa bancária': 'बैंक निश्चित आय',
    'Títulos empresariais': 'कॉर्पोरेट बॉन्ड',
    'Imobiliários': 'रियल एस्टेट',
    'Ações': 'शेयर',
    'Cadastro manual': 'मैनुअल प्रविष्टि',
    'Cotações indisponíveis': 'दरें उपलब्ध नहीं',
    'Cotações atualizadas com sucesso.': 'दरें सफलतापूर्वक अपडेट हुईं।',
    'Não foi possível atualizar as cotações.': 'दरें अपडेट नहीं हो सकीं।',
    'Sem conexão. O último valor disponível foi mantido.':
        'ऑफ़लाइन। अंतिम उपलब्ध मूल्य रखा गया।',
    'Cotações demonstrativas desatualizadas · dados reais serão atualizados por adaptador seguro':
        'पुरानी नमूना दरें · वास्तविक डेटा सुरक्षित रूप से अपडेट होगा',
    'Cotações atualizadas · fonte de mercado': 'दरें अपडेट हुईं · बाजार स्रोत',
    'Aviso educacional financeiro': 'वित्तीय शिक्षा सूचना',
    'Como funciona o Oscar Score': 'Oscar Score कैसे काम करता है',
    'Dispositivos, software, conectividade, casa, estudo e trabalho.':
        'डिवाइस, सॉफ्टवेयर, कनेक्टिविटी, घर, पढ़ाई और काम।',
    'DOM': 'रवि',
    'SEG': 'सोम',
    'TER': 'मंगल',
    'QUA': 'बुध',
    'QUI': 'गुरु',
    'SEX': 'शुक्र',
    'SÁB': 'शनि',
  },
  SupportedAppLocale.ptBr: {},
};
const globalUiFragments = <SupportedAppLocale, Map<String, String>>{
  SupportedAppLocale.enUs: {
    'Cobre aproximadamente ': 'Covers approximately ',
    ' guardados': ' saved',
    ' meses': ' months',
    'Não calculado': 'Not calculated',
    'Não avaliado': 'Not evaluated',
    'Não avaliada': 'Not evaluated',
    'Títulos públicos': 'Government bonds',
    'Renda fixa bancária': 'Bank fixed income',
    'Títulos empresariais': 'Corporate bonds',
    'Imobiliários': 'Real estate',
    'Ações': 'Stocks',
    'Cadastro manual': 'Manual entry',
    'Meta: ': 'Target: ',
    'Fluxo do mês: ': 'Monthly flow: ',
    'Reserva: ': 'Emergency fund: ',
    'Escolher ': 'Choose ',
    ' será removido deste mês.': ' will be removed from this month.',
    ' será removido de ': ' will be removed from ',
  },
  SupportedAppLocale.deDe: {
    'Cobre aproximadamente ': 'Deckt ungefähr ',
    ' guardados': ' gespart',
    ' meses': ' Monate',
    'Não calculado': 'Nicht berechnet',
    'Não avaliado': 'Nicht bewertet',
    'Não avaliada': 'Nicht bewertet',
    'Títulos públicos': 'Staatsanleihen',
    'Renda fixa bancária': 'Bank-Festgeld',
    'Títulos empresariais': 'Unternehmensanleihen',
    'Imobiliários': 'Immobilien',
    'Ações': 'Aktien',
    'Cadastro manual': 'Manueller Eintrag',
    'Meta: ': 'Ziel: ',
    'Fluxo do mês: ': 'Monatlicher Verlauf: ',
    'Reserva: ': 'Notfallreserve: ',
    'Escolher ': 'Wählen: ',
    ' será removido deste mês.': ' wird aus diesem Monat entfernt.',
    ' será removido de ': ' wird entfernt aus ',
  },
  SupportedAppLocale.frFr: {
    'Cobre aproximadamente ': 'Couvre environ ',
    ' guardados': ' épargnés',
    ' meses': ' mois',
    'Não calculado': 'Non calculé',
    'Não avaliado': 'Non évalué',
    'Não avaliada': 'Non évaluée',
    'Títulos públicos': 'Obligations d’État',
    'Renda fixa bancária': 'Revenu fixe bancaire',
    'Títulos empresariais': 'Obligations d’entreprise',
    'Imobiliários': 'Immobilier',
    'Ações': 'Actions',
    'Cadastro manual': 'Saisie manuelle',
    'Meta: ': 'Objectif : ',
    'Fluxo do mês: ': 'Flux du mois : ',
    'Reserva: ': 'Fonds d’urgence : ',
    'Escolher ': 'Choisir ',
    ' será removido deste mês.': ' sera supprimé de ce mois.',
    ' será removido de ': ' sera supprimé de ',
  },
  SupportedAppLocale.hiIn: {
    'Cobre aproximadamente ': 'लगभग कवर करता है: ',
    ' guardados': ' सुरक्षित',
    ' meses': ' महीने',
    'Não calculado': 'गणना नहीं हुई',
    'Não avaliado': 'मूल्यांकन नहीं हुआ',
    'Não avaliada': 'मूल्यांकन नहीं हुआ',
    'Títulos públicos': 'सरकारी बॉन्ड',
    'Renda fixa bancária': 'बैंक निश्चित आय',
    'Títulos empresariais': 'कॉर्पोरेट बॉन्ड',
    'Imobiliários': 'रियल एस्टेट',
    'Ações': 'शेयर',
    'Cadastro manual': 'मैनुअल प्रविष्टि',
    'Meta: ': 'लक्ष्य: ',
    'Fluxo do mês: ': 'मासिक प्रवाह: ',
    'Reserva: ': 'आपातकालीन निधि: ',
    'Escolher ': 'चुनें ',
    ' será removido deste mês.': ' इस महीने से हटाया जाएगा।',
    ' será removido de ': ' से हटाया जाएगा: ',
  },
  SupportedAppLocale.ptBr: {},
};
