// Reviewed product copy for this language only. No cross-language fallback.
const deDeMessages = <String, String>{
  "Entradas": "Einnahmen",
  "Gastos": "Ausgaben",
  "Parcelas Longas": "Langfristige Raten",
  "Participação das despesas": "Ausgabenanteile",
  "Nova entrada": "Neue Einnahme",
  "Novo gasto": "Neue Ausgabe",
  "Editar entrada": "Einnahme bearbeiten",
  "Editar gasto": "Ausgabe bearbeiten",
  "Editar serviço": "Dienstleistung bearbeiten",
  "Editar venda": "Verkauf bearbeiten",
  "Novo serviço": "Neue Dienstleistung",
  "Nova venda": "Neuer Verkauf",
  "Nova parcela": "Neue Rate",
  "Editar parcela": "Rate bearbeiten",
  "Parcela atual": "Aktuelle Rate",
  "Total de parcelas": "Gesamtzahl der Raten",
  "Informe uma parcela válida, como 5 de 36.":
      "Geben Sie eine gültige Rate ein, zum Beispiel 5 von 36.",
  "Nome": "Name",
  "Descrição": "Beschreibung",
  "Valor": "Betrag",
  "Desconto": "Rabatt",
  "Sem desconto": "Kein Rabatt",
  "Valor fixo": "Fester Betrag",
  "Percentual": "Prozent",
  "Recorrente": "Wiederkehrend",
  "Cancelar": "Abbrechen",
  "Salvar": "Speichern",
  "Editar": "Bearbeiten",
  "Excluir": "Löschen",
  "Confirmar exclusão": "Löschen bestätigen",
  "Item removido.": "Eintrag entfernt.",
  "Desfazer": "Rückgängig",
  "Reserva de Emergência": "Notfallreserve",
  "Valor guardado": "Gesparter Betrag",
  "1 mês": "1 Monat",
  "3 meses": "3 Monate",
  "6 meses": "6 Monate",
  "Atualizar valor": "Betrag aktualisieren",
  "Aporte entra nos gastos; zero salva só a meta.":
      "Der Beitrag wird als Ausgabe erfasst; null speichert nur das Ziel.",
  "Investimentos: Não avaliado": "Investitionen: Nicht bewertet",
  "Não foi possível carregar seus dados.":
      "Ihre Daten konnten nicht geladen werden.",
  "Tentar novamente": "Erneut versuchen",
  "Total realizado no mês": "Gesamteinnahmen im Monat",
  "Nenhum lançamento nesta categoria.": "Keine Einträge in dieser Kategorie.",
  "Ganho recorrente": "Wiederkehrendes Einkommen",
  "Somar à renda extra da Tela 1":
      "Zu den Zusatzeinnahmen auf Seite 1 addieren",
  "Ganho removido.": "Einnahme entfernt.",
  "Sem ganhos": "Keine Einnahmen",
  "Serviços": "Dienstleistungen",
  "Vendas": "Verkäufe",
  "Pesquisar ou adicionar investimento": "Anlage suchen oder hinzufügen",
  "Limpar pesquisa": "Suche löschen",
  "Alocação de ativos": "Vermögensaufteilung",
  "Símbolo ou código": "Symbol oder Code",
  "Família": "Kategorie",
  "Moeda original": "Originalwährung",
  "Valor aplicado": "Anlagebetrag",
  "Rendimento do mês": "Monatlicher Ertrag",
  "Confirmar posição": "Position bestätigen",
  "Excluir esta posição?": "Diese Position löschen?",
  "Posição excluída.": "Position gelöscht.",
  "Nenhuma posição nesta área e mês.":
      "Keine Position in diesem Bereich und Monat.",
  "Adicionar manualmente": "Manuell hinzufügen",
  "Renda Fixa": "Festverzinsliche Anlagen",
  "Imobiliários": "Immobilien",
  "Ações e ETFs": "Aktien und ETFs",
  "Simulador": "Simulator",
  "Calculadora de juros compostos": "Zinseszinsrechner",
  "Aporte mensal": "Monatliche Einzahlung",
  "Taxa (%)": "Zinssatz (%)",
  "Mensal": "Monatlich",
  "Anual": "Jährlich",
  "Prazo em meses": "Laufzeit in Monaten",
  "Calcular cenário": "Szenario berechnen",
  "Crescimento acima da inflação": "Wachstum über der Inflation",
  "Sua vida financeira": "Ihr Finanzleben",
  "em relatórios claros": "in klaren Berichten",
  "Relatório do mês atual": "Bericht des aktuellen Monats",
  "Relatório dos últimos 3 meses": "Bericht der letzten 3 Monate",
  "Relatório dos últimos 6 meses": "Bericht der letzten 6 Monate",
  "Relatório anual": "Jahresbericht",
  "Imprimir": "Drucken",
  "Compartilhar": "Teilen",
  "Antes de compartilhar": "Vor dem Teilen",
  "Continuar": "Weiter",
  "Sem movimentação": "Keine Aktivität",
  "Investimentos e crescimento real: Não avaliado":
      "Investitionen und reales Wachstum: Nicht bewertet",
  "Fechar": "Schließen",
  "Nenhum compromisso neste dia.": "Keine Termine an diesem Tag.",
  "Adicionar compromisso": "Termin hinzufügen",
  "Novo compromisso": "Neuer Termin",
  "Título *": "Titel *",
  "Observação opcional": "Optionale Notiz",
  "Recorrência": "Wiederholung",
  "Nenhuma": "Keine",
  "Semanal": "Wöchentlich",
  "Lembretes locais": "Lokale Erinnerungen",
  "Informe o título do compromisso.": "Geben Sie einen Termintitel ein.",
  "Compromisso excluído.": "Termin gelöscht.",
  "Compromissos\npessoais": "Persönliche\nTermine",
  "Serviços\nagendados": "Geplante\nDienste",
  "Compromissos\nprofissionais": "Berufliche\nTermine",
  "Plano Básico": "Basistarif",
  "Plano Plus": "Plus-Tarif",
  "Plano Pro": "Pro-Tarif",
  "Plano atual": "Aktueller Tarif",
  "Convidar": "Einladen",
  "Convide um Amigo": "Freund einladen",
  "Escolha a clareza que acompanha seu momento":
      "Wählen Sie die Klarheit, die zu Ihnen passt",
  "Oscar Clube": "Oscar Club",
  "Parceria remunerada": "Bezahlte Partnerschaft",
  "Ver benefício": "Vorteil ansehen",
  "Continuar para o parceiro": "Zum Partner wechseln",
  "Nenhum benefício válido disponível para sua região neste momento.":
      "Zurzeit ist für Ihre Region kein gültiger Vorteil verfügbar.",
  "Idioma, região e moeda": "Sprache, Region und Währung",
  "Idioma": "Sprache",
  "Moeda principal": "Hauptwährung",
  "Salvar alterações": "Änderungen speichern",
  "Configurações atualizadas": "Einstellungen aktualisiert",
  "Aparência": "Darstellung",
  "Automático": "Automatisch",
  "Claro": "Hell",
  "Escuro": "Dunkel",
  "Atualizar reserva de emergência": "Notgroschen aktualisieren",
  "Reserva de emergência": "Notgroschen",
  "Cadastre despesas para visualizar a participação na renda.":
      "Erfassen Sie Ausgaben, um deren Anteil am Einkommen zu sehen.",
  "Origem dos ganhos": "Einnahmequellen",
  "Nenhum resultado local. O cadastro manual continua disponível.":
      "Keine lokalen Ergebnisse. Die manuelle Eingabe bleibt verfügbar.",
  "Ela sairá da carteira, mas poderá ser restaurada por alguns segundos.": "Die Position wird entfernt, kann aber einige Sekunden lang wiederhergestellt werden.",
  "Evolução patrimonial": "Vermögensentwicklung",
  "1 ano": "1 Jahr",
  "Todo período": "Gesamter Zeitraum",
  "Patrimônio registrado": "Erfasster Depotwert",
  "Câmbio indisponível: não é possível somar investimentos em moedas diferentes.": "Wechselkurse sind nicht verfügbar; Anlagen in verschiedenen Währungen können nicht addiert werden.",
  "Valorização acumulada": "Kumulierte Erträge",
  "Somente rendimentos registrados; não inclui variação de mercado.":
      "Nur erfasste Erträge; Marktwertänderungen sind nicht enthalten.",
  "Nenhum investimento registrado neste período.":
      "In diesem Zeitraum sind keine Anlagen erfasst.",
  "Ver valores mês a mês": "Monatliche Werte anzeigen",
  "Aplicado + rendimento confirmado": "Anlagebetrag + bestätigte Rendite",
  "Aportes e rendimentos registrados": "Erfasste Einzahlungen und Erträge",
  "Total registrado": "Erfasste Gesamtsumme",
  "Variação no período": "Veränderung im Zeitraum",
  "Não inclui oscilações de mercado nem representa rentabilidade.":
      "Kursänderungen sind nicht enthalten; dies ist keine Anlagerendite.",
  "Estimativa educacional. Não é promessa de rentabilidade nem recomendação.":
      "Schätzung zu Bildungszwecken. Keine Renditezusage oder Empfehlung.",
  "Estimativa baseada em uma cesta média; não representa sua inflação pessoal.": "Schätzung anhand eines Durchschnittswarenkorbs; sie entspricht nicht Ihrer persönlichen Inflation.",
  "A alocação aparecerá quando você cadastrar uma posição.":
      "Die Aufteilung erscheint, sobald Sie eine Position erfassen.",
  "Não foi possível gerar o relatório. Tente novamente.":
      "Der Bericht konnte nicht erstellt werden. Versuchen Sie es erneut.",
  "Este documento contém informações financeiras pessoais. Compartilhe somente com pessoas de confiança.": "Dieses Dokument enthält persönliche Finanzdaten. Teilen Sie es nur mit vertrauenswürdigen Personen.",
  "O aplicativo agenda notificações locais. A entrega depende das permissões, economia de bateria, modo silencioso e políticas do aparelho.": "Die App plant lokale Benachrichtigungen. Die Zustellung hängt von Berechtigungen, Energiesparen, Lautlosmodus und Geräterichtlinien ab.",
  "Todos os planos preservam seus dados e a navegação completa. Recursos avançados são explicados no ponto de uso.": "Alle Tarife bewahren Ihre Daten und die vollständige Navigation. Erweiterte Funktionen werden am Einsatzort erklärt.",
  "Toque em um plano para visualizar os recursos disponíveis.":
      "Tippen Sie auf einen Tarif, um die verfügbaren Funktionen anzuzeigen.",
  "Uma indicação elegível pode oferecer até 40% de desconto. Benefícios não são cumulativos: prevalece sempre o maior desconto válido.": "Eine berechtigte Empfehlung kann bis zu 40 % Rabatt bieten. Vorteile sind nicht kombinierbar; es gilt stets der höchste gültige Rabatt.",
  "O convite seguro será habilitado quando contas e validação do servidor estiverem disponíveis.": "Sichere Einladungen werden aktiviert, sobald Konten und Serverprüfung verfügbar sind.",
  "Benefícios úteis e transparentes para apoiar sua educação, bem-estar e vida prática. Ofertas nunca alteram seu Oscar Score nem acessam seus dados financeiros.": "Nützliche, transparente Vorteile für Bildung, Wohlbefinden und Alltag. Angebote beeinflussen weder Ihren Oscar Score noch greifen sie auf Finanzdaten zu.",
  "O Oscar Finanças poderá receber uma comissão se você contratar ou comprar por este link. Você será direcionado ao ambiente do parceiro.": "Oscar Finanças kann eine Provision erhalten, wenn Sie über diesen Link kaufen. Sie werden zum Partner weitergeleitet.",
  "O link deste parceiro ainda não está disponível.":
      "Der Link dieses Partners ist noch nicht verfügbar.",
  "Região": "Region",
  "Primeiro dia da semana": "Erster Wochentag",
  "Ocultar valores ao abrir": "Werte beim Start ausblenden",
  "As Telas 1, 2 e 3 começam protegidas.":
      "Die Ansichten 1, 2 und 3 starten geschützt.",
  "Ocultar valores ao sair": "Werte beim Verlassen ausblenden",
  "Oculta os valores quando o aplicativo vai para segundo plano.":
      "Blendet Werte aus, wenn die App in den Hintergrund wechselt.",
  "Vibração e resposta tátil": "Vibration und haptisches Feedback",
  "Lembrete padrão para novos eventos": "Standarderinnerung für neue Termine",
  "Cotações e indicadores": "Kurse und Indikatoren",
  "O último snapshot válido é usado offline. Atualizações indisponíveis aparecem como desatualizadas.": "Der letzte gültige Stand wird offline genutzt. Nicht verfügbare Aktualisierungen erscheinen als veraltet.",
  "O Oscar Finanças não se conecta a contas bancárias nem movimenta dinheiro. Informações, simulações e projeções têm caráter informativo e usam dados fornecidos por você e referências de mercado atualizadas. Cotações podem apresentar atrasos ou diferenças em relação ao mercado.": "Oscar Finanças verbindet sich nicht mit Bankkonten und bewegt kein Geld. Informationen, Simulationen und Prognosen dienen der Orientierung und nutzen Ihre Angaben sowie aktuelle Marktreferenzen. Kurse können verzögert sein oder vom Markt abweichen.",
  "Atualização oficial disponível após configurar os provedores.": "Offizielle Aktualisierungen sind nach Einrichtung der Anbieter verfügbar.",
  "Atualizar agora": "Jetzt aktualisieren",
  "Disponível em {tempo}": "Verfügbar in {tempo}",
  "Oscar Finanças — Clareza que transforma escolhas em patrimônio.":
      "Oscar Finanças — Klarheit, die Entscheidungen in Vermögen verwandelt.",
  "Organiza receitas, despesas, ganhos extras, saúde financeira, relatórios, agenda e investimentos sem movimentar seu dinheiro nem oferecer recomendação individual.": "Ordnet Einnahmen, Ausgaben, Zusatzeinkünfte, Finanzgesundheit, Berichte, Kalender und Anlagen, ohne Geld zu bewegen oder individuell zu beraten.",
  "Saldo atual": "Aktueller Saldo",
  "Aporte deste mês": "Beitrag dieses Monats",
  "O aporte será incluído na lista de gastos do mês.":
      "Der Beitrag wird in die Ausgabenliste dieses Monats aufgenommen.",
  "Tipo de aporte": "Beitragsart",
  "Aporte único": "Einmaliger Beitrag",
  "Mensal fixo": "Fester Monatsbeitrag",
  "Variável ou intermitente": "Variabel oder unregelmäßig",
  "Meta de cobertura": "Deckungsziel",
  "Salário simulado": "Beispielgehalt",
  "Aluguel simulado": "Beispielmiete",
  "Luz simulada": "Beispielstrom",
  "Água simulada": "Beispielwasser",
  "Internet simulada": "Beispielinternet",
  "Mercado simulado": "Beispieleinkäufe",
  "Reserva de emergência simulada": "Beispiel-Notfallreserve",
  "Faculdade simulada": "Beispiel-Studiengebühr",
  "Carro simulado": "Beispielauto",
  "TV simulada": "Beispiel-TV",
  "Freelance de design simulado": "Beispiel-Designauftrag",
  "Serviço freelance": "Freiberuflicher Auftrag",
  "Projeto ou atendimento do mês": "Projekt oder Auftrag in diesem Monat",
  "Projeto pontual simulado": "Einmaliges Beispielprojekt",
  "Manutenção de computador simulada": "Beispiel-Computerwartung",
  "Serviço técnico simulado": "Technischer Beispieldienst",
  "Venda de bicicleta simulada": "Beispiel-Fahrradverkauf",
  "Venda ocasional simulada": "Gelegentlicher Beispielverkauf",
  "Venda ocasional": "Gelegenheitsverkauf",
  "Venda de item ou produto": "Verkauf eines Artikels oder Produkts",
  "Venda de doces simulada": "Beispiel-Süßwarenverkauf",
  "Renda complementar simulada": "Beispiel-Zusatzeinkommen",
  "Tesouro Selic simulado": "Beispiel-Staatsanleihe",
  "CDB simulado": "Beispiel-Bankanlage",
  "Fundo imobiliário simulado": "Beispiel-Immobilienfonds",
  "Ação simulada": "Beispielaktie",
  "Versão 0.1.0 · compilação 1": "Version 0.1.0 · Build 1",
  "Organização financeira essencial, sem custo.":
      "Wesentliche Finanzorganisation, kostenlos.",
  "Painel Financeiro completo, Reserva de Emergência e Oscar Score":
      "Vollständiges Finanz-Dashboard, Notgroschen und Oscar Score",
  "Relatório mensal com impressão e compartilhamento":
      "Monatsbericht zum Drucken und Teilen",
  "Agenda completa com recorrência e lembretes locais":
      "Vollständiger Kalender mit Wiederholungen und lokalen Erinnerungen",
  "Oscar Clube e Configurações": "Oscar Club und Einstellungen",
  "Grátis": "Kostenlos",
  "Mais controle para quem transforma trabalho em renda.":
      "Mehr Kontrolle für alle, die Arbeit in Einkommen verwandeln.",
  "Tudo do Plano Básico": "Alles aus dem Basistarif",
  "Ganho Extra completo: Serviços, Vendas e recorrências": "Vollständige Zusatzeinkünfte: Dienstleistungen, Verkäufe und Wiederholungen",
  "Integração Agenda → Ganho Extra": "Kalender-→-Zusatzeinkünfte-Integration",
  "Relatórios do mês e dos últimos 3 meses":
      "Berichte für den Monat und die letzten 3 Monate",
  "Visão patrimonial completa, simples e internacional.":
      "Vollständige, einfache und internationale Vermögenssicht.",
  "Tudo do Plano Plus": "Alles aus dem Plus-Tarif",
  "Investimentos, busca internacional, ações, ETFs e calculadora":
      "Anlagen, internationale Suche, Aktien, ETFs und Rechner",
  "Crescimento real e resumo em BRL, USD, EUR e INR":
      "Reales Wachstum und Übersicht in BRL, USD, EUR und INR",
  "Relatórios de 1, 3, 6 e 12 meses": "Berichte für 1, 3, 6 und 12 Monate",
  "Educação e Carreira": "Bildung und Karriere",
  "Cursos, idiomas, livros, certificações e ferramentas profissionais.":
      "Kurse, Sprachen, Bücher, Zertifikate und berufliche Werkzeuge.",
  "Saúde, Beleza e Bem-estar": "Gesundheit, Schönheit und Wohlbefinden",
  "Cuidados pessoais, academias, exames e soluções de bem-estar.":
      "Körperpflege, Fitnessstudios, Untersuchungen und Wellness-Lösungen.",
  "Viagens e Experiências": "Reisen und Erlebnisse",
  "Hospedagem, cultura, gastronomia, passeios e serviços relacionados.":
      "Unterkunft, Kultur, Gastronomie, Ausflüge und zugehörige Dienste.",
  "Tecnologia e Vida Prática": "Technologie und Alltag",
  "Notificações": "Benachrichtigungen",
  "Lançamentos recorrentes": "Wiederkehrende Einträge",
  "Relatório mensal disponível": "Monatsbericht verfügbar",
  "Dados econômicos e câmbio": "Wirtschaftsdaten und Wechselkurse",
  "Transparência e metodologia": "Transparenz und Methodik",
  "Sobre o aplicativo": "Über die App",
  "Estados Unidos": "Vereinigte Staaten",
  "Alemanha": "Deutschland",
  "França": "Frankreich",
  "Índia": "Indien",
  "No horário": "Zum Termin",
  "1 dia antes e no horário": "1 Tag vorher und zum Termin",
  "3 dias antes, 1 dia antes e no horário":
      "3 Tage vorher, 1 Tag vorher und zum Termin",
  "Termos de Uso": "Nutzungsbedingungen",
  "Política de Privacidade": "Datenschutzrichtlinie",
  "Consentimento e tratamento de dados financeiros":
      "Einwilligung und Verarbeitung von Finanzdaten",
  "Política de Anúncios": "Werberichtlinie",
  "Política de Parcerias e Benefícios":
      "Richtlinie für Partnerschaften und Vorteile",
  "Privacidade Internacional": "Internationaler Datenschutz",
  "Exclusão de dados": "Datenlöschung",
  "Aviso financeiro": "Finanzhinweis",
  "Metodologia do Oscar Score": "Methodik des Oscar Score",
  "Licenças e bibliotecas": "Lizenzen und Bibliotheken",
  "O Oscar Finanças organiza informações fornecidas pelo usuário. Os cálculos e projeções são educacionais, podem conter limitações e não constituem consultoria financeira. O usuário é responsável pela exatidão dos dados cadastrados e pelo uso dos relatórios.": "Oscar Finanças ordnet die vom Nutzer bereitgestellten Angaben. Berechnungen und Prognosen dienen der Bildung, können Einschränkungen enthalten und sind keine Finanzberatung. Der Nutzer ist für die Richtigkeit der Daten und die Nutzung der Berichte verantwortlich.",
  "Dados financeiros permanecem no aparelho nesta versão. Serviços públicos de câmbio e indicadores não recebem valores da carteira. Recursos externos devem declarar finalidade, retenção e fundamento legal antes da publicação.": "Finanzdaten bleiben in dieser Version auf dem Gerät. Öffentliche Kurs- und Indikatordienste erhalten keine Portfoliowerte. Externe Dienste müssen vor Veröffentlichung Zweck, Speicherung und Rechtsgrundlage offenlegen.",
  "O aplicativo aplica minimização, finalidade e controle do usuário. LGPD, GDPR e normas regionais serão observadas de acordo com o país de disponibilização.": "Die App setzt Datenminimierung, Zweckbindung und Nutzerkontrolle um. LGPD, DSGVO und regionale Vorschriften werden je nach Veröffentlichungsland beachtet.",
  "Espaços publicitários futuros usarão um módulo isolado. Personalização dependerá de consentimento aplicável e nenhum anúncio receberá receitas, despesas, agenda, relatório ou carteira.": "Künftige Werbeflächen verwenden ein isoliertes Modul. Personalisierung erfordert die geltende Einwilligung; Anzeigen erhalten niemals Einnahmen, Ausgaben, Kalender-, Berichts- oder Portfoliodaten.",
  "O Oscar Finanças poderá receber comissão por links identificados. A transparência aparece antes da saída; critérios comerciais não alteram Oscar Score, relatórios ou cálculos.": "Oscar Finanças kann für gekennzeichnete Links eine Provision erhalten. Der Hinweis erscheint vor dem Verlassen der App; kommerzielle Kriterien verändern weder Oscar Score noch Berichte oder Berechnungen.",
  "Idioma, região e moeda são independentes. Transferências internacionais, quando existirem, deverão informar destino, proteção e direitos aplicáveis.": "Sprache, Region und Währung sind unabhängig. Künftige internationale Übertragungen müssen Ziel, Schutz und anwendbare Rechte nennen.",
  "A exclusão local exige confirmação forte e não deve ocorrer parcialmente. Exclusão de conta só será exibida quando contas e sincronização reais estiverem implementadas.": "Lokales Löschen erfordert eine eindeutige Bestätigung und darf nicht teilweise erfolgen. Kontolöschung erscheint erst, wenn echte Konten und Synchronisierung umgesetzt sind.",
  "O aplicativo não executa investimentos, não oferece custódia e não recomenda compra ou venda. Câmbio, inflação e rentabilidade podem variar; desempenho passado não garante resultado futuro.": "Die App führt keine Anlagen aus, bietet keine Verwahrung und empfiehlt weder Kauf noch Verkauf. Kurse, Inflation und Renditen können schwanken; frühere Ergebnisse garantieren keine künftigen.",
  "O Oscar Score resume a sobra mensal em relação à renda bruta. Ele considera entradas confirmadas, despesas e déficit. Não é score de crédito e não determina acesso a produtos.": "Der Oscar Score fasst den monatlichen Überschuss im Verhältnis zum Bruttoeinkommen zusammen. Er berücksichtigt bestätigte Einnahmen, Ausgaben und Defizite. Er ist kein Kreditscore und entscheidet nicht über Produktzugang.",
  "O crescimento real estimado subtrai do rendimento nominal um efeito inflacionário baseado em índice oficial médio. Esse índice não representa a inflação pessoal de cada usuário.": "Das geschätzte reale Wachstum zieht vom nominalen Ertrag einen Inflationseffekt auf Basis eines amtlichen Durchschnittsindex ab. Dieser bildet die persönliche Inflation nicht ab.",
  "Construído com Flutter e bibliotecas revisadas para gráficos, banco local, PDF, impressão e notificações. A relação final de licenças será gerada para a versão publicada.": "Erstellt mit Flutter und geprüften Bibliotheken für Diagramme, lokalen Speicher, PDF, Druck und Benachrichtigungen. Die endgültige Lizenzliste wird für die veröffentlichte Version erzeugt.",
  "Ativos relacionados": "Zugehörige Anlagen",
  "Deslize para ver mais": "Wischen für weitere",
  "Dados simulados": "Simulierte Daten",
  "Aguardando cotação": "Kurs wird erwartet",
  "Cotação atualizada": "Kurs aktualisiert",
  "Última cotação salva": "Zuletzt gespeicherter Kurs",
  "Privacidade dos valores": "Werteschutz",
  "Lembretes da Agenda": "Kalendererinnerungen",
  "Fechamento mensal": "Monatsabschluss",
  "Plano e assinatura": "Tarif und Abonnement",
  "Domingo": "Sonntag",
  "Segunda-feira": "Montag",
  "Escolher": "Wählen",
  "por mês": "pro Monat",
  "mês": "Monat",
  "por ano": "pro Jahr",
  "equivalente a": "entspricht",
  "economize": "sparen",
  "Serviços do mês": "Dienstleistungen dieses Monats",
  "Vendas do mês": "Verkäufe dieses Monats",
  "Adicionar serviço": "Dienstleistung hinzufügen",
  "Adicionar venda": "Verkauf hinzufügen",
  "Somado à Tela 1": "In Ansicht 1 enthalten",
  "Nenhuma entrada neste mês.": "Keine Einnahmen in diesem Monat.",
  "Sem movimentações para exibir": "Keine Aktivitäten anzuzeigen",
  "Nenhum gasto neste mês.": "Keine Ausgaben in diesem Monat.",
  "Nenhuma parcela neste mês.": "Keine Raten in diesem Monat.",
  "Adicionar entrada": "Einnahme hinzufügen",
  "Adicionar gasto": "Ausgabe hinzufügen",
  "Adicionar parcela": "Rate hinzufügen",
  "Sobra": "Überschuss",
  "Déficit": "Defizit",
  "Não calculado": "Nicht berechnet",
  "Não avaliado": "Nicht bewertet",
  "Não avaliada": "Nicht bewertet",
  "Cadastre uma entrada para calcular seu Oscar Score.":
      "Erfassen Sie Einnahmen, um Ihren Oscar Score zu berechnen.",
  "Cadastre gastos para calcular a cobertura":
      "Erfassen Sie Ausgaben, um die Deckung zu berechnen",
  "Valor do desconto": "Rabattbetrag",
  "Títulos públicos": "Staatsanleihen",
  "Renda fixa bancária": "Bank-Festgeld",
  "Títulos empresariais": "Unternehmensanleihen",
  "Ações": "Aktien",
  "Cadastro manual": "Manueller Eintrag",
  "Cotações indisponíveis": "Kurse nicht verfügbar",
  "Cotações atualizadas com sucesso.": "Kurse erfolgreich aktualisiert.",
  "Não foi possível atualizar as cotações.":
      "Kurse konnten nicht aktualisiert werden.",
  "Sem conexão. O último valor disponível foi mantido.":
      "Offline. Der letzte verfügbare Wert wurde beibehalten.",
  "Cotações demonstrativas desatualizadas · dados reais serão atualizados por adaptador seguro":
      "Veraltete Demokurse · Marktdaten werden sicher aktualisiert",
  "Cotações atualizadas · fonte de mercado": "Kurse aktualisiert · Marktquelle",
  "Aviso educacional financeiro": "Finanzieller Bildungshinweis",
  "Como funciona o Oscar Score": "So funktioniert der Oscar Score",
  "Dispositivos, software, conectividade, casa, estudo e trabalho.":
      "Geräte, Software, Konnektivität, Zuhause, Studium und Arbeit.",
  "DOM": "SO",
  "SEG": "MO",
  "TER": "DI",
  "QUA": "MI",
  "QUI": "DO",
  "SEX": "FR",
  "SÁB": "SA",
  "Aplicado: {value}": "Angelegt: {value}",
  "Rendimento: {value}": "Ertrag: {value}",
  "Rendeu no mês: {value}": "Monatlicher Ertrag: {value}",
  "Efeito estimado da inflação: {value}":
      "Geschätzter Inflationseffekt: {value}",
  "Crescimento real estimado: {value}": "Geschätztes reales Wachstum: {value}",
  "Patrimônio estimado: {value}": "Geschätztes Vermögen: {value}",
  "Valor inicial ({currency})": "Anfangsbetrag ({currency})",
  "Saldo atual: {value}": "Aktueller Saldo: {value}",
  "{value} guardados": "{value} gespart",
  "Cobre aproximadamente {value} meses": "Deckt ungefähr {value} Monate",
  "Meta: {months} meses · {percent}%": "Ziel: {months} Monate · {percent}%",
  "Meta: {months} meses": "Ziel: {months} Monate",
  "meses de cobertura": "Monate abgedeckt",
  "da meta": "des Ziels",
  "Ajustar meta": "Ziel anpassen",
  "O aporte deve ser maior que zero.": "Der Beitrag muss größer als null sein.",
  "Fluxo do mês: {value}/100": "Monatlicher Verlauf: {value}/100",
  "Reserva: {value} meses": "Notfallreserve: {value} Monate",
  "Reserva de Emergência: {value} meses": "Notfallreserve: {value} Monate",
  "{name} · {amount} será removido deste mês.":
      "{name} · {amount} wird aus diesem Monat entfernt.",
  "{name} será removido de {month}.": "{name} wird aus {month} entfernt.",
  "Cadastrar “{name}” manualmente": "„{name}“ manuell hinzufügen",
  "Serviços · {value}%": "Dienstleistungen · {value}%",
  "Vendas · {value}%": "Verkäufe · {value}%",
  "Horário · {time}": "Uhrzeit · {time}",
  "Escolher {plan}": "{plan} wählen",
  "Este período está disponível no Plano {plan}.":
      "Dieser Zeitraum ist im Tarif {plan} verfügbar.",
  "Relatório · {count} folha": "Bericht · {count} Seite",
  "Relatório · {count} folhas": "Bericht · {count} Seiten",
  "Competência {month} · Página {page} de {total}":
      "Zeitraum {month} · Seite {page} von {total}",
  "Criptomoedas": "Kryptowährungen",
  "Quantidade": "Menge",
  "Informe uma quantidade válida.": "Geben Sie eine gültige Menge ein.",
  "Histórico em formação": "Verlauf wird aufgebaut",
  "Variação em 24 horas": "Veränderung in 24 Stunden",
  "O convite de amigos está indisponível nesta versão.":
      "Freundeseinladungen sind in dieser Version nicht verfügbar.",
  "Receba 30% de desconto quando um amigo indicado se cadastrar e contratar um plano anual. Assinaturas mensais não participam. Descontos não se acumulam: vale o maior desconto elegível.": "Erhalten Sie 30 % Rabatt, wenn ein geworbener Freund sich registriert und einen Jahrestarif abschließt. Monatsabonnements zählen nicht. Rabatte sind nicht kombinierbar; es gilt der höchste berechtigte Rabatt.",
  "Carteira de criptomoedas com cotações CoinMarketCap":
      "Kryptoportfolio mit CoinMarketCap-Kursen",
  "entry.welcome": "Ihre Finanzen mit Klarheit, Privatsphäre und Ziel.",
  "entry.google": "Mit Google anmelden",
  "entry.apple": "Mit Apple anmelden",
  "entry.guest": "Ohne Konto fortfahren",
  "entry.disclaimer": "Ihre Finanzdaten bleiben auf diesem Gerät.",
  "drawer.close": "Menü schließen",
  "privacy.hide": "Werte ausblenden",
  "privacy.show": "Werte anzeigen",
  "month.previous": "Vorheriger Monat",
  "month.next": "Nächster Monat",
  "screen.financial": "Finanzübersicht",
  "screen.extraIncome": "Zusatzeinkommen",
  "screen.investments": "Investitionen",
  "screen.objectives": "Ziele",
  "screen.reports": "Gesamtbericht",
  "screen.agenda": "Kalender",
  "screen.calculator": "Rechner",
  "screen.plans": "Tarife",
  "screen.club": "Oscar Club",
  "screen.settings": "Einstellungen",
  "objectives.subtitle": "Verfolge den Fortschritt deiner Ziele",
  "Objetivos financeiros com evolução mês a mês":
      "Finanzielle Ziele mit monatlichem Fortschritt",
  "objectives.new": "Neues Ziel",
  "objectives.emptyTitle": "Hier beginnen deine Ziele",
  "objectives.emptyBody": "Erstelle ein Ziel, um Einzahlungen und Fortschritt im Zeitverlauf zu verfolgen.",
  "objectives.loadFailed": "Deine Ziele konnten nicht geladen werden.",
  "objectives.retry": "Erneut versuchen",
  "objectives.name": "Name des Ziels",
  "objectives.nameRequired": "Gib einen Namen für das Ziel ein.",
  "objectives.targetPeriod": "Zeitraum des Ziels",
  "objectives.threeMonths": "3 Monate",
  "objectives.sixMonths": "6 Monate",
  "objectives.oneYear": "1 Jahr",
  "objectives.fiveYears": "5 Jahre",
  "objectives.tenYears": "10 Jahre",
  "objectives.monthCount": "{count} Monate",
  "objectives.targetAmount": "Zielbetrag",
  "objectives.targetRequired": "Gib einen Betrag größer als null ein.",
  "objectives.initialBalance": "Bereits angespartes Guthaben",
  "objectives.initialBalanceHelp":
      "Der bereits zurückgelegte Betrag vor neuen Einzahlungen.",
  "objectives.contribution": "Einzahlung",
  "objectives.addContribution": "Einzahlung hinzufügen",
  "objectives.contributionAmount": "Einzahlungsbetrag",
  "objectives.saveContribution": "Einzahlung speichern",
  "objectives.contributionSaved":
      "Einzahlung zum Ziel hinzugefügt und unter Ausgaben erfasst.",
  "objectives.exchangeUnavailable": "Wechselkurs nicht verfügbar; die Einzahlung konnte nicht umgerechnet werden.",
  "Saldo reservado": "Zurückgelegter Betrag",
  "Aportes acumulados": "Einzahlungen gesamt",
  "Meta": "Ziel",
  "Acompanhe sua meta na tela Objetivos":
      "Saldo, Einzahlungen und Fortschritt deiner Reserve ansehen",
  "Aporte · {name}": "Einzahlung · {name}",
  "objectives.annualRate": "Jahreszinssatz",
  "objectives.compoundInterest": "Jährlicher Zinseszins",
  "objectives.annualRateShort": "Jahreszins",
  "objectives.lowerRate": "Zinssatz senken",
  "objectives.raiseRate": "Zinssatz erhöhen",
  "objectives.annualRateHelp":
      "Gib den Satz für deine Projektion ein oder lass 0 % stehen.",
  "objectives.rateTooHigh": "Gib einen Jahreszins zwischen 0 % und 100 % ein.",
  "objectives.frequency": "Häufigkeit der Einzahlung",
  "objectives.oneTime": "Einmalig",
  "objectives.monthly": "Monatlich wiederkehrend",
  "objectives.projectionDisclosure": "Der Zinssatz ergibt eine Schätzung, keinen Live-Kurs. Diese Einzahlung erscheint auch bei Ausgaben als „Einzahlung · Ziel“.",
  "objectives.create": "Ziel erstellen",
  "objectives.cancel": "Abbrechen",
  "objectives.created": "Ziel erstellt.",
  "objectives.goalActions": "Zielaktionen",
  "objectives.delete": "Löschen",
  "objectives.deleteTitle": "Dieses Ziel löschen?",
  "objectives.deleteBody": "Das Ziel und sein Fortschritt werden von dieser Seite entfernt. Einträge zu Einzahlungen unter Ausgaben bleiben erhalten.",
  "objectives.currentBalance": "Voraussichtlicher Kontostand in diesem Monat",
  "objectives.contributions": "Einzahlungen gesamt",
  "objectives.estimatedYield": "Geschätzte Rendite",
  "objectives.returnLabel": "Rendite",
  "objectives.progressSemantics": "Zielfortschritt: {percent} %",
  "objectives.target": "Ziel: {months} · {amount}",
  "objectives.percentComplete": "{percent} % erreicht",
  "objectives.importedHistory": "Einzahlungshistorie aus den Ausgaben übernommen. Es wurde keine Rendite angenommen.",
  "objectives.viewEvolution": "Monatlicher Verlauf",
  "objectives.chartDescription": "Diagramm zur Entwicklung des Zielguthabens",
  "objectives.monthlyEvolution": "Monatliche Entwicklung",
  "objectives.estimatedYieldShort": "Rendite (gesch.)",
  "objectives.actualYieldShort": "Rendite",
  "objectives.closingBalance": "Endsaldo",
  "objectives.projectionFootnote": "Schätzung anhand des eingegebenen Jahreszinses ({rate} % p. a.). Kein Live-Kurs; prüfe den tatsächlichen Kontostand bei deinem Anbieter.",
  "foundation.ready": "Struktur für die nächste Etappe vorbereitet",
  "Brasil": "Brasilien",
  "Clareza que transforma escolhas em patrimônio":
      "Klarheit, die Entscheidungen in Vermögen verwandelt",
  "Fluxo do mês: Não calculado": "Monatlicher Verlauf: Nicht berechnet",
  "Reserva: Não avaliada": "Notfallreserve: Nicht bewertet",
  "Oscar Score: Não calculado": "Oscar Score: Nicht berechnet",
  "Reserva de Emergência: Não avaliada": "Notfallreserve: Nicht bewertet",
  "Indisponível": "Nicht verfügbar",
  "home.block.financial": "Finanzübersicht",
  "home.block.extraIncome": "Zusatzverdienst",
  "home.block.investments": "Investitionen",
  "home.block.emergencyFund": "Notfallreserve",
  "home.block.objectives": "Ziele",
  "Acompanhe o progresso das suas metas":
      "Verfolgen Sie den Fortschritt Ihrer Ziele",
  "Saldo dos objetivos": "Zielguthaben",
  "Total acumulado": "Insgesamt eingezahlt",
  "Meta total": "Gesamtziel",
  "Últimas cotações salvas · atualização automática":
      "Zuletzt gespeicherte Kurse · automatische Aktualisierung",
  "Últimas cotações salvas · atualização automática indisponível": "Zuletzt gespeicherte Kurse · automatische Aktualisierung nicht verfügbar",
  "legal.privacy.body": "Oscar Finanças verwendet Ihre eingegebenen Beträge, Beschreibungen, Anlagen und Termine zur Organisation Ihrer Finanzen. In der installierten App bleiben diese Daten auf Ihrem Gerät; in der Webversion werden sie lokal in diesem Browser gespeichert und bleiben nach dem Neuladen verfügbar. Einstellungen werden ebenfalls lokal gespeichert.\n\nFür Marktkurse nutzen wir AwesomeAPI, HG Brasil, Alpha Vantage und CoinMarketCap. Anfragen enthalten Währungen und Anlagenkennungen, jedoch keine Mengen, Salden, Anlagebeträge, Beschreibungen oder Termine. Verbindungsdienste können IP-Adresse und technische Metadaten erhalten.\n\nBerichte werden nur auf Ihren Wunsch gedruckt oder an andere Apps und Empfänger weitergegeben. Wir verkaufen keine Finanzdaten. Diese Version synchronisiert keine Daten mit einem entfernten Konto und enthält keine Werbe- oder Verhaltensanalyse-SDKs.\n\nSie können Einträge bearbeiten und entfernen. Entfernen lässt sich rückgängig machen; lokal als gelöscht markierte Einträge können erhalten bleiben. Webdaten bleiben in diesem Browser, bis Sie sie in der App entfernen oder die Websitedaten in den Browsereinstellungen löschen. Löschen Sie in der installierten App die App-Daten in den Systemeinstellungen, um die lokale Datenbank zu entfernen. Exportierte Dateien und externe Kopien müssen separat gelöscht werden.",
  "legal.ads.body": "Diese Version zeigt keine Werbung und enthält kein AdMob-SDK. Finanzdaten werden nicht für gezielte Werbung verwendet. Vor einer Aktivierung von Werbung werden diese Richtlinie und die Datenschutzeinstellungen aktualisiert. Soweit erforderlich, können Sie Ihre Einwilligung vor Werbeanfragen in den Datenschutzoptionen erteilen und ändern.",
  "legal.permissions.body": "Erinnerungen verwenden lokale Benachrichtigungen mit der erforderlichen Systemberechtigung. Sie können diese in den Geräteeinstellungen widerrufen. Zur Finanzverwaltung benötigt die App weder Kontakte noch präzisen Standort, Kamera oder Mikrofon. Verweigerte Berechtigungen können Erinnerungen verhindern, jedoch keine Finanzeinträge.",
  "Permissões e notificações": "Berechtigungen und Benachrichtigungen",
  "legal.terms.body": "Oscar Finanças organisiert Finanzen und erstellt Bildungsberechnungen aus Ihren Eingaben. Die App überweist kein Geld, führt keine Handelsaufträge aus, verwahrt keine Kryptowährungen und bietet keine individuelle Anlageberatung. Kurse können verzögert oder nicht verfügbar sein. Marktwerte sind keine realisierten Erträge.\n\nSie sind für die Prüfung Ihrer Einträge und den Schutz von Gerät und exportierten Berichten verantwortlich. Prognosen garantieren keine Ergebnisse. Die Inflationsschätzung dieser Version nutzt einen lokalen Referenzsatz und bildet nicht Ihre persönliche Inflation ab. Abonnementkäufe und Freundeseinladungen sind in dieser Version nicht verfügbar; Tarifschaltflächen lösen keine Zahlung aus.",
  "report.documentSummary.one": "{months} Monat · {pages} PDF-Seiten",
  "report.documentSummary.many": "{months} Monate · {pages} PDF-Seiten",
  "report.monthLabel": "Monat",
  "report.pdfPagesLabel": "PDF-Seiten",
  "report.summary": "Monatsübersicht",
  "report.incomeSection": "Einnahmen",
  "report.assets": "Anlagen",
  "report.cryptoassets": "Kryptoanlagen",
  "report.objectives": "Ziele",
  "report.ofTarget": "des Ziels",
  "report.quantity": "Menge",
  "report.monthlyReturn": "Monatliche Rendite",
  "report.target": "Zielbetrag",
  "report.monthlyYield": "Ertrag im Monat",
  "report.estimated": "geschätzt",
  "report.confirmed": "erfasst",
  "report.footerNote": "Für den Monat erfasste Werte",
  "report.demoFirst100k": "Meine ersten 100.000",
  "report.tagline": "Klarheit, die Entscheidungen in Vermögen verwandelt",
  "report.report": "Finanzbericht",
  "Relatório financeiro": "Finanzbericht",
  "report.personal": "Persönliches Dokument",
  "Documento pessoal": "Persönliches Dokument",
  "report.currency": "Basiswährung",
  "moeda base": "Basiswährung",
  "report.generated": "erstellt am",
  "gerado em": "erstellt am",
  "report.noMovement": "Keine Bewegung",
  "report.mainIncome": "Haupteinkommen",
  "Renda principal": "Haupteinkommen",
  "report.extra": "Bestätigte Zusatzeinkünfte",
  "Ganho Extra confirmado": "Bestätigte Zusatzeinkünfte",
  "report.total": "Gesamteinnahmen",
  "Entradas totais": "Gesamteinnahmen",
  "report.expenses": "Ausgaben",
  "Despesas": "Ausgaben",
  "report.installments": "Raten",
  "Parcelas": "Raten",
  "report.balance": "Verfügbarer Überschuss",
  "Sobra disponível": "Verfügbarer Überschuss",
  "report.deficit": "Defizit",
  "report.health": "Finanzielle Gesundheit",
  "Saúde financeira": "Finanzielle Gesundheit",
  "report.notCalculated": "Nicht berechnet",
  "report.fund": "Notgroschen",
  "report.notEvaluated": "Nicht bewertet",
  "report.months": "Monate",
  "meses": "Monate",
  "report.mainExpenses": "Erfasste Ausgaben",
  "Principais gastos": "Wichtigste Ausgaben",
  "report.noExpenses": "Keine Ausgaben erfasst.",
  "Nenhum gasto cadastrado.": "Keine Ausgaben erfasst.",
  "report.extraDetails": "Details zu Zusatzeinkünften",
  "report.noExtraIncome": "Keine Zusatzeinkünfte erfasst.",
  "report.printUnavailable": "Der Druckdialog ließ sich nicht öffnen. Laden Sie das PDF über Teilen herunter.",
  "report.printFallback": "Der Druckdialog wurde nicht geöffnet. Das PDF wurde zum Drucken heruntergeladen.",
  "report.investments": "Anlagen und reales Wachstum",
  "Investimentos e crescimento real": "Anlagen und reales Wachstum",
  "report.page": "Seite",
  "Página": "Seite",
  "report.of": "von",
  "de": "von",
  "report.critical": "Kritischer Alarm",
  "Alerta Crítico": "Kritischer Alarm",
  "report.attention": "Achtung / Knapp",
  "Atenção / Apertado": "Achtung / Knapp",
  "report.balanced": "Ausgeglichen",
  "Equilibrado": "Ausgeglichen",
  "report.healthy": "Gesund",
  "Saudável": "Gesund",
  "report.prosperous": "Wohlhabend",
  "Próspero": "Wohlhabend",
  "Parcela {current} de {total}": "Rate {current} von {total}",
  "Atenção": "Achtung",
  "Alerta crítico": "Kritische Warnung",
  "{date}, {count} compromissos": "{date}, {count} Termine",
  "Oscar Score, {score} de 100, {level}":
      "Oscar Score, {score} von 100, {level}",
  "Oscar Score não calculado. Cadastre uma entrada.":
      "Oscar Score nicht berechnet. Fügen Sie eine Einnahme hinzu.",
  "Painel financeiro, valores ocultos": "Finanzübersicht, Beträge ausgeblendet",
  "Painel Financeiro": "Finanzübersicht",
  "O mês pede proteção. Reveja os maiores compromissos.": "Diesen Monat ist Vorsicht geboten. Prüfen Sie Ihre größten Verpflichtungen.",
  "Há pouco espaço de manobra. Pequenos ajustes podem abrir fôlego.":
      "Der Spielraum ist knapp. Kleine Anpassungen können Entlastung bringen.",
  "Sua estrutura está equilibrada. Preserve a constância.":
      "Ihre Finanzen sind ausgeglichen. Bleiben Sie konsequent.",
  "Boa margem financeira. Continue fortalecendo sua reserva.": "Sie haben einen guten finanziellen Spielraum. Stärken Sie weiter Ihre Rücklage.",
  "Excelente capacidade de sobra. Direcione esse resultado com propósito.":
      "Sie erzielen einen sehr guten Überschuss. Setzen Sie ihn gezielt ein.",
  "Criptoativos": "Kryptoanlagen",
  "Carteira de criptoativos": "Kryptoanlagen-Portfolio",
  "Sem anúncios": "Werbefrei",
  "Criptoativos relacionados": "Verwandte Kryptoanlagen",
  "Carteira": "Portfolio",
  "comprometido": "gebunden",
  "Disponível no Plano {plan}.": "Im {plan}-Tarif verfügbar.",
  "Histórico indisponível": "Verlauf nicht verfügbar",
  "Início": "Startseite",
  "Resumo de {month}": "Zusammenfassung für {month}",
  "Painel financeiro": "Finanzübersicht",
  "Sua vida financeira em um só lugar": "Ihre Finanzen an einem Ort",
  "Saldo do mês": "Monatssaldo",
  "Ganhos extras": "Zusätzliche Einnahmen",
  "Renda além do seu salário": "Einnahmen zusätzlich zum Gehalt",
  "Total no mês": "Gesamt im Monat",
  "Investimentos": "Anlagen",
  "Seu patrimônio trabalhando por você": "Ihr Vermögen arbeitet für Sie",
  "Total investido": "Anlagewert",
  "Ativos": "Anlagen",
  "Variação indisponível": "Änderung nicht verfügbar",
  "investment.period.month": "Monat",
  "24h": "24 Std.",
  "{count} ativo": "{count} Anlage",
  "{count} ativos": "{count} Anlagen",
  "{count} criptoativo": "{count} Kryptoanlage",
  "{count} criptoativos": "{count} Kryptoanlagen",
  "{count} ativos na carteira": "{count} Positionen im Portfolio",
  "Carregando resumo…": "Zusammenfassung wird geladen…",
  "Resumo indisponível": "Zusammenfassung nicht verfügbar",
  "screen.account": "Mein Konto",
  "Dados do perfil": "Profildaten",
  "Data de nascimento": "Geburtsdatum",
  "Receber comunicações do Oscar Hive": "Mitteilungen von Oscar Hive erhalten",
  "Opcional e independente da publicidade.":
      "Optional und unabhängig von Werbung.",
  "Essa preferência fica salva neste aparelho.":
      "Diese Einstellung wird auf diesem Gerät gespeichert.",
  "Perfil salvo neste dispositivo.": "Profil auf diesem Gerät gespeichert.",
  "Não foi possível salvar o perfil.":
      "Das Profil konnte nicht gespeichert werden.",
  "O acesso com Google ainda não está disponível nesta versão.":
      "Die Google-Anmeldung ist in dieser Version noch nicht verfügbar.",
  "Apple estará disponível em uma versão futura.":
      "Apple-Anmeldung wird in einer zukünftigen Version verfügbar sein.",
  "Cópia de segurança e recuperação": "Sicherung und Wiederherstellung",
  "Seus dados ficam neste aparelho. A sincronização e a recuperação na nuvem ainda não estão disponíveis.": "Ihre Daten bleiben auf diesem Gerät. Cloud-Synchronisierung und Wiederherstellung sind noch nicht verfügbar.",
  "legal.account.profile.body": "Name, Geburtsdatum und Kommunikationseinstellung sind optional und werden nur auf diesem Gerät gespeichert. Diese Daten werden nicht an ein entferntes Konto gesendet. In dieser Version werden keine Mitteilungen versendet.",
};
