// Reviewed product copy for this language only. No cross-language fallback.
const enUsMessages = <String, String>{
  "Entradas": "Income",
  "Gastos": "Expenses",
  "Parcelas Longas": "Long-term installments",
  "Participação das despesas": "Expense share",
  "Nova entrada": "New income",
  "Novo gasto": "New expense",
  "Editar entrada": "Edit income",
  "Editar gasto": "Edit expense",
  "Editar serviço": "Edit service",
  "Editar venda": "Edit sale",
  "Nova parcela": "New installment",
  "Editar parcela": "Edit installment",
  "Parcela atual": "Current installment",
  "Total de parcelas": "Total installments",
  "Informe uma parcela válida, como 5 de 36.":
      "Enter a valid installment, such as 5 of 36.",
  "Nome": "Name",
  "Valor": "Amount",
  "Desconto": "Discount",
  "Sem desconto": "No discount",
  "Valor fixo": "Fixed amount",
  "Percentual": "Percentage",
  "Recorrente": "Recurring",
  "Cancelar": "Cancel",
  "Salvar": "Save",
  "Editar": "Edit",
  "Excluir": "Delete",
  "Confirmar exclusão": "Confirm deletion",
  "Item removido.": "Item removed.",
  "Desfazer": "Undo",
  "Reserva de Emergência": "Emergency Fund",
  "Valor guardado": "Saved amount",
  "1 mês": "1 month",
  "3 meses": "3 months",
  "6 meses": "6 months",
  "Atualizar valor": "Update amount",
  "Aporte entra nos gastos; zero salva só a meta.":
      "The contribution is recorded as an expense; zero saves only the goal.",
  "Investimentos: Não avaliado": "Investments: Not evaluated",
  "Não foi possível carregar seus dados.": "Your data could not be loaded.",
  "Tentar novamente": "Try again",
  "Total realizado no mês": "Total earned this month",
  "Nenhum lançamento nesta categoria.": "No entries in this category.",
  "Ganho recorrente": "Recurring income",
  "Somar à renda extra da Tela 1": "Add to extra income on Screen 1",
  "Ganho removido.": "Income removed.",
  "Sem ganhos": "No income",
  "Serviços": "Services",
  "Vendas": "Sales",
  "Pesquisar ou adicionar investimento": "Search or add investment",
  "Limpar pesquisa": "Clear search",
  "Alocação de ativos": "Asset allocation",
  "Símbolo ou código": "Symbol or code",
  "Família": "Family",
  "Moeda original": "Original currency",
  "Valor aplicado": "Amount invested",
  "Rendimento do mês": "Monthly return",
  "Confirmar posição": "Confirm position",
  "Excluir esta posição?": "Delete this position?",
  "Posição excluída.": "Position deleted.",
  "Nenhuma posição nesta área e mês.": "No positions in this area and month.",
  "Adicionar manualmente": "Add manually",
  "Renda Fixa": "Fixed Income",
  "Imobiliários": "Real estate",
  "Ações e ETFs": "Stocks and ETFs",
  "Simulador": "Simulator",
  "Calculadora de juros compostos": "Compound interest calculator",
  "Aporte mensal": "Monthly contribution",
  "Taxa (%)": "Rate (%)",
  "Mensal": "Monthly",
  "Anual": "Annual",
  "Prazo em meses": "Term in months",
  "Calcular cenário": "Calculate scenario",
  "Crescimento acima da inflação": "Growth above inflation",
  "Sua vida financeira": "Your financial life",
  "em relatórios claros": "in clear reports",
  "Relatório do mês atual": "Current month report",
  "Relatório dos últimos 3 meses": "Last 3 months report",
  "Relatório dos últimos 6 meses": "Last 6 months report",
  "Relatório anual": "Annual report",
  "Imprimir": "Print",
  "Compartilhar": "Share",
  "Antes de compartilhar": "Before sharing",
  "Continuar": "Continue",
  "Sem movimentação": "No activity",
  "Investimentos e crescimento real: Não avaliado":
      "Investments and real growth: Not evaluated",
  "Fechar": "Close",
  "Nenhum compromisso neste dia.": "No appointments on this day.",
  "Adicionar compromisso": "Add appointment",
  "Novo compromisso": "New appointment",
  "Título *": "Title *",
  "Observação opcional": "Optional note",
  "Recorrência": "Recurrence",
  "Lembretes locais": "Local reminders",
  "Informe o título do compromisso.": "Enter an appointment title.",
  "Compromisso excluído.": "Appointment deleted.",
  "Compromissos\npessoais": "Personal\nappointments",
  "Serviços\nagendados": "Scheduled\nservices",
  "Compromissos\nprofissionais": "Professional\nappointments",
  "Plano Básico": "Basic Plan",
  "Plano Plus": "Plus Plan",
  "Plano Pro": "Pro Plan",
  "Plano atual": "Current plan",
  "Convidar": "Invite",
  "Convide um Amigo": "Invite a Friend",
  "Escolha a clareza que acompanha seu momento":
      "Choose the clarity that fits your moment",
  "Oscar Clube": "Oscar Club",
  "Parceria remunerada": "Paid partnership",
  "Ver benefício": "View benefit",
  "Continuar para o parceiro": "Continue to partner",
  "Nenhum benefício válido disponível para sua região neste momento.":
      "No valid benefit is available for your region right now.",
  "Idioma, região e moeda": "Language, region and currency",
  "Idioma": "Language",
  "Moeda principal": "Primary currency",
  "Salvar alterações": "Save changes",
  "Configurações atualizadas": "Settings updated",
  "Aparência": "Appearance",
  "Automático": "Automatic",
  "Claro": "Light",
  "Escuro": "Dark",
  "Atualizar reserva de emergência": "Update emergency fund",
  "Reserva de emergência": "Emergency fund",
  "Cadastre despesas para visualizar a participação na renda.":
      "Add expenses to see their share of your income.",
  "Origem dos ganhos": "Income sources",
  "Nenhum resultado local. O cadastro manual continua disponível.":
      "No local results. Manual entry is still available.",
  "Ela sairá da carteira, mas poderá ser restaurada por alguns segundos.":
      "It will leave the portfolio, but can be restored for a few seconds.",
  "Evolução patrimonial": "Wealth evolution",
  "1 ano": "1 year",
  "Todo período": "All time",
  "Patrimônio registrado": "Recorded portfolio value",
  "Câmbio indisponível: não é possível somar investimentos em moedas diferentes.": "Exchange rates are unavailable; investments in different currencies cannot be combined.",
  "Valorização acumulada": "Accumulated gains",
  "Somente rendimentos registrados; não inclui variação de mercado.":
      "Recorded returns only; market price changes are excluded.",
  "Nenhum investimento registrado neste período.":
      "No investments recorded in this period.",
  "Ver valores mês a mês": "View monthly values",
  "Aplicado + rendimento confirmado": "Invested amount + confirmed return",
  "Aportes e rendimentos registrados": "Recorded contributions and returns",
  "Total registrado": "Recorded total",
  "Variação no período": "Change over period",
  "Não inclui oscilações de mercado nem representa rentabilidade.":
      "It excludes market price changes and is not investment return.",
  "Estimativa educacional. Não é promessa de rentabilidade nem recomendação.":
      "Educational estimate. It is neither a return guarantee nor advice.",
  "Estimativa baseada em uma cesta média; não representa sua inflação pessoal.": "Estimate based on an average basket; it does not represent your personal inflation.",
  "A alocação aparecerá quando você cadastrar uma posição.":
      "Allocation will appear after you add a holding.",
  "Não foi possível gerar o relatório. Tente novamente.":
      "The report could not be generated. Try again.",
  "Este documento contém informações financeiras pessoais. Compartilhe somente com pessoas de confiança.": "This document contains personal financial information. Share it only with people you trust.",
  "O aplicativo agenda notificações locais. A entrega depende das permissões, economia de bateria, modo silencioso e políticas do aparelho.": "The app schedules local notifications. Delivery depends on permissions, battery saving, silent mode and device policies.",
  "Todos os planos preservam seus dados e a navegação completa. Recursos avançados são explicados no ponto de uso.": "Every plan keeps your data and full navigation. Advanced features are explained where they are used.",
  "Toque em um plano para visualizar os recursos disponíveis.":
      "Tap a plan to view its available features.",
  "Uma indicação elegível pode oferecer até 40% de desconto. Benefícios não são cumulativos: prevalece sempre o maior desconto válido.": "An eligible referral may offer up to 40% off. Benefits cannot be combined: the highest valid discount always applies.",
  "O convite seguro será habilitado quando contas e validação do servidor estiverem disponíveis.": "Secure invitations will be enabled when accounts and server validation are available.",
  "Benefícios úteis e transparentes para apoiar sua educação, bem-estar e vida prática. Ofertas nunca alteram seu Oscar Score nem acessam seus dados financeiros.": "Useful, transparent benefits for education, well-being and everyday life. Offers never affect your Oscar Score or access financial data.",
  "O Oscar Finanças poderá receber uma comissão se você contratar ou comprar por este link. Você será direcionado ao ambiente do parceiro.": "Oscar Finanças may receive a commission if you buy through this link. You will be directed to the partner environment.",
  "O link deste parceiro ainda não está disponível.":
      "This partner link is not available yet.",
  "Região": "Region",
  "Primeiro dia da semana": "First day of the week",
  "Ocultar valores ao abrir": "Hide values on launch",
  "As Telas 1, 2 e 3 começam protegidas.":
      "Screens 1, 2 and 3 start protected.",
  "Ocultar valores ao sair": "Hide values when leaving",
  "Oculta os valores quando o aplicativo vai para segundo plano.":
      "Hides values when the app goes to the background.",
  "Vibração e resposta tátil": "Vibration and haptic feedback",
  "Lembrete padrão para novos eventos": "Default reminder for new events",
  "Cotações e indicadores": "Quotes and indicators",
  "O último snapshot válido é usado offline. Atualizações indisponíveis aparecem como desatualizadas.": "The latest valid snapshot is used offline. Unavailable updates appear as outdated.",
  "O Oscar Finanças não se conecta a contas bancárias nem movimenta dinheiro. Informações, simulações e projeções têm caráter informativo e usam dados fornecidos por você e referências de mercado atualizadas. Cotações podem apresentar atrasos ou diferenças em relação ao mercado.": "Oscar Finanças does not connect to bank accounts or move money. Information, simulations and projections are informational and use data you provide and up-to-date market references. Quotes may be delayed or differ from the market.",
  "Atualização oficial disponível após configurar os provedores.":
      "Official updates become available after providers are configured.",
  "Atualizar agora": "Update now",
  "Disponível em {tempo}": "Available in {tempo}",
  "Oscar Finanças — Clareza que transforma escolhas em patrimônio.":
      "Oscar Finanças — Clarity that turns choices into wealth.",
  "Organiza receitas, despesas, ganhos extras, saúde financeira, relatórios, agenda e investimentos sem movimentar seu dinheiro nem oferecer recomendação individual.": "Organizes income, expenses, extra earnings, financial health, reports, calendar and investments without moving your money or giving individual advice.",
  "Saldo atual": "Current balance",
  "Aporte deste mês": "This month contribution",
  "O aporte será incluído na lista de gastos do mês.":
      "The contribution will be included in this month’s expense list.",
  "Tipo de aporte": "Contribution type",
  "Aporte único": "One-time contribution",
  "Mensal fixo": "Fixed monthly",
  "Variável ou intermitente": "Variable or intermittent",
  "Meta de cobertura": "Coverage target",
  "Salário simulado": "Sample salary",
  "Aluguel simulado": "Sample rent",
  "Luz simulada": "Sample electricity",
  "Água simulada": "Sample water",
  "Internet simulada": "Sample internet",
  "Mercado simulado": "Sample groceries",
  "Reserva de emergência simulada": "Sample emergency fund",
  "Faculdade simulada": "Sample tuition",
  "Carro simulado": "Sample car",
  "TV simulada": "Sample TV",
  "Freelance de design simulado": "Sample design freelance",
  "Serviço freelance": "Freelance service",
  "Projeto ou atendimento do mês": "Project or service this month",
  "Projeto pontual simulado": "Sample one-off project",
  "Manutenção de computador simulada": "Sample computer maintenance",
  "Serviço técnico simulado": "Sample technical service",
  "Venda de bicicleta simulada": "Sample bicycle sale",
  "Venda ocasional simulada": "Sample occasional sale",
  "Venda ocasional": "Occasional sale",
  "Venda de item ou produto": "Sale of an item or product",
  "Venda de doces simulada": "Sample sweets sale",
  "Renda complementar simulada": "Sample additional income",
  "Tesouro Selic simulado": "Sample Treasury bond",
  "CDB simulado": "Sample bank fixed income",
  "Fundo imobiliário simulado": "Sample real estate fund",
  "Ação simulada": "Sample stock",
  "Versão 0.1.0 · compilação 1": "Version 0.1.0 · build 1",
  "Organização financeira essencial, sem custo.":
      "Essential financial organization, free of charge.",
  "Painel Financeiro completo, Reserva de Emergência e Oscar Score":
      "Full Financial Dashboard, Emergency Fund and Oscar Score",
  "Relatório mensal com impressão e compartilhamento":
      "Monthly report with printing and sharing",
  "Agenda completa com recorrência e lembretes locais":
      "Full calendar with recurrence and local reminders",
  "Oscar Clube e Configurações": "Oscar Club and Settings",
  "Grátis": "Free",
  "Mais controle para quem transforma trabalho em renda.":
      "More control for those who turn work into income.",
  "Tudo do Plano Básico": "Everything in the Basic Plan",
  "Ganho Extra completo: Serviços, Vendas e recorrências":
      "Full Extra Income: Services, Sales and recurrence",
  "Integração Agenda → Ganho Extra": "Calendar → Extra Income integration",
  "Relatórios do mês e dos últimos 3 meses":
      "Current-month and last-3-month reports",
  "Visão patrimonial completa, simples e internacional.":
      "A complete, simple and international wealth view.",
  "Tudo do Plano Plus": "Everything in the Plus Plan",
  "Investimentos, busca internacional, ações, ETFs e calculadora":
      "Investments, international search, stocks, ETFs and calculator",
  "Crescimento real e resumo em BRL, USD, EUR e INR":
      "Real growth and summary in BRL, USD, EUR and INR",
  "Relatórios de 1, 3, 6 e 12 meses": "Reports for 1, 3, 6 and 12 months",
  "Educação e Carreira": "Education and Career",
  "Cursos, idiomas, livros, certificações e ferramentas profissionais.":
      "Courses, languages, books, certifications and professional tools.",
  "Saúde, Beleza e Bem-estar": "Health, Beauty and Well-being",
  "Cuidados pessoais, academias, exames e soluções de bem-estar.":
      "Personal care, gyms, tests and well-being solutions.",
  "Viagens e Experiências": "Travel and Experiences",
  "Hospedagem, cultura, gastronomia, passeios e serviços relacionados.":
      "Accommodation, culture, food, tours and related services.",
  "Tecnologia e Vida Prática": "Technology and Everyday Life",
  "Notificações": "Notifications",
  "Lançamentos recorrentes": "Recurring entries",
  "Relatório mensal disponível": "Monthly report available",
  "Dados econômicos e câmbio": "Economic data and exchange rates",
  "Transparência e metodologia": "Transparency and methodology",
  "Sobre o aplicativo": "About the app",
  "Estados Unidos": "United States",
  "Alemanha": "Germany",
  "França": "France",
  "Índia": "India",
  "No horário": "At event time",
  "1 dia antes e no horário": "1 day before and at event time",
  "3 dias antes, 1 dia antes e no horário":
      "3 days before, 1 day before and at event time",
  "Termos de Uso": "Terms of Use",
  "Política de Privacidade": "Privacy Policy",
  "Consentimento e tratamento de dados financeiros":
      "Consent and financial data processing",
  "Política de Anúncios": "Advertising Policy",
  "Política de Parcerias e Benefícios": "Partnership and Benefits Policy",
  "Privacidade Internacional": "International Privacy",
  "Exclusão de dados": "Data deletion",
  "Aviso financeiro": "Financial notice",
  "Metodologia do Oscar Score": "Oscar Score methodology",
  "Licenças e bibliotecas": "Licenses and libraries",
  "O Oscar Finanças organiza informações fornecidas pelo usuário. Os cálculos e projeções são educacionais, podem conter limitações e não constituem consultoria financeira. O usuário é responsável pela exatidão dos dados cadastrados e pelo uso dos relatórios.": "Oscar Finanças organizes information supplied by the user. Calculations and projections are educational, may have limitations and are not financial advice. The user is responsible for entered data and use of reports.",
  "Dados financeiros permanecem no aparelho nesta versão. Serviços públicos de câmbio e indicadores não recebem valores da carteira. Recursos externos devem declarar finalidade, retenção e fundamento legal antes da publicação.": "Financial data stays on the device in this version. Public exchange-rate and indicator services never receive portfolio values. External services must disclose purpose, retention and legal basis before release.",
  "O aplicativo aplica minimização, finalidade e controle do usuário. LGPD, GDPR e normas regionais serão observadas de acordo com o país de disponibilização.": "The app applies data minimization, purpose limitation and user control. LGPD, GDPR and regional rules will be observed in each release country.",
  "Espaços publicitários futuros usarão um módulo isolado. Personalização dependerá de consentimento aplicável e nenhum anúncio receberá receitas, despesas, agenda, relatório ou carteira.": "Future advertising spaces will use an isolated module. Personalization will require applicable consent, and ads will never receive income, expenses, calendar, report or portfolio data.",
  "O Oscar Finanças poderá receber comissão por links identificados. A transparência aparece antes da saída; critérios comerciais não alteram Oscar Score, relatórios ou cálculos.": "Oscar Finanças may receive commission from identified links. Disclosure appears before leaving the app; commercial criteria never affect Oscar Score, reports or calculations.",
  "Idioma, região e moeda são independentes. Transferências internacionais, quando existirem, deverão informar destino, proteção e direitos aplicáveis.": "Language, region and currency are independent. Any future international transfer must disclose destination, protection and applicable rights.",
  "A exclusão local exige confirmação forte e não deve ocorrer parcialmente. Exclusão de conta só será exibida quando contas e sincronização reais estiverem implementadas.": "Local deletion requires strong confirmation and must not be partial. Account deletion will appear only after real accounts and synchronization are implemented.",
  "O aplicativo não executa investimentos, não oferece custódia e não recomenda compra ou venda. Câmbio, inflação e rentabilidade podem variar; desempenho passado não garante resultado futuro.": "The app does not execute investments, provide custody or recommend buying or selling. Exchange rates, inflation and returns may vary; past performance does not guarantee future results.",
  "O Oscar Score resume a sobra mensal em relação à renda bruta. Ele considera entradas confirmadas, despesas e déficit. Não é score de crédito e não determina acesso a produtos.": "Oscar Score summarizes the monthly balance relative to gross income. It considers confirmed income, expenses and deficit. It is not a credit score and does not determine access to products.",
  "O crescimento real estimado subtrai do rendimento nominal um efeito inflacionário baseado em índice oficial médio. Esse índice não representa a inflação pessoal de cada usuário.": "Estimated real growth subtracts an inflation effect based on an official average index from nominal returns. That index does not represent each user’s personal inflation.",
  "Construído com Flutter e bibliotecas revisadas para gráficos, banco local, PDF, impressão e notificações. A relação final de licenças será gerada para a versão publicada.": "Built with Flutter and reviewed libraries for charts, local storage, PDF, printing and notifications. The final license list will be generated for the published version.",
  "Ativos relacionados": "Related assets",
  "Deslize para ver mais": "Swipe to see more",
  "Dados simulados": "Simulated data",
  "Aguardando cotação": "Waiting for quote",
  "Cotação atualizada": "Quote updated",
  "Última cotação salva": "Last saved quote",
  "Privacidade dos valores": "Value privacy",
  "Lembretes da Agenda": "Calendar reminders",
  "Fechamento mensal": "Monthly closing",
  "Plano e assinatura": "Plan and subscription",
  "Domingo": "Sunday",
  "Segunda-feira": "Monday",
  "Escolher": "Choose",
  "por mês": "per month",
  "mês": "month",
  "por ano": "per year",
  "equivalente a": "equivalent to",
  "economize": "save",
  "Serviços do mês": "Services this month",
  "Vendas do mês": "Sales this month",
  "Adicionar serviço": "Add service",
  "Adicionar venda": "Add sale",
  "Somado à Tela 1": "Included on Screen 1",
  "Nenhuma entrada neste mês.": "No income this month.",
  "Sem movimentações para exibir": "No activity to display",
  "Nenhum gasto neste mês.": "No expenses this month.",
  "Nenhuma parcela neste mês.": "No installments this month.",
  "Adicionar entrada": "Add income",
  "Adicionar gasto": "Add expense",
  "Adicionar parcela": "Add installment",
  "Sobra": "Balance",
  "Déficit": "Deficit",
  "Não calculado": "Not calculated",
  "Não avaliado": "Not evaluated",
  "Não avaliada": "Not evaluated",
  "Cadastre uma entrada para calcular seu Oscar Score.":
      "Add an income to calculate your Oscar Score.",
  "Cadastre gastos para calcular a cobertura":
      "Add expenses to calculate coverage",
  "Valor do desconto": "Discount amount",
  "Títulos públicos": "Government bonds",
  "Renda fixa bancária": "Bank fixed income",
  "Títulos empresariais": "Corporate bonds",
  "Ações": "Stocks",
  "Cadastro manual": "Manual entry",
  "Cotações indisponíveis": "Quotes unavailable",
  "Cotações atualizadas com sucesso.": "Quotes updated successfully.",
  "Não foi possível atualizar as cotações.": "Quotes could not be updated.",
  "Sem conexão. O último valor disponível foi mantido.":
      "Offline. The latest available value was kept.",
  "Cotações demonstrativas desatualizadas · dados reais serão atualizados por adaptador seguro":
      "Outdated demonstration quotes · real data will be updated securely",
  "Cotações atualizadas · fonte de mercado": "Quotes updated · market source",
  "Aviso educacional financeiro": "Financial education notice",
  "Como funciona o Oscar Score": "How Oscar Score works",
  "Dispositivos, software, conectividade, casa, estudo e trabalho.":
      "Devices, software, connectivity, home, study and work.",
  "DOM": "SUN",
  "SEG": "MON",
  "TER": "TUE",
  "QUA": "WED",
  "QUI": "THU",
  "SEX": "FRI",
  "SÁB": "SAT",
  "Aplicado: {value}": "Invested: {value}",
  "Rendimento: {value}": "Return: {value}",
  "Rendeu no mês: {value}": "Monthly return: {value}",
  "Efeito estimado da inflação: {value}": "Estimated inflation effect: {value}",
  "Crescimento real estimado: {value}": "Estimated real growth: {value}",
  "Patrimônio estimado: {value}": "Estimated wealth: {value}",
  "Valor inicial ({currency})": "Initial amount ({currency})",
  "Saldo atual: {value}": "Current balance: {value}",
  "{value} guardados": "{value} saved",
  "Cobre aproximadamente {value} meses": "Covers approximately {value} months",
  "Meta: {months} meses · {percent}%": "Target: {months} months · {percent}%",
  "Meta: {months} meses": "Target: {months} months",
  "meses de cobertura": "months of coverage",
  "da meta": "of goal",
  "Ajustar meta": "Adjust goal",
  "O aporte deve ser maior que zero.":
      "Contribution must be greater than zero.",
  "Fluxo do mês: {value}/100": "Monthly flow: {value}/100",
  "Reserva: {value} meses": "Emergency fund: {value} months",
  "Reserva de Emergência: {value} meses": "Emergency fund: {value} months",
  "{name} · {amount} será removido deste mês.":
      "{name} · {amount} will be removed from this month.",
  "{name} será removido de {month}.": "{name} will be removed from {month}.",
  "Cadastrar “{name}” manualmente": "Add “{name}” manually",
  "Serviços · {value}%": "Services · {value}%",
  "Vendas · {value}%": "Sales · {value}%",
  "Horário · {time}": "Time · {time}",
  "Escolher {plan}": "Choose {plan}",
  "Este período está disponível no Plano {plan}.":
      "This period is available with the {plan} plan.",
  "Relatório · {count} folha": "Report · {count} page",
  "Relatório · {count} folhas": "Report · {count} pages",
  "Competência {month} · Página {page} de {total}":
      "Period {month} · Page {page} of {total}",
  "Criptomoedas": "Cryptocurrencies",
  "Quantidade": "Quantity",
  "Informe uma quantidade válida.": "Enter a valid quantity.",
  "Histórico em formação": "History is building",
  "Variação em 24 horas": "24-hour change",
  "O convite de amigos está indisponível nesta versão.":
      "Friend invitations are unavailable in this version.",
  "Receba 30% de desconto quando um amigo indicado se cadastrar e contratar um plano anual. Assinaturas mensais não participam. Descontos não se acumulam: vale o maior desconto elegível.": "Get 30% off when a referred friend signs up and purchases an annual plan. Monthly subscriptions do not qualify. Discounts cannot be combined: the highest eligible discount applies.",
  "Carteira de criptomoedas com cotações CoinMarketCap":
      "Crypto portfolio with CoinMarketCap quotes",
  "entry.welcome": "Your financial life with clarity, privacy, and purpose.",
  "entry.google": "Continue with Google",
  "entry.apple": "Continue with Apple",
  "entry.guest": "Continue without an account",
  "entry.disclaimer": "Your financial data stays on this device.",
  "drawer.close": "Close menu",
  "privacy.hide": "Hide values",
  "privacy.show": "Show values",
  "month.previous": "Previous month",
  "month.next": "Next month",
  "screen.financial": "Financial Dashboard",
  "screen.extraIncome": "Extra Income",
  "screen.investments": "Investments",
  "screen.objectives": "Goals",
  "screen.reports": "General Report",
  "screen.agenda": "Calendar",
  "screen.calculator": "Calculator",
  "screen.plans": "Plans",
  "screen.club": "Oscar Club",
  "screen.settings": "Settings",
  "objectives.subtitle": "Track the progress of your goals",
  "Objetivos financeiros com evolução mês a mês":
      "Financial goals with month-by-month progress",
  "objectives.new": "New Goal",
  "objectives.emptyTitle": "Your goals start here",
  "objectives.emptyBody":
      "Create a goal to follow contributions and progress over time.",
  "objectives.loadFailed": "Your goals could not be loaded.",
  "objectives.retry": "Try again",
  "objectives.name": "Goal name",
  "objectives.nameRequired": "Enter a name for this goal.",
  "objectives.targetPeriod": "Goal timeframe",
  "objectives.threeMonths": "3 months",
  "objectives.sixMonths": "6 months",
  "objectives.oneYear": "1 year",
  "objectives.fiveYears": "5 years",
  "objectives.tenYears": "10 years",
  "objectives.monthCount": "{count} months",
  "objectives.targetAmount": "Goal amount",
  "objectives.targetRequired": "Enter an amount greater than zero.",
  "objectives.initialBalance": "Amount already saved",
  "objectives.initialBalanceHelp":
      "The amount already set aside, before new contributions.",
  "objectives.contribution": "Contribution",
  "objectives.addContribution": "Add contribution",
  "objectives.contributionAmount": "Contribution amount",
  "objectives.saveContribution": "Save contribution",
  "objectives.contributionSaved":
      "Contribution added to the goal and recorded in Expenses.",
  "objectives.exchangeUnavailable":
      "Exchange rate unavailable; this contribution could not be converted.",
  "Saldo reservado": "Saved balance",
  "Aportes acumulados": "Total contributions",
  "Meta": "Target",
  "Acompanhe sua meta na tela Objetivos":
      "View your reserve balance, contributions, and progress",
  "Aporte · {name}": "Contribution · {name}",
  "objectives.annualRate": "Annual rate",
  "objectives.compoundInterest": "Compound interest per year",
  "objectives.annualRateShort": "Annual rate",
  "objectives.lowerRate": "Decrease rate",
  "objectives.raiseRate": "Increase rate",
  "objectives.annualRateHelp":
      "Use the rate for your projection, or leave it at 0%.",
  "objectives.rateTooHigh": "Enter a rate from 0% to 100% per year.",
  "objectives.frequency": "Contribution frequency",
  "objectives.oneTime": "One-time",
  "objectives.monthly": "Recurring monthly",
  "objectives.projectionDisclosure": "This rate produces an estimate, not a live quote. This month’s contribution also appears in Expenses as “Contribution · goal”.",
  "objectives.create": "Create goal",
  "objectives.cancel": "Cancel",
  "objectives.created": "Goal created.",
  "objectives.goalActions": "Goal actions",
  "objectives.delete": "Delete",
  "objectives.deleteTitle": "Delete this goal?",
  "objectives.deleteBody": "The goal and its progress will be removed from this screen. Contribution entries in Expenses will be kept.",
  "objectives.currentBalance": "Projected balance this month",
  "objectives.contributions": "Total contributions",
  "objectives.estimatedYield": "Estimated return",
  "objectives.returnLabel": "Return",
  "objectives.progressSemantics": "Goal progress: {percent}%",
  "objectives.target": "Target: {months} · {amount}",
  "objectives.percentComplete": "{percent}% reached",
  "objectives.importedHistory":
      "Contribution history imported from Expenses. No returns were assumed.",
  "objectives.viewEvolution": "Monthly progress",
  "objectives.chartDescription": "Chart of the goal balance over time",
  "objectives.monthlyEvolution": "Month-by-month progress",
  "objectives.estimatedYieldShort": "Est. return",
  "objectives.actualYieldShort": "Return",
  "objectives.closingBalance": "Closing balance",
  "objectives.projectionFootnote": "Estimate based on the entered annual rate ({rate}% p.a.). No live quote; check the actual balance with your investment provider.",
  "foundation.ready": "Structure ready for the next stage",
  "Brasil": "Brazil",
  "Clareza que transforma escolhas em patrimônio":
      "Clarity that turns choices into wealth",
  "Fluxo do mês: Não calculado": "Monthly flow: Not calculated",
  "Reserva: Não avaliada": "Emergency fund: Not evaluated",
  "Oscar Score: Não calculado": "Oscar Score: Not calculated",
  "Reserva de Emergência: Não avaliada": "Emergency fund: Not evaluated",
  "Indisponível": "Unavailable",
  "home.block.financial": "Financial Dashboard",
  "home.block.extraIncome": "Extra Income",
  "home.block.investments": "Investments",
  "home.block.emergencyFund": "Emergency Fund",
  "home.block.objectives": "Goals",
  "Acompanhe o progresso das suas metas": "Track your goals' progress",
  "Saldo dos objetivos": "Goals balance",
  "Total acumulado": "Total contributed",
  "Meta total": "Total target",
  "Últimas cotações salvas · atualização automática":
      "Last saved rates · automatic updates",
  "Últimas cotações salvas · atualização automática indisponível":
      "Last saved rates · automatic updates unavailable",
  "legal.privacy.body": "Oscar Finanças uses the amounts, descriptions, investments and appointments you enter to organize your finances. In the installed app, these records stay on your device; in the web version, they are stored locally in this browser and remain available after reload. Preferences are also saved locally.\n\nWe use AwesomeAPI, HG Brasil, Alpha Vantage and CoinMarketCap for market rates. Requests send currencies and asset identifiers, not quantities, balances, invested amounts, descriptions or appointments. Services involved in the connection may receive your IP address and technical metadata.\n\nReports are sent to other apps or recipients only when you choose to print or share. We do not sell your financial data. This version does not synchronize records with a remote account or include advertising or behavioral analytics SDKs.\n\nYou can edit and remove records. Item removal supports undo and may retain local records marked as deleted. Web data stays in this browser until you remove it in the app or clear this site’s data in your browser settings. In the installed app, clear the app’s data in your system settings to erase the local database. Exported files and external copies must be deleted separately.",
  "legal.ads.body": "This version does not show ads or include the AdMob SDK. Financial records are not used for ad targeting. If ads become available, this policy and privacy controls will be updated before activation. Where required, you will be able to choose and review consent in privacy options before ad requests.",
  "legal.permissions.body": "Reminders use local notifications, with system permission where required. You can revoke this permission in device settings. The app does not need your contacts, precise location, camera or microphone to organize finances. Denied permissions may prevent reminders but do not prevent financial entries.",
  "Permissões e notificações": "Permissions and notifications",
  "legal.terms.body": "Oscar Finanças organizes finances and provides educational calculations from your entries. It does not move money, execute trades, hold cryptocurrency or give individual investment advice. Quotes may be delayed or unavailable. Market values are not realized income.\n\nYou are responsible for checking your records and protecting access to your device and exported reports. Projections do not guarantee results. This version’s inflation estimate uses a local reference rate and does not represent your personal inflation. Subscription purchases and friend invitations are unavailable in this version; plan buttons do not charge you.",
  "report.tagline": "Clarity that turns choices into wealth",
  "report.report": "Financial report",
  "Relatório financeiro": "Financial report",
  "report.personal": "Personal document",
  "Documento pessoal": "Personal document",
  "report.currency": "base currency",
  "moeda base": "base currency",
  "report.generated": "generated on",
  "gerado em": "generated on",
  "report.noMovement": "No activity",
  "report.mainIncome": "Main income",
  "Renda principal": "Main income",
  "report.extra": "Confirmed extra income",
  "Ganho Extra confirmado": "Confirmed extra income",
  "report.total": "Total income",
  "Entradas totais": "Total income",
  "report.expenses": "Expenses",
  "Despesas": "Expenses",
  "report.installments": "Installments",
  "Parcelas": "Installments",
  "report.balance": "Available balance",
  "Sobra disponível": "Available balance",
  "report.deficit": "Deficit",
  "report.health": "Financial health",
  "Saúde financeira": "Financial health",
  "report.notCalculated": "Not calculated",
  "report.fund": "Emergency fund",
  "report.notEvaluated": "Not evaluated",
  "report.months": "months",
  "meses": "months",
  "report.mainExpenses": "Recorded expenses",
  "Principais gastos": "Main expenses",
  "report.noExpenses": "No expenses added.",
  "Nenhum gasto cadastrado.": "No expenses added.",
  "report.extraDetails": "Extra income details",
  "report.noExtraIncome": "No extra income recorded.",
  "report.printUnavailable":
      "Could not open printing. Use Share to download the PDF.",
  "report.printFallback": "The print dialog did not open; the PDF was downloaded so you can print it from your viewer.",
  "report.investments": "Investments and real growth",
  "Investimentos e crescimento real": "Investments and real growth",
  "report.page": "Page",
  "Página": "Page",
  "report.of": "of",
  "de": "of",
  "report.critical": "Critical alert",
  "Alerta Crítico": "Critical alert",
  "report.attention": "Attention / Tight",
  "Atenção / Apertado": "Attention / Tight",
  "report.balanced": "Balanced",
  "Equilibrado": "Balanced",
  "report.healthy": "Healthy",
  "Saudável": "Healthy",
  "report.prosperous": "Prosperous",
  "Próspero": "Prosperous",
  "Parcela {current} de {total}": "Installment {current} of {total}",
  "Atenção": "Attention",
  "Alerta crítico": "Critical alert",
  "{date}, {count} compromissos": "{date}, {count} appointments",
  "Oscar Score, {score} de 100, {level}":
      "Oscar Score, {score} out of 100, {level}",
  "Oscar Score não calculado. Cadastre uma entrada.":
      "Oscar Score not calculated. Add income.",
  "Painel financeiro, valores ocultos": "Financial dashboard, amounts hidden",
  "Painel Financeiro": "Financial Dashboard",
  "O mês pede proteção. Reveja os maiores compromissos.":
      "This month calls for caution. Review your largest commitments.",
  "Há pouco espaço de manobra. Pequenos ajustes podem abrir fôlego.": "There is little room to maneuver. Small adjustments can create breathing room.",
  "Sua estrutura está equilibrada. Preserve a constância.":
      "Your finances are balanced. Stay consistent.",
  "Boa margem financeira. Continue fortalecendo sua reserva.":
      "You have a healthy financial margin. Keep strengthening your reserve.",
  "Excelente capacidade de sobra. Direcione esse resultado com propósito.":
      "You have excellent surplus capacity. Put it to purposeful use.",
  "Criptoativos": "Crypto assets",
  "Carteira de criptoativos": "Crypto-asset portfolio",
  "Sem anúncios": "No ads",
  "Criptoativos relacionados": "Related crypto assets",
  "Carteira": "Portfolio",
  "comprometido": "committed",
  "Disponível no Plano {plan}.": "Available on the {plan} plan.",
  "Histórico indisponível": "History unavailable",
  "Início": "Home",
  "Resumo de {month}": "{month} Summary",
  "Painel financeiro": "Financial dashboard",
  "Sua vida financeira em um só lugar": "Your financial life in one place",
  "Saldo do mês": "Monthly balance",
  "Ganhos extras": "Extra income",
  "Renda além do seu salário": "Income beyond your salary",
  "Total no mês": "Total this month",
  "Investimentos": "Investments",
  "Seu patrimônio trabalhando por você": "Your wealth working for you",
  "Total investido": "Total invested",
  "Ativos": "Assets",
  "Variação indisponível": "Change unavailable",
  "investment.period.month": "month",
  "24h": "24h",
  "{count} ativo": "{count} asset",
  "{count} ativos": "{count} assets",
  "{count} criptoativo": "{count} crypto asset",
  "{count} criptoativos": "{count} crypto assets",
  "{count} ativos na carteira": "{count} assets in your portfolio",
  "Carregando resumo…": "Loading summary…",
  "Resumo indisponível": "Summary unavailable",
  "screen.account": "My Account",
  "Dados do perfil": "Profile details",
  "Data de nascimento": "Date of birth",
  "Receber comunicações do Oscar Hive": "Receive Oscar Hive updates",
  "Opcional e independente da publicidade.":
      "Optional and independent of advertising.",
  "Essa preferência fica salva neste aparelho.":
      "This preference is saved on this device.",
  "Perfil salvo neste dispositivo.": "Profile saved on this device.",
  "Não foi possível salvar o perfil.": "Could not save the profile.",
  "O acesso com Google ainda não está disponível nesta versão.":
      "Google sign-in is not available in this version yet.",
  "Apple estará disponível em uma versão futura.":
      "Apple sign-in will be available in a future version.",
  "Cópia de segurança e recuperação": "Backup and recovery",
  "Seus dados ficam neste aparelho. A sincronização e a recuperação na nuvem ainda não estão disponíveis.": "Your data stays on this device. Cloud sync and recovery are not available yet.",
  "legal.account.profile.body": "Your name, date of birth and communication preference are optional and saved only on this device. This information is not sent to a remote account. No communications are sent in this version.",
};
