// Reviewed product copy for this language only. No cross-language fallback.
const frFrMessages = <String, String>{
  "Entradas": "Revenus",
  "Gastos": "Dépenses",
  "Parcelas Longas": "Mensualités longues",
  "Participação das despesas": "Répartition des dépenses",
  "Nova entrada": "Nouveau revenu",
  "Novo gasto": "Nouvelle dépense",
  "Editar entrada": "Modifier le revenu",
  "Editar gasto": "Modifier la dépense",
  "Editar serviço": "Modifier le service",
  "Editar venda": "Modifier la vente",
  "Novo serviço": "Nouveau service",
  "Nova venda": "Nouvelle vente",
  "Nova parcela": "Nouvelle échéance",
  "Editar parcela": "Modifier l’échéance",
  "Parcela atual": "Échéance actuelle",
  "Total de parcelas": "Nombre total d’échéances",
  "Informe uma parcela válida, como 5 de 36.":
      "Indiquez une échéance valide, par exemple 5 sur 36.",
  "Nome": "Nom",
  "Descrição": "Description",
  "Valor": "Montant",
  "Desconto": "Remise",
  "Sem desconto": "Sans remise",
  "Valor fixo": "Montant fixe",
  "Percentual": "Pourcentage",
  "Recorrente": "Récurrent",
  "Cancelar": "Annuler",
  "Salvar": "Enregistrer",
  "Editar": "Modifier",
  "Excluir": "Supprimer",
  "Confirmar exclusão": "Confirmer la suppression",
  "Item removido.": "Élément supprimé.",
  "Desfazer": "Annuler la suppression",
  "Reserva de Emergência": "Fonds d’urgence",
  "Valor guardado": "Montant épargné",
  "1 mês": "1 mois",
  "3 meses": "3 mois",
  "6 meses": "6 mois",
  "Atualizar valor": "Mettre à jour le montant",
  "Aporte entra nos gastos; zero salva só a meta.": "Le versement est compté comme dépense ; zéro enregistre seulement l’objectif.",
  "Investimentos: Não avaliado": "Investissements : Non évalué",
  "Não foi possível carregar seus dados.": "Impossible de charger vos données.",
  "Tentar novamente": "Réessayer",
  "Total realizado no mês": "Total réalisé ce mois",
  "Nenhum lançamento nesta categoria.": "Aucune entrée dans cette catégorie.",
  "Ganho recorrente": "Revenu récurrent",
  "Somar à renda extra da Tela 1":
      "Ajouter au revenu supplémentaire de l’écran 1",
  "Ganho removido.": "Revenu supprimé.",
  "Sem ganhos": "Aucun revenu",
  "Serviços": "Services",
  "Vendas": "Ventes",
  "Pesquisar ou adicionar investimento":
      "Rechercher ou ajouter un investissement",
  "Limpar pesquisa": "Effacer la recherche",
  "Alocação de ativos": "Allocation des actifs",
  "Símbolo ou código": "Symbole ou code",
  "Família": "Famille",
  "Moeda original": "Devise d’origine",
  "Valor aplicado": "Montant investi",
  "Rendimento do mês": "Rendement du mois",
  "Confirmar posição": "Confirmer la position",
  "Excluir esta posição?": "Supprimer cette position ?",
  "Posição excluída.": "Position supprimée.",
  "Nenhuma posição nesta área e mês.":
      "Aucune position dans cette zone et ce mois.",
  "Adicionar manualmente": "Ajouter manuellement",
  "Renda Fixa": "Revenu fixe",
  "Imobiliários": "Immobilier",
  "Ações e ETFs": "Actions et ETF",
  "Simulador": "Simulateur",
  "Calculadora de juros compostos": "Calculatrice d’intérêts composés",
  "Aporte mensal": "Versement mensuel",
  "Taxa (%)": "Taux (%)",
  "Mensal": "Mensuel",
  "Anual": "Annuel",
  "Prazo em meses": "Durée en mois",
  "Calcular cenário": "Calculer le scénario",
  "Crescimento acima da inflação": "Croissance au-dessus de l’inflation",
  "Sua vida financeira": "Votre vie financière",
  "em relatórios claros": "en rapports clairs",
  "Relatório do mês atual": "Rapport du mois en cours",
  "Relatório dos últimos 3 meses": "Rapport des 3 derniers mois",
  "Relatório dos últimos 6 meses": "Rapport des 6 derniers mois",
  "Relatório anual": "Rapport annuel",
  "Imprimir": "Imprimer",
  "Compartilhar": "Partager",
  "Antes de compartilhar": "Avant de partager",
  "Continuar": "Continuer",
  "Sem movimentação": "Aucun mouvement",
  "Investimentos e crescimento real: Não avaliado":
      "Investissements et croissance réelle : Non évalué",
  "Fechar": "Fermer",
  "Nenhum compromisso neste dia.": "Aucun rendez-vous ce jour.",
  "Adicionar compromisso": "Ajouter un rendez-vous",
  "Novo compromisso": "Nouveau rendez-vous",
  "Título *": "Titre *",
  "Observação opcional": "Note facultative",
  "Recorrência": "Récurrence",
  "Nenhuma": "Aucune",
  "Semanal": "Hebdomadaire",
  "Lembretes locais": "Rappels locaux",
  "Informe o título do compromisso.": "Saisissez un titre de rendez-vous.",
  "Compromisso excluído.": "Rendez-vous supprimé.",
  "Compromissos\npessoais": "Rendez-vous\npersonnels",
  "Serviços\nagendados": "Services\nplanifiés",
  "Compromissos\nprofissionais": "Rendez-vous\nprofessionnels",
  "Plano Básico": "Formule Basique",
  "Plano Plus": "Formule Plus",
  "Plano Pro": "Formule Pro",
  "Plano atual": "Formule actuelle",
  "Convidar": "Inviter",
  "Convide um Amigo": "Inviter un ami",
  "Escolha a clareza que acompanha seu momento":
      "Choisissez la clarté adaptée à votre situation",
  "Oscar Clube": "Club Oscar",
  "Parceria remunerada": "Partenariat rémunéré",
  "Ver benefício": "Voir l’avantage",
  "Continuar para o parceiro": "Continuer vers le partenaire",
  "Nenhum benefício válido disponível para sua região neste momento.":
      "Aucun avantage valide n’est disponible dans votre région actuellement.",
  "Idioma, região e moeda": "Langue, région et devise",
  "Idioma": "Langue",
  "Moeda principal": "Devise principale",
  "Salvar alterações": "Enregistrer les modifications",
  "Configurações atualizadas": "Paramètres mis à jour",
  "Aparência": "Apparence",
  "Automático": "Automatique",
  "Claro": "Clair",
  "Escuro": "Sombre",
  "Atualizar reserva de emergência": "Mettre à jour le fonds d'urgence",
  "Reserva de emergência": "Fonds d'urgence",
  "Cadastre despesas para visualizar a participação na renda.":
      "Ajoutez des dépenses pour voir leur part dans vos revenus.",
  "Origem dos ganhos": "Sources de revenus",
  "Nenhum resultado local. O cadastro manual continua disponível.":
      "Aucun résultat local. La saisie manuelle reste disponible.",
  "Ela sairá da carteira, mas poderá ser restaurada por alguns segundos.": "La position sera retirée, mais pourra être restaurée pendant quelques secondes.",
  "Evolução patrimonial": "Évolution du patrimoine",
  "1 ano": "1 an",
  "Todo período": "Toute la période",
  "Patrimônio registrado": "Valeur enregistrée du portefeuille",
  "Câmbio indisponível: não é possível somar investimentos em moedas diferentes.": "Les taux de change sont indisponibles ; les placements en différentes devises ne peuvent pas être additionnés.",
  "Valorização acumulada": "Gains cumulés",
  "Somente rendimentos registrados; não inclui variação de mercado.":
      "Rendements enregistrés uniquement ; variations du marché exclues.",
  "Nenhum investimento registrado neste período.":
      "Aucun investissement enregistré sur cette période.",
  "Ver valores mês a mês": "Voir les valeurs mensuelles",
  "Aplicado + rendimento confirmado": "Montant investi + rendement confirmé",
  "Aportes e rendimentos registrados": "Versements et rendements enregistrés",
  "Total registrado": "Total enregistré",
  "Variação no período": "Variation sur la période",
  "Não inclui oscilações de mercado nem representa rentabilidade.":
      "Les variations du marché sont exclues ; ce n’est pas un rendement.",
  "Estimativa educacional. Não é promessa de rentabilidade nem recomendação.": "Estimation pédagogique. Ce n’est ni une promesse de rendement ni un conseil.",
  "Estimativa baseada em uma cesta média; não representa sua inflação pessoal.": "Estimation fondée sur un panier moyen ; elle ne représente pas votre inflation personnelle.",
  "A alocação aparecerá quando você cadastrar uma posição.":
      "La répartition apparaîtra après l’ajout d’une position.",
  "Não foi possível gerar o relatório. Tente novamente.":
      "Impossible de générer le rapport. Réessayez.",
  "Este documento contém informações financeiras pessoais. Compartilhe somente com pessoas de confiança.": "Ce document contient des informations financières personnelles. Partagez-le uniquement avec des personnes de confiance.",
  "O aplicativo agenda notificações locais. A entrega depende das permissões, economia de bateria, modo silencioso e políticas do aparelho.": "L’application programme des notifications locales. Leur réception dépend des autorisations, de l’économie d’énergie, du mode silencieux et des règles de l’appareil.",
  "Todos os planos preservam seus dados e a navegação completa. Recursos avançados são explicados no ponto de uso.": "Tous les forfaits conservent vos données et la navigation complète. Les fonctions avancées sont expliquées au moment de leur utilisation.",
  "Toque em um plano para visualizar os recursos disponíveis.":
      "Touchez un forfait pour voir les fonctionnalités disponibles.",
  "Uma indicação elegível pode oferecer até 40% de desconto. Benefícios não são cumulativos: prevalece sempre o maior desconto válido.": "Un parrainage éligible peut offrir jusqu’à 40 % de remise. Les avantages ne se cumulent pas : la remise valide la plus élevée s’applique.",
  "O convite seguro será habilitado quando contas e validação do servidor estiverem disponíveis.": "Les invitations sécurisées seront activées lorsque les comptes et la validation serveur seront disponibles.",
  "Benefícios úteis e transparentes para apoiar sua educação, bem-estar e vida prática. Ofertas nunca alteram seu Oscar Score nem acessam seus dados financeiros.": "Des avantages utiles et transparents pour l’éducation, le bien-être et le quotidien. Les offres n’affectent jamais votre Oscar Score et n’accèdent pas à vos données financières.",
  "O Oscar Finanças poderá receber uma comissão se você contratar ou comprar por este link. Você será direcionado ao ambiente do parceiro.": "Oscar Finanças peut recevoir une commission si vous achetez via ce lien. Vous serez redirigé vers l’espace du partenaire.",
  "O link deste parceiro ainda não está disponível.":
      "Le lien de ce partenaire n’est pas encore disponible.",
  "Região": "Région",
  "Primeiro dia da semana": "Premier jour de la semaine",
  "Ocultar valores ao abrir": "Masquer les montants au démarrage",
  "As Telas 1, 2 e 3 começam protegidas.":
      "Les écrans 1, 2 et 3 démarrent protégés.",
  "Ocultar valores ao sair": "Masquer les montants en quittant",
  "Oculta os valores quando o aplicativo vai para segundo plano.":
      "Masque les montants lorsque l’application passe en arrière-plan.",
  "Vibração e resposta tátil": "Vibration et retour haptique",
  "Lembrete padrão para novos eventos":
      "Rappel par défaut pour les nouveaux événements",
  "Cotações e indicadores": "Taux et indicateurs",
  "O último snapshot válido é usado offline. Atualizações indisponíveis aparecem como desatualizadas.": "Le dernier instantané valide est utilisé hors ligne. Les mises à jour indisponibles apparaissent comme obsolètes.",
  "O Oscar Finanças não se conecta a contas bancárias nem movimenta dinheiro. Informações, simulações e projeções têm caráter informativo e usam dados fornecidos por você e referências de mercado atualizadas. Cotações podem apresentar atrasos ou diferenças em relação ao mercado.": "Oscar Finanças ne se connecte pas aux comptes bancaires et ne déplace aucun argent. Les informations, simulations et projections sont indicatives et utilisent vos données ainsi que des références de marché actualisées. Les cours peuvent être retardés ou différer du marché.",
  "Atualização oficial disponível após configurar os provedores.": "Les mises à jour officielles seront disponibles après configuration des fournisseurs.",
  "Atualizar agora": "Mettre à jour",
  "Disponível em {tempo}": "Disponible dans {tempo}",
  "Oscar Finanças — Clareza que transforma escolhas em patrimônio.":
      "Oscar Finanças — La clarté qui transforme les choix en patrimoine.",
  "Organiza receitas, despesas, ganhos extras, saúde financeira, relatórios, agenda e investimentos sem movimentar seu dinheiro nem oferecer recomendação individual.": "Organise revenus, dépenses, gains complémentaires, santé financière, rapports, agenda et placements sans déplacer votre argent ni fournir de conseil individuel.",
  "Saldo atual": "Solde actuel",
  "Aporte deste mês": "Versement de ce mois",
  "O aporte será incluído na lista de gastos do mês.":
      "Le versement sera inclus dans la liste des dépenses de ce mois.",
  "Tipo de aporte": "Type de versement",
  "Aporte único": "Versement unique",
  "Mensal fixo": "Mensuel fixe",
  "Variável ou intermitente": "Variable ou intermittent",
  "Meta de cobertura": "Objectif de couverture",
  "Salário simulado": "Salaire d’exemple",
  "Aluguel simulado": "Loyer d’exemple",
  "Luz simulada": "Électricité d’exemple",
  "Água simulada": "Eau d’exemple",
  "Internet simulada": "Internet d’exemple",
  "Mercado simulado": "Courses d’exemple",
  "Reserva de emergência simulada": "Fonds d’urgence d’exemple",
  "Faculdade simulada": "Frais d’études d’exemple",
  "Carro simulado": "Voiture d’exemple",
  "TV simulada": "TV d’exemple",
  "Freelance de design simulado": "Mission design d’exemple",
  "Serviço freelance": "Mission en freelance",
  "Projeto ou atendimento do mês": "Projet ou prestation du mois",
  "Projeto pontual simulado": "Projet ponctuel d’exemple",
  "Manutenção de computador simulada": "Maintenance informatique d’exemple",
  "Serviço técnico simulado": "Service technique d’exemple",
  "Venda de bicicleta simulada": "Vente de vélo d’exemple",
  "Venda ocasional simulada": "Vente occasionnelle d’exemple",
  "Venda ocasional": "Vente occasionnelle",
  "Venda de item ou produto": "Vente d’un article ou d’un produit",
  "Venda de doces simulada": "Vente de confiseries d’exemple",
  "Renda complementar simulada": "Revenu complémentaire d’exemple",
  "Tesouro Selic simulado": "Obligation publique d’exemple",
  "CDB simulado": "Placement bancaire d’exemple",
  "Fundo imobiliário simulado": "Fonds immobilier d’exemple",
  "Ação simulada": "Action d’exemple",
  "Versão 0.1.0 · compilação 1": "Version 0.1.0 · build 1",
  "Organização financeira essencial, sem custo.":
      "Organisation financière essentielle, gratuite.",
  "Painel Financeiro completo, Reserva de Emergência e Oscar Score":
      "Tableau financier complet, fonds d’urgence et Oscar Score",
  "Relatório mensal com impressão e compartilhamento":
      "Rapport mensuel à imprimer et partager",
  "Agenda completa com recorrência e lembretes locais":
      "Agenda complet avec récurrence et rappels locaux",
  "Oscar Clube e Configurações": "Oscar Club et Paramètres",
  "Grátis": "Gratuit",
  "Mais controle para quem transforma trabalho em renda.":
      "Plus de contrôle pour transformer le travail en revenu.",
  "Tudo do Plano Básico": "Tout le forfait Basique",
  "Ganho Extra completo: Serviços, Vendas e recorrências":
      "Revenus complémentaires complets : services, ventes et récurrences",
  "Integração Agenda → Ganho Extra":
      "Intégration Agenda → Revenus complémentaires",
  "Relatórios do mês e dos últimos 3 meses":
      "Rapports du mois et des 3 derniers mois",
  "Visão patrimonial completa, simples e internacional.":
      "Vision patrimoniale complète, simple et internationale.",
  "Tudo do Plano Plus": "Tout le forfait Plus",
  "Investimentos, busca internacional, ações e ETFs":
      "Placements, recherche internationale, actions et ETF",
  "Crescimento real e resumo em BRL, USD, EUR e INR":
      "Croissance réelle et synthèse en BRL, USD, EUR et INR",
  "Relatórios de 1, 3, 6 e 12 meses": "Rapports sur 1, 3, 6 et 12 mois",
  "Educação e Carreira": "Éducation et Carrière",
  "Cursos, idiomas, livros, certificações e ferramentas profissionais.":
      "Cours, langues, livres, certifications et outils professionnels.",
  "Saúde, Beleza e Bem-estar": "Santé, Beauté et Bien-être",
  "Cuidados pessoais, academias, exames e soluções de bem-estar.":
      "Soins personnels, salles de sport, examens et solutions de bien-être.",
  "Viagens e Experiências": "Voyages et Expériences",
  "Hospedagem, cultura, gastronomia, passeios e serviços relacionados.":
      "Hébergement, culture, gastronomie, visites et services associés.",
  "Tecnologia e Vida Prática": "Technologie et Vie pratique",
  "Notificações": "Notifications",
  "Lançamentos recorrentes": "Écritures récurrentes",
  "Relatório mensal disponível": "Rapport mensuel disponible",
  "Dados econômicos e câmbio": "Données économiques et change",
  "Transparência e metodologia": "Transparence et méthodologie",
  "Sobre o aplicativo": "À propos de l’application",
  "Estados Unidos": "États-Unis",
  "Alemanha": "Allemagne",
  "França": "France",
  "Índia": "Inde",
  "No horário": "À l’heure prévue",
  "1 dia antes e no horário": "1 jour avant et à l’heure prévue",
  "3 dias antes, 1 dia antes e no horário":
      "3 jours avant, 1 jour avant et à l’heure prévue",
  "Termos de Uso": "Conditions d’utilisation",
  "Política de Privacidade": "Politique de confidentialité",
  "Consentimento e tratamento de dados financeiros":
      "Consentement et traitement des données financières",
  "Política de Anúncios": "Politique publicitaire",
  "Política de Parcerias e Benefícios":
      "Politique de partenariats et avantages",
  "Privacidade Internacional": "Confidentialité internationale",
  "Exclusão de dados": "Suppression des données",
  "Aviso financeiro": "Avertissement financier",
  "Metodologia do Oscar Score": "Méthodologie Oscar Score",
  "Licenças e bibliotecas": "Licences et bibliothèques",
  "O Oscar Finanças organiza informações fornecidas pelo usuário. Os cálculos e projeções são educacionais, podem conter limitações e não constituem consultoria financeira. O usuário é responsável pela exatidão dos dados cadastrados e pelo uso dos relatórios.": "Oscar Finanças organise les informations fournies par l’utilisateur. Les calculs et projections sont pédagogiques, peuvent comporter des limites et ne constituent pas un conseil financier. L’utilisateur est responsable de l’exactitude des données et de l’usage des rapports.",
  "Dados financeiros permanecem no aparelho nesta versão. Serviços públicos de câmbio e indicadores não recebem valores da carteira. Recursos externos devem declarar finalidade, retenção e fundamento legal antes da publicação.": "Dans cette version, les données financières restent sur l’appareil. Les services publics de change et d’indicateurs ne reçoivent aucune valeur du portefeuille. Tout service externe doit déclarer finalité, conservation et base juridique avant publication.",
  "O aplicativo aplica minimização, finalidade e controle do usuário. LGPD, GDPR e normas regionais serão observadas de acordo com o país de disponibilização.": "L’application applique minimisation, limitation des finalités et contrôle utilisateur. La LGPD, le RGPD et les règles régionales seront respectés selon le pays de diffusion.",
  "Espaços publicitários futuros usarão um módulo isolado. Personalização dependerá de consentimento aplicável e nenhum anúncio receberá receitas, despesas, agenda, relatório ou carteira.": "Les futurs espaces publicitaires utiliseront un module isolé. La personnalisation exigera le consentement applicable et aucune publicité ne recevra les revenus, dépenses, agenda, rapports ou portefeuille.",
  "O Oscar Finanças poderá receber comissão por links identificados. A transparência aparece antes da saída; critérios comerciais não alteram Oscar Score, relatórios ou cálculos.": "Oscar Finanças peut percevoir une commission via des liens identifiés. L’information apparaît avant de quitter l’application ; les critères commerciaux n’affectent ni Oscar Score, ni rapports, ni calculs.",
  "Idioma, região e moeda são independentes. Transferências internacionais, quando existirem, deverão informar destino, proteção e direitos aplicáveis.": "Langue, région et devise sont indépendantes. Toute future opération internationale devra indiquer destination, protection et droits applicables.",
  "A exclusão local exige confirmação forte e não deve ocorrer parcialmente. Exclusão de conta só será exibida quando contas e sincronização reais estiverem implementadas.": "La suppression locale exige une confirmation forte et ne doit pas être partielle. La suppression de compte n’apparaîtra qu’après mise en œuvre de comptes et d’une synchronisation réels.",
  "O aplicativo não executa investimentos, não oferece custódia e não recomenda compra ou venda. Câmbio, inflação e rentabilidade podem variar; desempenho passado não garante resultado futuro.": "L’application n’exécute pas de placements, n’assure pas la garde et ne recommande ni achat ni vente. Change, inflation et rendements peuvent varier ; les performances passées ne garantissent pas les résultats futurs.",
  "O Oscar Score resume a sobra mensal em relação à renda bruta. Ele considera entradas confirmadas, despesas e déficit. Não é score de crédito e não determina acesso a produtos.": "Oscar Score résume le solde mensuel par rapport au revenu brut. Il tient compte des revenus confirmés, dépenses et déficits. Ce n’est pas un score de crédit et il ne détermine aucun accès à des produits.",
  "O crescimento real estimado subtrai do rendimento nominal um efeito inflacionário baseado em índice oficial médio. Esse índice não representa a inflação pessoal de cada usuário.": "La croissance réelle estimée retranche du rendement nominal un effet d’inflation fondé sur un indice officiel moyen. Cet indice ne représente pas l’inflation personnelle de chaque utilisateur.",
  "Construído com Flutter e bibliotecas revisadas para gráficos, banco local, PDF, impressão e notificações. A relação final de licenças será gerada para a versão publicada.": "Construit avec Flutter et des bibliothèques vérifiées pour graphiques, stockage local, PDF, impression et notifications. La liste finale des licences sera produite pour la version publiée.",
  "Ativos relacionados": "Actifs associés",
  "Deslize para ver mais": "Balayez pour en voir plus",
  "Dados simulados": "Données simulées",
  "Aguardando cotação": "En attente de cotation",
  "Cotação atualizada": "Cotation actualisée",
  "Última cotação salva": "Dernière cotation enregistrée",
  "Privacidade dos valores": "Confidentialité des montants",
  "Lembretes da Agenda": "Rappels du calendrier",
  "Fechamento mensal": "Clôture mensuelle",
  "Plano e assinatura": "Forfait et abonnement",
  "Domingo": "Dimanche",
  "Segunda-feira": "Lundi",
  "Escolher": "Choisir",
  "por mês": "par mois",
  "mês": "mois",
  "por ano": "par an",
  "equivalente a": "équivaut à",
  "economize": "économisez",
  "Serviços do mês": "Services du mois",
  "Vendas do mês": "Ventes du mois",
  "Adicionar serviço": "Ajouter un service",
  "Adicionar venda": "Ajouter une vente",
  "Somado à Tela 1": "Inclus dans l’écran 1",
  "Nenhuma entrada neste mês.": "Aucun revenu ce mois-ci.",
  "Sem movimentações para exibir": "Aucune activité à afficher",
  "Nenhum gasto neste mês.": "Aucune dépense ce mois-ci.",
  "Nenhuma parcela neste mês.": "Aucune échéance ce mois-ci.",
  "Adicionar entrada": "Ajouter un revenu",
  "Adicionar gasto": "Ajouter une dépense",
  "Adicionar parcela": "Ajouter une échéance",
  "Sobra": "Solde",
  "Déficit": "Déficit budgétaire",
  "Não calculado": "Non calculé",
  "Não avaliado": "Non évalué",
  "Não avaliada": "Non évaluée",
  "Cadastre uma entrada para calcular seu Oscar Score.":
      "Ajoutez un revenu pour calculer votre Oscar Score.",
  "Cadastre gastos para calcular a cobertura":
      "Ajoutez des dépenses pour calculer la couverture",
  "Valor do desconto": "Montant de la remise",
  "Títulos públicos": "Obligations d’État",
  "Renda fixa bancária": "Revenu fixe bancaire",
  "Títulos empresariais": "Obligations d’entreprise",
  "Ações": "Actions",
  "Cadastro manual": "Saisie manuelle",
  "Cotações indisponíveis": "Cours indisponibles",
  "Cotações atualizadas com sucesso.": "Cours mis à jour.",
  "Não foi possível atualizar as cotações.":
      "Impossible de mettre à jour les cours.",
  "Sem conexão. O último valor disponível foi mantido.":
      "Hors ligne. La dernière valeur disponible a été conservée.",
  "Cotações demonstrativas desatualizadas · dados reais serão atualizados por adaptador seguro": "Cours de démonstration obsolètes · les données réelles seront mises à jour en sécurité",
  "Cotações atualizadas · fonte de mercado":
      "Cours actualisés · source de marché",
  "Aviso educacional financeiro": "Avertissement pédagogique financier",
  "Como funciona o Oscar Score": "Fonctionnement de l’Oscar Score",
  "Dispositivos, software, conectividade, casa, estudo e trabalho.":
      "Appareils, logiciels, connectivité, maison, études et travail.",
  "DOM": "DIM",
  "SEG": "LUN",
  "TER": "MAR",
  "QUA": "MER",
  "QUI": "JEU",
  "SEX": "VEN",
  "SÁB": "SAM",
  "Aplicado: {value}": "Investi : {value}",
  "Rendimento: {value}": "Rendement : {value}",
  "Rendeu no mês: {value}": "Rendement du mois : {value}",
  "Efeito estimado da inflação: {value}":
      "Effet estimé de l’inflation : {value}",
  "Crescimento real estimado: {value}": "Croissance réelle estimée : {value}",
  "Patrimônio estimado: {value}": "Patrimoine estimé : {value}",
  "Valor inicial ({currency})": "Montant initial ({currency})",
  "Saldo atual: {value}": "Solde actuel : {value}",
  "{value} guardados": "{value} épargnés",
  "Cobre aproximadamente {value} meses": "Couvre environ {value} mois",
  "Meta: {months} meses · {percent}%": "Objectif : {months} mois · {percent}%",
  "Meta: {months} meses": "Objectif : {months} mois",
  "meses de cobertura": "mois de couverture",
  "da meta": "de l’objectif",
  "Ajustar meta": "Ajuster l’objectif",
  "O aporte deve ser maior que zero.":
      "Le versement doit être supérieur à zéro.",
  "Fluxo do mês: {value}/100": "Flux du mois : {value}/100",
  "Reserva: {value} meses": "Réserve : {value} mois",
  "Reserva de Emergência: {value} meses": "Fonds d’urgence : {value} mois",
  "{name} · {amount} será removido deste mês.":
      "{name} · {amount} sera supprimé de ce mois.",
  "{name} será removido de {month}.": "{name} sera supprimé de {month}.",
  "Cadastrar “{name}” manualmente": "Ajouter « {name} » manuellement",
  "Serviços · {value}%": "Services · {value}%",
  "Vendas · {value}%": "Ventes · {value}%",
  "Horário · {time}": "Heure · {time}",
  "Escolher {plan}": "Choisir {plan}",
  "Este período está disponível no Plano {plan}.":
      "Cette période est disponible avec la formule {plan}.",
  "Relatório · {count} folha": "Rapport · {count} page",
  "Relatório · {count} folhas": "Rapport · {count} pages",
  "Competência {month} · Página {page} de {total}":
      "Période {month} · Page {page} sur {total}",
  "Criptomoedas": "Cryptomonnaies",
  "Quantidade": "Quantité",
  "Informe uma quantidade válida.": "Saisissez une quantité valide.",
  "Histórico em formação": "Historique en cours de constitution",
  "Variação em 24 horas": "Variation sur 24 heures",
  "O convite de amigos está indisponível nesta versão.":
      "Les invitations d’amis sont indisponibles dans cette version.",
  "Receba 30% de desconto quando um amigo indicado se cadastrar e contratar um plano anual. Assinaturas mensais não participam. Descontos não se acumulam: vale o maior desconto elegível.": "Obtenez 30 % de réduction lorsqu’un ami parrainé s’inscrit et souscrit une formule annuelle. Les abonnements mensuels sont exclus. Les réductions ne se cumulent pas : la plus élevée s’applique.",
  "Carteira de criptomoedas com cotações CoinMarketCap":
      "Portefeuille crypto avec les cotations CoinMarketCap",
  "entry.welcome": "Vos finances avec clarté, confidentialité et objectif.",
  "entry.google": "Continuer avec Google",
  "entry.apple": "Continuer avec Apple",
  "entry.guest": "Continuer sans compte",
  "entry.disclaimer": "Vos données financières restent sur cet appareil.",
  "drawer.close": "Fermer le menu",
  "privacy.hide": "Masquer les montants",
  "privacy.show": "Afficher les montants",
  "month.previous": "Mois précédent",
  "month.next": "Mois suivant",
  "screen.financial": "Tableau financier",
  "screen.extraIncome": "Revenus supplémentaires",
  "screen.investments": "Investissements",
  "screen.objectives": "Objectifs",
  "screen.reports": "Rapport général",
  "screen.agenda": "Agenda",
  "screen.calculator": "Calculatrice",
  "screen.plans": "Formules",
  "screen.club": "Club Oscar",
  "screen.settings": "Paramètres",
  "objectives.subtitle": "Suivez la progression de vos objectifs",
  "Objetivos financeiros com evolução mês a mês":
      "Objectifs financiers avec suivi mois par mois",
  "objectives.new": "Nouvel objectif",
  "objectives.emptyTitle": "Vos objectifs commencent ici",
  "objectives.emptyBody": "Créez un objectif pour suivre les versements et leur évolution dans le temps.",
  "objectives.loadFailed": "Impossible de charger vos objectifs.",
  "objectives.retry": "Réessayer",
  "objectives.name": "Nom de l’objectif",
  "objectives.nameRequired": "Saisissez un nom pour cet objectif.",
  "objectives.targetPeriod": "Échéance de l’objectif",
  "objectives.threeMonths": "3 mois",
  "objectives.sixMonths": "6 mois",
  "objectives.oneYear": "1 an",
  "objectives.fiveYears": "5 ans",
  "objectives.tenYears": "10 ans",
  "objectives.monthCount": "{count} mois",
  "objectives.targetAmount": "Montant de l’objectif",
  "objectives.targetRequired": "Saisissez un montant supérieur à zéro.",
  "objectives.initialBalance": "Montant déjà épargné",
  "objectives.initialBalanceHelp":
      "Montant déjà mis de côté, avant les nouveaux versements.",
  "objectives.contribution": "Versement",
  "objectives.addContribution": "Ajouter un versement",
  "objectives.contributionAmount": "Montant du versement",
  "objectives.saveContribution": "Enregistrer le versement",
  "objectives.contributionSaved":
      "Versement ajouté à l’objectif et enregistré dans les dépenses.",
  "objectives.exchangeUnavailable":
      "Taux de change indisponible ; le versement n’a pas pu être converti.",
  "Saldo reservado": "Solde épargné",
  "Aportes acumulados": "Versements cumulés",
  "Meta": "Objectif",
  "Acompanhe sua meta na tela Objetivos":
      "Suivez le solde, les versements et la progression de votre réserve",
  "Aporte · {name}": "Versement · {name}",
  "objectives.annualRate": "Taux annuel",
  "objectives.compoundInterest": "Intérêts composés par an",
  "objectives.annualRateShort": "Taux annuel",
  "objectives.lowerRate": "Baisser le taux",
  "objectives.raiseRate": "Augmenter le taux",
  "objectives.annualRateHelp":
      "Saisissez le taux à utiliser pour la projection ou laissez 0 %.",
  "objectives.rateTooHigh": "Saisissez un taux annuel entre 0 % et 100 %.",
  "objectives.frequency": "Fréquence du versement",
  "objectives.oneTime": "Ponctuel",
  "objectives.monthly": "Mensuel récurrent",
  "objectives.projectionDisclosure": "Ce taux produit une estimation, pas un cours en temps réel. Le versement de ce mois apparaît aussi dans Dépenses sous « Versement · objectif ».",
  "objectives.create": "Créer l’objectif",
  "objectives.cancel": "Annuler",
  "objectives.created": "Objectif créé.",
  "objectives.goalActions": "Actions sur l’objectif",
  "objectives.delete": "Supprimer",
  "objectives.deleteTitle": "Supprimer cet objectif ?",
  "objectives.deleteBody": "L’objectif et sa progression seront retirés de cet écran. Les opérations de versement dans Dépenses seront conservées.",
  "objectives.currentBalance": "Solde projeté pour ce mois",
  "objectives.contributions": "Versements cumulés",
  "objectives.estimatedYield": "Rendement estimé",
  "objectives.returnLabel": "Rendement",
  "objectives.progressSemantics": "Progression de l’objectif : {percent} %",
  "objectives.target": "Objectif : {months} · {amount}",
  "objectives.percentComplete": "{percent} % atteint",
  "objectives.importedHistory": "Historique des versements importé depuis les dépenses. Aucun rendement n’a été supposé.",
  "objectives.viewEvolution": "Évolution mensuelle",
  "objectives.chartDescription":
      "Graphique de l’évolution mensuelle du solde de l’objectif",
  "objectives.monthlyEvolution": "Évolution mois par mois",
  "objectives.estimatedYieldShort": "Rend. estimé",
  "objectives.actualYieldShort": "Rendement",
  "objectives.closingBalance": "Solde final",
  "objectives.projectionFootnote": "Estimation selon le taux annuel saisi ({rate} % par an). Aucun cours en temps réel ; vérifiez le solde réel auprès de votre établissement.",
  "foundation.ready": "Structure prête pour la prochaine étape",
  "Brasil": "Brésil",
  "Clareza que transforma escolhas em patrimônio":
      "La clarté qui transforme les choix en patrimoine",
  "Fluxo do mês: Não calculado": "Flux du mois : Non calculé",
  "Reserva: Não avaliada": "Réserve : Non évaluée",
  "Oscar Score: Não calculado": "Oscar Score : Non calculé",
  "Reserva de Emergência: Não avaliada": "Fonds d’urgence : Non évalué",
  "Indisponível": "Indisponible",
  "home.block.financial": "Tableau de Bord Financier",
  "home.block.extraIncome": "Revenus Supplémentaires",
  "home.block.investments": "Investissements",
  "home.block.emergencyFund": "Fonds d’urgence",
  "home.block.objectives": "Objectifs",
  "Acompanhe o progresso das suas metas":
      "Suivez la progression de vos objectifs",
  "Saldo dos objetivos": "Solde des objectifs",
  "Total acumulado": "Total des versements",
  "Meta total": "Objectif total",
  "Últimas cotações salvas · atualização automática":
      "Derniers taux enregistrés · mise à jour automatique",
  "Últimas cotações salvas · atualização automática indisponível":
      "Derniers taux enregistrés · mise à jour automatique indisponible",
  "legal.privacy.body": "Oscar Finanças utilise les montants, descriptions, placements et rendez-vous que vous saisissez pour organiser vos finances. Dans l’application installée, ces données restent sur votre appareil ; dans la version web, elles sont enregistrées localement dans ce navigateur et restent disponibles après rechargement. Les préférences sont également enregistrées localement.\n\nLes cotations proviennent d’AwesomeAPI, HG Brasil, Alpha Vantage et CoinMarketCap. Les requêtes transmettent des devises et des identifiants d’actifs, jamais les quantités, soldes, montants investis, descriptions ou rendez-vous. Les services de connexion peuvent recevoir votre adresse IP et des métadonnées techniques.\n\nLes rapports ne sont transmis à d’autres applications ou destinataires que si vous choisissez de les imprimer ou partager. Nous ne vendons pas vos données financières. Cette version ne synchronise pas les données avec un compte distant et ne contient aucun SDK publicitaire ou d’analyse comportementale.\n\nVous pouvez modifier et retirer des éléments. Le retrait peut être annulé et conserver localement des éléments marqués comme supprimés. Les données web restent dans ce navigateur jusqu’à leur retrait dans l’application ou à l’effacement des données du site dans les paramètres du navigateur. Dans l’application installée, effacez les données de l’application dans les paramètres système pour supprimer la base locale. Les fichiers exportés et copies externes doivent être supprimés séparément.",
  "legal.ads.body": "Cette version ne diffuse aucune publicité et n’intègre pas le SDK AdMob. Les données financières ne servent pas au ciblage publicitaire. Si des publicités sont proposées, cette politique et les contrôles de confidentialité seront mis à jour avant leur activation. Lorsque cela est requis, vous pourrez choisir et revoir votre consentement avant les requêtes publicitaires.",
  "legal.permissions.body": "Les rappels utilisent des notifications locales avec l’autorisation du système si nécessaire. Vous pouvez la révoquer dans les paramètres de l’appareil. L’application n’a pas besoin de vos contacts, de votre position précise, de la caméra ou du microphone pour organiser vos finances. Un refus peut empêcher les rappels, mais pas la saisie financière.",
  "Permissões e notificações": "Autorisations et notifications",
  "legal.terms.body": "Oscar Finanças organise vos finances et fournit des calculs pédagogiques à partir de vos saisies. Il ne déplace pas d’argent, n’exécute pas d’ordres, ne conserve pas de cryptomonnaies et ne fournit pas de conseil individuel en investissement. Les cotations peuvent être retardées ou indisponibles. Les valeurs de marché ne sont pas des revenus réalisés.\n\nVous devez vérifier vos données et protéger l’accès à votre appareil et aux rapports exportés. Les projections ne garantissent aucun résultat. L’estimation de l’inflation utilise un taux de référence local et ne représente pas votre inflation personnelle. Les achats d’abonnements et invitations d’amis sont indisponibles dans cette version ; les boutons des formules ne déclenchent aucun paiement.",
  "report.documentSummary.one": "{months} mois · {pages} pages PDF",
  "report.documentSummary.many": "{months} mois · {pages} pages PDF",
  "report.monthLabel": "Mois",
  "report.pdfPagesLabel": "Pages PDF",
  "report.summary": "Résumé du mois",
  "report.incomeSection": "Revenus",
  "report.assets": "Actifs",
  "report.cryptoassets": "Crypto-actifs",
  "report.objectives": "Objectifs",
  "report.ofTarget": "de l’objectif",
  "report.quantity": "Quantité",
  "report.monthlyReturn": "Rendement mensuel",
  "report.target": "Objectif",
  "report.monthlyYield": "Gain du mois",
  "report.estimated": "estimé",
  "report.confirmed": "enregistré",
  "report.footerNote": "Valeurs enregistrées pour le mois",
  "report.demoFirst100k": "Mes premiers 100 000",
  "report.tagline": "La clarté qui transforme les choix en patrimoine",
  "report.report": "Rapport financier",
  "Relatório financeiro": "Rapport financier",
  "report.personal": "Document personnel",
  "Documento pessoal": "Document personnel",
  "report.currency": "devise de base",
  "moeda base": "devise de base",
  "report.generated": "généré le",
  "gerado em": "généré le",
  "report.noMovement": "Aucun mouvement",
  "report.mainIncome": "Revenu principal",
  "Renda principal": "Revenu principal",
  "report.extra": "Revenu complémentaire confirmé",
  "Ganho Extra confirmado": "Revenu complémentaire confirmé",
  "report.total": "Revenus totaux",
  "Entradas totais": "Revenus totaux",
  "report.expenses": "Dépenses",
  "Despesas": "Dépenses",
  "report.installments": "Échéances",
  "Parcelas": "Échéances",
  "report.balance": "Solde disponible",
  "Sobra disponível": "Solde disponible",
  "report.deficit": "Déficit",
  "report.health": "Santé financière",
  "Saúde financeira": "Santé financière",
  "report.notCalculated": "Non calculé",
  "report.fund": "Fonds d'urgence",
  "report.notEvaluated": "Non évalué",
  "report.months": "mois",
  "meses": "mois",
  "report.mainExpenses": "Dépenses enregistrées",
  "Principais gastos": "Principales dépenses",
  "report.noExpenses": "Aucune dépense enregistrée.",
  "Nenhum gasto cadastrado.": "Aucune dépense enregistrée.",
  "report.extraDetails": "Détail des revenus complémentaires",
  "report.noExtraIncome": "Aucun revenu complémentaire enregistré.",
  "report.printUnavailable": "Impossible d’ouvrir l’impression. Utilisez Partager pour télécharger le PDF.",
  "report.printFallback": "La fenêtre d’impression ne s’est pas ouverte ; le PDF a été téléchargé pour être imprimé depuis votre lecteur.",
  "report.investments": "Placements et croissance réelle",
  "Investimentos e crescimento real": "Placements et croissance réelle",
  "report.page": "Page",
  "Página": "Page",
  "report.of": "sur",
  "de": "sur",
  "report.critical": "Alerte critique",
  "Alerta Crítico": "Alerte critique",
  "report.attention": "Attention / Serré",
  "Atenção / Apertado": "Attention / Serré",
  "report.balanced": "Équilibré",
  "Equilibrado": "Équilibré",
  "report.healthy": "Sain",
  "Saudável": "Sain",
  "report.prosperous": "Prospère",
  "Próspero": "Prospère",
  "Parcela {current} de {total}": "Échéance {current} sur {total}",
  "Atenção": "Attention",
  "Alerta crítico": "Alerte critique",
  "{date}, {count} compromissos": "{date}, {count} rendez-vous",
  "Oscar Score, {score} de 100, {level}":
      "Oscar Score, {score} sur 100, {level}",
  "Oscar Score não calculado. Cadastre uma entrada.":
      "Oscar Score non calculé. Ajoutez un revenu.",
  "Painel financeiro, valores ocultos": "Tableau financier, montants masqués",
  "Painel Financeiro": "Tableau financier",
  "O mês pede proteção. Reveja os maiores compromissos.": "Ce mois demande de la prudence. Réexaminez vos engagements les plus importants.",
  "Há pouco espaço de manobra. Pequenos ajustes podem abrir fôlego.": "La marge est limitée. De petits ajustements peuvent vous donner de l’air.",
  "Sua estrutura está equilibrada. Preserve a constância.":
      "Vos finances sont équilibrées. Gardez cette régularité.",
  "Boa margem financeira. Continue fortalecendo sua reserva.":
      "Votre marge financière est bonne. Continuez à renforcer votre réserve.",
  "Excelente capacidade de sobra. Direcione esse resultado com propósito.": "Votre capacité d’épargne est excellente. Donnez un objectif à ce résultat.",
  "Criptoativos": "Cryptoactifs",
  "Carteira de criptoativos": "Portefeuille de cryptoactifs",
  "Sem anúncios": "Sans publicité",
  "Criptoativos relacionados": "Cryptoactifs associés",
  "Carteira": "Portefeuille",
  "comprometido": "engagé",
  "Disponível no Plano {plan}.": "Disponible avec la formule {plan}.",
  "Histórico indisponível": "Historique indisponible",
  "Início": "Accueil",
  "Resumo de {month}": "Résumé de {month}",
  "Painel financeiro": "Tableau financier",
  "Sua vida financeira em um só lugar": "Vos finances en un seul endroit",
  "Saldo do mês": "Solde du mois",
  "Ganhos extras": "Revenus supplémentaires",
  "Renda além do seu salário": "Des revenus en plus de votre salaire",
  "Total no mês": "Total du mois",
  "Investimentos": "Investissements",
  "Seu patrimônio trabalhando por você": "Votre patrimoine travaille pour vous",
  "Total investido": "Total investi",
  "Ativos": "Actifs",
  "Variação indisponível": "Variation indisponible",
  "investment.period.month": "mois",
  "24h": "24 h",
  "{count} ativo": "{count} actif",
  "{count} ativos": "{count} actifs",
  "{count} criptoativo": "{count} cryptoactif",
  "{count} criptoativos": "{count} cryptoactifs",
  "{count} ativos na carteira": "{count} actifs dans le portefeuille",
  "Carregando resumo…": "Chargement du résumé…",
  "Resumo indisponível": "Résumé indisponible",
  "screen.account": "Mon compte",
  "Dados do perfil": "Données du profil",
  "Data de nascimento": "Date de naissance",
  "Receber comunicações do Oscar Hive":
      "Recevoir les communications d’Oscar Hive",
  "Opcional e independente da publicidade.":
      "Facultatif et indépendant de la publicité.",
  "Essa preferência fica salva neste aparelho.":
      "Cette préférence est enregistrée sur cet appareil.",
  "Perfil salvo neste dispositivo.": "Profil enregistré sur cet appareil.",
  "Não foi possível salvar o perfil.": "Impossible d’enregistrer le profil.",
  "O acesso com Google ainda não está disponível nesta versão.":
      "La connexion Google n’est pas encore disponible dans cette version.",
  "Apple estará disponível em uma versão futura.":
      "La connexion Apple sera disponible dans une prochaine version.",
  "Cópia de segurança e recuperação": "Sauvegarde et récupération",
  "Seus dados ficam neste aparelho. A sincronização e a recuperação na nuvem ainda não estão disponíveis.": "Vos données restent sur cet appareil. La synchronisation et la récupération dans le cloud ne sont pas encore disponibles.",
  "legal.account.profile.body": "Votre nom, votre date de naissance et votre préférence de communication sont facultatifs et enregistrés uniquement sur cet appareil. Ces données ne sont pas envoyées à un compte distant. Aucune communication n’est envoyée dans cette version.",
};
