// Reviewed product copy for this language only. No cross-language fallback.
const hiInMessages = <String, String>{
  "Entradas": "आय",
  "Gastos": "खर्च",
  "Parcelas Longas": "दीर्घकालीन किस्तें",
  "Participação das despesas": "खर्च का हिस्सा",
  "Nova entrada": "नई आय",
  "Novo gasto": "नया खर्च",
  "Editar entrada": "आय संपादित करें",
  "Editar gasto": "खर्च संपादित करें",
  "Editar serviço": "सेवा संपादित करें",
  "Editar venda": "बिक्री संपादित करें",
  "Nova parcela": "नई किस्त",
  "Editar parcela": "किस्त संपादित करें",
  "Parcela atual": "वर्तमान किस्त",
  "Total de parcelas": "कुल किस्तें",
  "Informe uma parcela válida, como 5 de 36.":
      "मान्य किस्त दर्ज करें, जैसे 36 में से 5।",
  "Nome": "नाम",
  "Valor": "राशि",
  "Desconto": "छूट",
  "Sem desconto": "कोई छूट नहीं",
  "Valor fixo": "निश्चित राशि",
  "Percentual": "प्रतिशत",
  "Recorrente": "आवर्ती",
  "Cancelar": "रद्द करें",
  "Salvar": "सहेजें",
  "Editar": "संपादित करें",
  "Excluir": "हटाएँ",
  "Confirmar exclusão": "हटाने की पुष्टि करें",
  "Item removido.": "आइटम हटाया गया।",
  "Desfazer": "पूर्ववत करें",
  "Reserva de Emergência": "आपातकालीन निधि",
  "Valor guardado": "बचाई गई राशि",
  "1 mês": "1 महीना",
  "3 meses": "3 महीने",
  "6 meses": "6 महीने",
  "Atualizar valor": "राशि अपडेट करें",
  "Aporte entra nos gastos; zero salva só a meta.":
      "योगदान खर्च में दर्ज होगा; शून्य से केवल लक्ष्य सहेजा जाएगा।",
  "Investimentos: Não avaliado": "निवेश: मूल्यांकन नहीं हुआ",
  "Não foi possível carregar seus dados.": "आपका डेटा लोड नहीं हो सका।",
  "Tentar novamente": "फिर प्रयास करें",
  "Total realizado no mês": "महीने की कुल आय",
  "Nenhum lançamento nesta categoria.": "इस श्रेणी में कोई प्रविष्टि नहीं है।",
  "Ganho recorrente": "आवर्ती आय",
  "Somar à renda extra da Tela 1": "स्क्रीन 1 की अतिरिक्त आय में जोड़ें",
  "Ganho removido.": "आय हटाई गई।",
  "Sem ganhos": "कोई आय नहीं",
  "Serviços": "सेवाएँ",
  "Vendas": "बिक्री",
  "Pesquisar ou adicionar investimento": "निवेश खोजें या जोड़ें",
  "Limpar pesquisa": "खोज साफ़ करें",
  "Alocação de ativos": "परिसंपत्ति आवंटन",
  "Símbolo ou código": "प्रतीक या कोड",
  "Família": "श्रेणी",
  "Moeda original": "मूल मुद्रा",
  "Valor aplicado": "निवेशित राशि",
  "Rendimento do mês": "मासिक प्रतिफल",
  "Confirmar posição": "स्थिति की पुष्टि करें",
  "Excluir esta posição?": "यह स्थिति हटाएँ?",
  "Posição excluída.": "स्थिति हटाई गई।",
  "Nenhuma posição nesta área e mês.":
      "इस क्षेत्र और महीने में कोई स्थिति नहीं है।",
  "Adicionar manualmente": "मैन्युअल रूप से जोड़ें",
  "Renda Fixa": "निश्चित आय",
  "Imobiliários": "रियल एस्टेट",
  "Ações e ETFs": "शेयर और ETF",
  "Simulador": "सिम्युलेटर",
  "Calculadora de juros compostos": "चक्रवृद्धि ब्याज कैलकुलेटर",
  "Aporte mensal": "मासिक योगदान",
  "Taxa (%)": "दर (%)",
  "Mensal": "मासिक",
  "Anual": "वार्षिक",
  "Prazo em meses": "अवधि (महीने)",
  "Calcular cenário": "परिदृश्य की गणना करें",
  "Crescimento acima da inflação": "महंगाई से अधिक वृद्धि",
  "Sua vida financeira": "आपका वित्तीय जीवन",
  "em relatórios claros": "स्पष्ट रिपोर्टों में",
  "Relatório do mês atual": "वर्तमान महीने की रिपोर्ट",
  "Relatório dos últimos 3 meses": "पिछले 3 महीनों की रिपोर्ट",
  "Relatório dos últimos 6 meses": "पिछले 6 महीनों की रिपोर्ट",
  "Relatório anual": "वार्षिक रिपोर्ट",
  "Imprimir": "प्रिंट करें",
  "Compartilhar": "साझा करें",
  "Antes de compartilhar": "साझा करने से पहले",
  "Continuar": "जारी रखें",
  "Sem movimentação": "कोई गतिविधि नहीं",
  "Investimentos e crescimento real: Não avaliado":
      "निवेश और वास्तविक वृद्धि: मूल्यांकन नहीं हुआ",
  "Fechar": "बंद करें",
  "Nenhum compromisso neste dia.": "इस दिन कोई अपॉइंटमेंट नहीं है।",
  "Adicionar compromisso": "अपॉइंटमेंट जोड़ें",
  "Novo compromisso": "नया अपॉइंटमेंट",
  "Título *": "शीर्षक *",
  "Observação opcional": "वैकल्पिक नोट",
  "Recorrência": "पुनरावृत्ति",
  "Lembretes locais": "स्थानीय रिमाइंडर",
  "Informe o título do compromisso.": "अपॉइंटमेंट का शीर्षक दर्ज करें।",
  "Compromisso excluído.": "अपॉइंटमेंट हटाया गया।",
  "Compromissos\npessoais": "व्यक्तिगत\nअपॉइंटमेंट",
  "Serviços\nagendados": "निर्धारित\nसेवाएँ",
  "Compromissos\nprofissionais": "पेशेवर\nअपॉइंटमेंट",
  "Plano Básico": "बेसिक योजना",
  "Plano Plus": "प्लस योजना",
  "Plano Pro": "प्रो योजना",
  "Plano atual": "वर्तमान योजना",
  "Convidar": "आमंत्रित करें",
  "Convide um Amigo": "मित्र को आमंत्रित करें",
  "Escolha a clareza que acompanha seu momento":
      "अपने समय के अनुरूप स्पष्टता चुनें",
  "Oscar Clube": "ऑस्कर क्लब",
  "Parceria remunerada": "भुगतान की गई साझेदारी",
  "Ver benefício": "लाभ देखें",
  "Continuar para o parceiro": "साझेदार की ओर जारी रखें",
  "Nenhum benefício válido disponível para sua região neste momento.":
      "अभी आपके क्षेत्र के लिए कोई मान्य लाभ उपलब्ध नहीं है।",
  "Idioma, região e moeda": "भाषा, क्षेत्र और मुद्रा",
  "Idioma": "भाषा",
  "Moeda principal": "मुख्य मुद्रा",
  "Salvar alterações": "परिवर्तन सहेजें",
  "Configurações atualizadas": "सेटिंग्स अपडेट हुईं",
  "Aparência": "रूप",
  "Automático": "स्वचालित",
  "Claro": "हल्का",
  "Escuro": "गहरा",
  "Atualizar reserva de emergência": "आपातकालीन निधि अपडेट करें",
  "Reserva de emergência": "आपातकालीन निधि",
  "Cadastre despesas para visualizar a participação na renda.":
      "आय में खर्च का हिस्सा देखने के लिए खर्च जोड़ें।",
  "Origem dos ganhos": "आय के स्रोत",
  "Nenhum resultado local. O cadastro manual continua disponível.":
      "कोई स्थानीय परिणाम नहीं। मैन्युअल एंट्री अभी भी उपलब्ध है।",
  "Ela sairá da carteira, mas poderá ser restaurada por alguns segundos.":
      "यह पोर्टफोलियो से हटेगा, लेकिन कुछ सेकंड तक पुनःस्थापित किया जा सकेगा।",
  "Evolução patrimonial": "संपत्ति की वृद्धि",
  "1 ano": "1 वर्ष",
  "Todo período": "पूरी अवधि",
  "Patrimônio registrado": "दर्ज पोर्टफ़ोलियो मूल्य",
  "Câmbio indisponível: não é possível somar investimentos em moedas diferentes.": "विनिमय दरें उपलब्ध नहीं हैं; अलग-अलग मुद्राओं के निवेशों को जोड़ा नहीं जा सकता।",
  "Valorização acumulada": "संचित लाभ",
  "Somente rendimentos registrados; não inclui variação de mercado.":
      "केवल दर्ज प्रतिफल; बाज़ार मूल्य में बदलाव शामिल नहीं हैं।",
  "Nenhum investimento registrado neste período.":
      "इस अवधि में कोई निवेश दर्ज नहीं है।",
  "Ver valores mês a mês": "मासिक मूल्य देखें",
  "Aplicado + rendimento confirmado": "निवेशित राशि + पुष्टि किया गया रिटर्न",
  "Aportes e rendimentos registrados": "दर्ज निवेश और रिटर्न",
  "Total registrado": "दर्ज कुल राशि",
  "Variação no período": "इस अवधि में बदलाव",
  "Não inclui oscilações de mercado nem representa rentabilidade.": "इसमें बाज़ार मूल्य के उतार-चढ़ाव शामिल नहीं हैं और यह निवेश प्रतिफल नहीं है।",
  "Estimativa educacional. Não é promessa de rentabilidade nem recomendação.":
      "शैक्षिक अनुमान। यह रिटर्न का वादा या सलाह नहीं है।",
  "Estimativa baseada em uma cesta média; não representa sua inflação pessoal.":
      "औसत टोकरी पर आधारित अनुमान; यह आपकी व्यक्तिगत महंगाई नहीं दर्शाता।",
  "A alocação aparecerá quando você cadastrar uma posição.":
      "होल्डिंग जोड़ने के बाद आवंटन दिखेगा।",
  "Não foi possível gerar o relatório. Tente novamente.":
      "रिपोर्ट नहीं बन सकी। फिर कोशिश करें।",
  "Este documento contém informações financeiras pessoais. Compartilhe somente com pessoas de confiança.": "इस दस्तावेज़ में व्यक्तिगत वित्तीय जानकारी है। केवल विश्वसनीय लोगों के साथ साझा करें।",
  "O aplicativo agenda notificações locais. A entrega depende das permissões, economia de bateria, modo silencioso e políticas do aparelho.": "ऐप स्थानीय सूचनाएं निर्धारित करता है। वितरण अनुमति, बैटरी बचत, साइलेंट मोड और डिवाइस नीतियों पर निर्भर है।",
  "Todos os planos preservam seus dados e a navegação completa. Recursos avançados são explicados no ponto de uso.": "सभी प्लान आपका डेटा और पूरा नेविगेशन बनाए रखते हैं। उन्नत सुविधाएं उपयोग के स्थान पर समझाई जाती हैं।",
  "Toque em um plano para visualizar os recursos disponíveis.":
      "उपलब्ध सुविधाएं देखने के लिए किसी प्लान पर टैप करें।",
  "Uma indicação elegível pode oferecer até 40% de desconto. Benefícios não são cumulativos: prevalece sempre o maior desconto válido.": "योग्य रेफरल पर 40% तक छूट मिल सकती है। लाभ जोड़े नहीं जाते; सबसे बड़ी मान्य छूट लागू होती है।",
  "O convite seguro será habilitado quando contas e validação do servidor estiverem disponíveis.":
      "खाते और सर्वर सत्यापन उपलब्ध होने पर सुरक्षित आमंत्रण सक्रिय होंगे।",
  "Benefícios úteis e transparentes para apoiar sua educação, bem-estar e vida prática. Ofertas nunca alteram seu Oscar Score nem acessam seus dados financeiros.": "शिक्षा, कल्याण और दैनिक जीवन के लिए उपयोगी और पारदर्शी लाभ। ऑफर आपके Oscar Score को कभी नहीं बदलते और वित्तीय डेटा तक पहुंच नहीं रखते।",
  "O Oscar Finanças poderá receber uma comissão se você contratar ou comprar por este link. Você será direcionado ao ambiente do parceiro.": "इस लिंक से खरीदने पर Oscar Finanças को कमीशन मिल सकता है। आपको पार्टनर के पेज पर भेजा जाएगा।",
  "O link deste parceiro ainda não está disponível.":
      "इस पार्टनर का लिंक अभी उपलब्ध नहीं है।",
  "Região": "क्षेत्र",
  "Primeiro dia da semana": "सप्ताह का पहला दिन",
  "Ocultar valores ao abrir": "ऐप खुलने पर राशि छिपाएं",
  "As Telas 1, 2 e 3 começam protegidas.":
      "स्क्रीन 1, 2 और 3 सुरक्षित रूप से शुरू होती हैं।",
  "Ocultar valores ao sair": "बाहर जाने पर राशि छिपाएं",
  "Oculta os valores quando o aplicativo vai para segundo plano.":
      "ऐप के बैकग्राउंड में जाने पर राशि छिपाता है।",
  "Vibração e resposta tátil": "वाइब्रेशन और हैप्टिक फीडबैक",
  "Lembrete padrão para novos eventos": "नए इवेंट के लिए डिफ़ॉल्ट रिमाइंडर",
  "Cotações e indicadores": "दरें और संकेतक",
  "O último snapshot válido é usado offline. Atualizações indisponíveis aparecem como desatualizadas.": "अंतिम मान्य स्नैपशॉट ऑफ़लाइन उपयोग होता है। अनुपलब्ध अपडेट पुराने के रूप में दिखाई देते हैं।",
  "O Oscar Finanças não se conecta a contas bancárias nem movimenta dinheiro. Informações, simulações e projeções têm caráter informativo e usam dados fornecidos por você e referências de mercado atualizadas. Cotações podem apresentar atrasos ou diferenças em relação ao mercado.": "Oscar Finanças बैंक खातों से नहीं जुड़ता और पैसे का लेन-देन नहीं करता। जानकारी, सिमुलेशन और अनुमान केवल सूचनात्मक हैं तथा आपके डेटा और अपडेट किए गए बाज़ार संदर्भों का उपयोग करते हैं। बाज़ार भाव में देरी या अंतर हो सकता है।",
  "Atualização oficial disponível após configurar os provedores.":
      "प्रदाता कॉन्फ़िगर होने के बाद आधिकारिक अपडेट उपलब्ध होंगे।",
  "Atualizar agora": "अभी अपडेट करें",
  "Disponível em {tempo}": "{tempo} में उपलब्ध",
  "Oscar Finanças — Clareza que transforma escolhas em patrimônio.":
      "Oscar Finanças — स्पष्टता जो चुनावों को संपत्ति में बदलती है।",
  "Organiza receitas, despesas, ganhos extras, saúde financeira, relatórios, agenda e investimentos sem movimentar seu dinheiro nem oferecer recomendação individual.": "आपके पैसे को हिलाए बिना या व्यक्तिगत सलाह दिए बिना आय, खर्च, अतिरिक्त कमाई, वित्तीय स्वास्थ्य, रिपोर्ट, कैलेंडर और निवेश को व्यवस्थित करता है।",
  "Saldo atual": "वर्तमान शेष",
  "Aporte deste mês": "इस महीने का योगदान",
  "O aporte será incluído na lista de gastos do mês.":
      "योगदान इस महीने की खर्च सूची में शामिल होगा।",
  "Tipo de aporte": "योगदान का प्रकार",
  "Aporte único": "एकमुश्त योगदान",
  "Mensal fixo": "निश्चित मासिक",
  "Variável ou intermitente": "परिवर्तनशील या रुक-रुक कर",
  "Meta de cobertura": "कवरेज लक्ष्य",
  "Salário simulado": "उदाहरण वेतन",
  "Aluguel simulado": "उदाहरण किराया",
  "Luz simulada": "उदाहरण बिजली",
  "Água simulada": "उदाहरण पानी",
  "Internet simulada": "उदाहरण इंटरनेट",
  "Mercado simulado": "उदाहरण किराना",
  "Reserva de emergência simulada": "उदाहरण आपातकालीन निधि",
  "Faculdade simulada": "उदाहरण कॉलेज शुल्क",
  "Carro simulado": "उदाहरण कार",
  "TV simulada": "उदाहरण टीवी",
  "Freelance de design simulado": "उदाहरण डिज़ाइन फ्रीलांस",
  "Serviço freelance": "फ्रीलांस सेवा",
  "Projeto ou atendimento do mês": "इस महीने की परियोजना या सेवा",
  "Projeto pontual simulado": "उदाहरण एकमुश्त परियोजना",
  "Manutenção de computador simulada": "उदाहरण कंप्यूटर रखरखाव",
  "Serviço técnico simulado": "उदाहरण तकनीकी सेवा",
  "Venda de bicicleta simulada": "उदाहरण साइकिल बिक्री",
  "Venda ocasional simulada": "उदाहरण आकस्मिक बिक्री",
  "Venda ocasional": "कभी-कभार की बिक्री",
  "Venda de item ou produto": "वस्तु या उत्पाद की बिक्री",
  "Venda de doces simulada": "उदाहरण मिठाई बिक्री",
  "Renda complementar simulada": "उदाहरण अतिरिक्त आय",
  "Tesouro Selic simulado": "उदाहरण सरकारी बॉन्ड",
  "CDB simulado": "उदाहरण बैंक निवेश",
  "Fundo imobiliário simulado": "उदाहरण रियल एस्टेट फंड",
  "Ação simulada": "उदाहरण शेयर",
  "Versão 0.1.0 · compilação 1": "संस्करण 0.1.0 · बिल्ड 1",
  "Organização financeira essencial, sem custo.":
      "आवश्यक वित्तीय व्यवस्था, निःशुल्क।",
  "Painel Financeiro completo, Reserva de Emergência e Oscar Score":
      "पूरा वित्तीय डैशबोर्ड, आपातकालीन निधि और Oscar Score",
  "Relatório mensal com impressão e compartilhamento":
      "प्रिंट और साझा करने के साथ मासिक रिपोर्ट",
  "Agenda completa com recorrência e lembretes locais":
      "दोहराव और स्थानीय रिमाइंडर वाला पूरा कैलेंडर",
  "Oscar Clube e Configurações": "Oscar Club और सेटिंग्स",
  "Grátis": "निःशुल्क",
  "Mais controle para quem transforma trabalho em renda.":
      "काम को आय में बदलने वालों के लिए अधिक नियंत्रण।",
  "Tudo do Plano Básico": "बेसिक प्लान की सभी सुविधाएं",
  "Ganho Extra completo: Serviços, Vendas e recorrências":
      "पूरी अतिरिक्त आय: सेवाएं, बिक्री और दोहराव",
  "Integração Agenda → Ganho Extra": "कैलेंडर → अतिरिक्त आय एकीकरण",
  "Relatórios do mês e dos últimos 3 meses":
      "महीने और पिछले 3 महीनों की रिपोर्ट",
  "Visão patrimonial completa, simples e internacional.":
      "संपत्ति का पूरा, सरल और अंतरराष्ट्रीय दृश्य।",
  "Tudo do Plano Plus": "प्लस प्लान की सभी सुविधाएं",
  "Investimentos, busca internacional, ações, ETFs e calculadora":
      "निवेश, अंतरराष्ट्रीय खोज, शेयर, ETF और कैलकुलेटर",
  "Crescimento real e resumo em BRL, USD, EUR e INR":
      "BRL, USD, EUR और INR में वास्तविक वृद्धि और सारांश",
  "Relatórios de 1, 3, 6 e 12 meses": "1, 3, 6 और 12 महीनों की रिपोर्ट",
  "Educação e Carreira": "शिक्षा और करियर",
  "Cursos, idiomas, livros, certificações e ferramentas profissionais.":
      "कोर्स, भाषाएं, किताबें, प्रमाणपत्र और पेशेवर उपकरण।",
  "Saúde, Beleza e Bem-estar": "स्वास्थ्य, सौंदर्य और कल्याण",
  "Viagens e Experiências": "यात्रा और अनुभव",
  "Tecnologia e Vida Prática": "प्रौद्योगिकी और दैनिक जीवन",
  "Notificações": "सूचनाएं",
  "Dados econômicos e câmbio": "आर्थिक डेटा और विनिमय",
  "Transparência e metodologia": "पारदर्शिता और पद्धति",
  "Sobre o aplicativo": "ऐप के बारे में",
  "Estados Unidos": "संयुक्त राज्य अमेरिका",
  "Alemanha": "जर्मनी",
  "França": "फ़्रांस",
  "Índia": "भारत",
  "No horário": "निर्धारित समय पर",
  "1 dia antes e no horário": "1 दिन पहले और निर्धारित समय पर",
  "3 dias antes, 1 dia antes e no horário":
      "3 दिन पहले, 1 दिन पहले और निर्धारित समय पर",
  "Termos de Uso": "उपयोग की शर्तें",
  "Política de Privacidade": "गोपनीयता नीति",
  "Consentimento e tratamento de dados financeiros":
      "सहमति और वित्तीय डेटा प्रसंस्करण",
  "Política de Anúncios": "विज्ञापन नीति",
  "Política de Parcerias e Benefícios": "भागीदारी और लाभ नीति",
  "Privacidade Internacional": "अंतरराष्ट्रीय गोपनीयता",
  "Exclusão de dados": "डेटा हटाना",
  "Aviso financeiro": "वित्तीय सूचना",
  "Metodologia do Oscar Score": "Oscar Score पद्धति",
  "Licenças e bibliotecas": "लाइसेंस और लाइब्रेरी",
  "O Oscar Finanças organiza informações fornecidas pelo usuário. Os cálculos e projeções são educacionais, podem conter limitações e não constituem consultoria financeira. O usuário é responsável pela exatidão dos dados cadastrados e pelo uso dos relatórios.": "Oscar Finanças उपयोगकर्ता द्वारा दी गई जानकारी को व्यवस्थित करता है। गणना और अनुमान शैक्षिक हैं, उनकी सीमाएं हो सकती हैं और वे वित्तीय सलाह नहीं हैं। डेटा की शुद्धता और रिपोर्ट के उपयोग की ज़िम्मेदारी उपयोगकर्ता की है।",
  "Dados financeiros permanecem no aparelho nesta versão. Serviços públicos de câmbio e indicadores não recebem valores da carteira. Recursos externos devem declarar finalidade, retenção e fundamento legal antes da publicação.": "इस संस्करण में वित्तीय डेटा डिवाइस पर रहता है। सार्वजनिक विनिमय और संकेतक सेवाओं को पोर्टफोलियो मूल्य नहीं मिलते। बाहरी सेवाओं को रिलीज़ से पहले उद्देश्य, संग्रह और कानूनी आधार बताना होगा।",
  "O aplicativo aplica minimização, finalidade e controle do usuário. LGPD, GDPR e normas regionais serão observadas de acordo com o país de disponibilização.": "ऐप डेटा न्यूनतमीकरण, उद्देश्य सीमा और उपयोगकर्ता नियंत्रण लागू करता है। रिलीज़ देश के अनुसार LGPD, GDPR और क्षेत्रीय नियमों का पालन होगा।",
  "Espaços publicitários futuros usarão um módulo isolado. Personalização dependerá de consentimento aplicável e nenhum anúncio receberá receitas, despesas, agenda, relatório ou carteira.": "भविष्य के विज्ञापन स्थान अलग मॉड्यूल का उपयोग करेंगे। व्यक्तिकरण के लिए लागू सहमति चाहिए और विज्ञापन को आय, खर्च, कैलेंडर, रिपोर्ट या पोर्टफोलियो डेटा कभी नहीं मिलेगा।",
  "O aplicativo não executa investimentos, não oferece custódia e não recomenda compra ou venda. Câmbio, inflação e rentabilidade podem variar; desempenho passado não garante resultado futuro.": "ऐप निवेश निष्पादित नहीं करता, कस्टडी नहीं देता और खरीदने या बेचने की सलाह नहीं देता। विनिमय, महंगाई और रिटर्न बदल सकते हैं; पिछला प्रदर्शन भविष्य के परिणाम की गारंटी नहीं है।",
  "O Oscar Score resume a sobra mensal em relação à renda bruta. Ele considera entradas confirmadas, despesas e déficit. Não é score de crédito e não determina acesso a produtos.": "Oscar Score सकल आय के सापेक्ष मासिक शेष का सार देता है। यह पुष्ट आय, खर्च और घाटे को देखता है। यह क्रेडिट स्कोर नहीं है और उत्पाद पहुंच निर्धारित नहीं करता।",
  "O crescimento real estimado subtrai do rendimento nominal um efeito inflacionário baseado em índice oficial médio. Esse índice não representa a inflação pessoal de cada usuário.": "अनुमानित वास्तविक वृद्धि नाममात्र रिटर्न से औसत आधिकारिक सूचकांक पर आधारित महंगाई प्रभाव घटाती है। यह सूचकांक व्यक्तिगत महंगाई नहीं दिखाता।",
  "Construído com Flutter e bibliotecas revisadas para gráficos, banco local, PDF, impressão e notificações. A relação final de licenças será gerada para a versão publicada.": "Flutter और चार्ट, स्थानीय स्टोरेज, PDF, प्रिंटिंग और सूचनाओं के लिए समीक्षित लाइब्रेरी से बना। प्रकाशित संस्करण के लिए अंतिम लाइसेंस सूची बनेगी।",
  "Cuidados pessoais, academias, exames e soluções de bem-estar.":
      "व्यक्तिगत देखभाल, जिम, जांच और कल्याण समाधान।",
  "Hospedagem, cultura, gastronomia, passeios e serviços relacionados.":
      "आवास, संस्कृति, भोजन, भ्रमण और संबंधित सेवाएं।",
  "Lançamentos recorrentes": "आवर्ती प्रविष्टियां",
  "Relatório mensal disponível": "मासिक रिपोर्ट उपलब्ध",
  "O Oscar Finanças poderá receber comissão por links identificados. A transparência aparece antes da saída; critérios comerciais não alteram Oscar Score, relatórios ou cálculos.": "Oscar Finanças को चिह्नित लिंक से कमीशन मिल सकता है। ऐप से बाहर जाने से पहले यह स्पष्ट किया जाता है; वाणिज्यिक मानदंड Oscar Score, रिपोर्ट या गणना नहीं बदलते।",
  "Idioma, região e moeda são independentes. Transferências internacionais, quando existirem, deverão informar destino, proteção e direitos aplicáveis.": "भाषा, क्षेत्र और मुद्रा स्वतंत्र हैं। भविष्य के अंतरराष्ट्रीय हस्तांतरण को गंतव्य, सुरक्षा और लागू अधिकार बताने होंगे।",
  "A exclusão local exige confirmação forte e não deve ocorrer parcialmente. Exclusão de conta só será exibida quando contas e sincronização reais estiverem implementadas.": "स्थानीय डेटा हटाने के लिए मज़बूत पुष्टि चाहिए और यह आंशिक नहीं होना चाहिए। वास्तविक खाते और सिंक्रनाइज़ेशन लागू होने पर ही खाता हटाने का विकल्प दिखेगा।",
  "Ativos relacionados": "संबंधित परिसंपत्तियाँ",
  "Deslize para ver mais": "और देखने के लिए स्वाइप करें",
  "Dados simulados": "अनुमानित डेटा",
  "Aguardando cotação": "भाव की प्रतीक्षा",
  "Cotação atualizada": "भाव अपडेट हुआ",
  "Última cotação salva": "अंतिम सहेजा गया भाव",
  "Privacidade dos valores": "राशियों की गोपनीयता",
  "Lembretes da Agenda": "कैलेंडर रिमाइंडर",
  "Fechamento mensal": "मासिक समापन",
  "Plano e assinatura": "योजना और सदस्यता",
  "Domingo": "रविवार",
  "Segunda-feira": "सोमवार",
  "Escolher": "चुनें",
  "por mês": "प्रति माह",
  "mês": "माह",
  "por ano": "प्रति वर्ष",
  "equivalente a": "के बराबर",
  "economize": "बचाएं",
  "Serviços do mês": "इस महीने की सेवाएं",
  "Vendas do mês": "इस महीने की बिक्री",
  "Adicionar serviço": "सेवा जोड़ें",
  "Adicionar venda": "बिक्री जोड़ें",
  "Somado à Tela 1": "स्क्रीन 1 में शामिल",
  "Nenhuma entrada neste mês.": "इस महीने कोई आय नहीं।",
  "Sem movimentações para exibir": "दिखाने के लिए कोई गतिविधि नहीं",
  "Nenhum gasto neste mês.": "इस महीने कोई खर्च नहीं।",
  "Nenhuma parcela neste mês.": "इस महीने कोई किस्त नहीं।",
  "Adicionar entrada": "आय जोड़ें",
  "Adicionar gasto": "खर्च जोड़ें",
  "Adicionar parcela": "किस्त जोड़ें",
  "Sobra": "शेष",
  "Déficit": "घाटा",
  "Não calculado": "गणना नहीं हुई",
  "Não avaliado": "मूल्यांकन नहीं हुआ",
  "Não avaliada": "मूल्यांकन नहीं हुआ",
  "Cadastre uma entrada para calcular seu Oscar Score.":
      "अपना Oscar Score जानने के लिए आय दर्ज करें।",
  "Cadastre gastos para calcular a cobertura":
      "कवरेज की गणना के लिए खर्च जोड़ें",
  "Valor do desconto": "छूट की राशि",
  "Títulos públicos": "सरकारी बॉन्ड",
  "Renda fixa bancária": "बैंक निश्चित आय",
  "Títulos empresariais": "कॉर्पोरेट बॉन्ड",
  "Ações": "शेयर",
  "Cadastro manual": "मैनुअल प्रविष्टि",
  "Cotações indisponíveis": "दरें उपलब्ध नहीं",
  "Cotações atualizadas com sucesso.": "दरें सफलतापूर्वक अपडेट हुईं।",
  "Não foi possível atualizar as cotações.": "दरें अपडेट नहीं हो सकीं।",
  "Sem conexão. O último valor disponível foi mantido.":
      "ऑफ़लाइन। अंतिम उपलब्ध मूल्य रखा गया।",
  "Cotações demonstrativas desatualizadas · dados reais serão atualizados por adaptador seguro":
      "पुरानी नमूना दरें · वास्तविक डेटा सुरक्षित रूप से अपडेट होगा",
  "Cotações atualizadas · fonte de mercado": "दरें अपडेट हुईं · बाजार स्रोत",
  "Aviso educacional financeiro": "वित्तीय शिक्षा सूचना",
  "Como funciona o Oscar Score": "Oscar Score कैसे काम करता है",
  "Dispositivos, software, conectividade, casa, estudo e trabalho.":
      "डिवाइस, सॉफ्टवेयर, कनेक्टिविटी, घर, पढ़ाई और काम।",
  "DOM": "रवि",
  "SEG": "सोम",
  "TER": "मंगल",
  "QUA": "बुध",
  "QUI": "गुरु",
  "SEX": "शुक्र",
  "SÁB": "शनि",
  "Aplicado: {value}": "निवेशित: {value}",
  "Rendimento: {value}": "प्रतिफल: {value}",
  "Rendeu no mês: {value}": "मासिक प्रतिफल: {value}",
  "Efeito estimado da inflação: {value}":
      "अनुमानित मुद्रास्फीति प्रभाव: {value}",
  "Crescimento real estimado: {value}": "अनुमानित वास्तविक वृद्धि: {value}",
  "Patrimônio estimado: {value}": "अनुमानित संपत्ति: {value}",
  "Valor inicial ({currency})": "प्रारंभिक राशि ({currency})",
  "Saldo atual: {value}": "वर्तमान शेष: {value}",
  "{value} guardados": "{value} सुरक्षित",
  "Cobre aproximadamente {value} meses": "लगभग {value} महीनों के लिए पर्याप्त",
  "Meta: {months} meses · {percent}%": "लक्ष्य: {months} महीने · {percent}%",
  "Meta: {months} meses": "लक्ष्य: {months} महीने",
  "meses de cobertura": "महीनों का खर्च",
  "da meta": "लक्ष्य का",
  "Ajustar meta": "लक्ष्य बदलें",
  "O aporte deve ser maior que zero.": "योगदान शून्य से अधिक होना चाहिए।",
  "Fluxo do mês: {value}/100": "मासिक प्रवाह: {value}/100",
  "Reserva: {value} meses": "आपातकालीन निधि: {value} महीने",
  "Reserva de Emergência: {value} meses": "आपातकालीन निधि: {value} महीने",
  "{name} · {amount} será removido deste mês.":
      "{name} · {amount} इस महीने से हटा दिया जाएगा।",
  "{name} será removido de {month}.": "{name} को {month} से हटा दिया जाएगा।",
  "Cadastrar “{name}” manualmente": "“{name}” को मैन्युअल रूप से जोड़ें",
  "Serviços · {value}%": "सेवाएँ · {value}%",
  "Vendas · {value}%": "बिक्री · {value}%",
  "Horário · {time}": "समय · {time}",
  "Escolher {plan}": "{plan} चुनें",
  "Este período está disponível no Plano {plan}.":
      "यह अवधि {plan} योजना में उपलब्ध है।",
  "Relatório · {count} folha": "रिपोर्ट · {count} पृष्ठ",
  "Relatório · {count} folhas": "रिपोर्ट · {count} पृष्ठ",
  "Competência {month} · Página {page} de {total}":
      "अवधि {month} · पृष्ठ {page}, कुल {total}",
  "Criptomoedas": "क्रिप्टोकरेंसी",
  "Quantidade": "मात्रा",
  "Informe uma quantidade válida.": "मान्य मात्रा दर्ज करें।",
  "Histórico em formação": "इतिहास तैयार हो रहा है",
  "Variação em 24 horas": "24 घंटे का बदलाव",
  "O convite de amigos está indisponível nesta versão.":
      "इस संस्करण में मित्रों को आमंत्रित करना उपलब्ध नहीं है।",
  "Receba 30% de desconto quando um amigo indicado se cadastrar e contratar um plano anual. Assinaturas mensais não participam. Descontos não se acumulam: vale o maior desconto elegível.": "जब आपके आमंत्रण पर कोई मित्र पंजीकरण करके वार्षिक योजना खरीदे, तो 30% छूट पाएँ। मासिक सदस्यताएँ पात्र नहीं हैं। छूट जोड़ी नहीं जातीं; सबसे बड़ी पात्र छूट लागू होती है।",
  "Carteira de criptomoedas com cotações CoinMarketCap":
      "CoinMarketCap भावों के साथ क्रिप्टो पोर्टफोलियो",
  "entry.welcome": "स्पष्टता, गोपनीयता और उद्देश्य के साथ आपका वित्तीय जीवन।",
  "entry.google": "Google से प्रवेश करें",
  "entry.apple": "Apple से प्रवेश करें",
  "entry.guest": "बिना खाते के जारी रखें",
  "entry.disclaimer": "आपका वित्तीय डेटा इसी डिवाइस पर रहता है।",
  "drawer.close": "मेनू बंद करें",
  "privacy.hide": "राशियाँ छिपाएँ",
  "privacy.show": "राशियाँ दिखाएँ",
  "month.previous": "पिछला महीना",
  "month.next": "अगला महीना",
  "screen.financial": "वित्तीय डैशबोर्ड",
  "screen.extraIncome": "अतिरिक्त आय",
  "screen.investments": "निवेश",
  "screen.objectives": "लक्ष्य",
  "screen.reports": "सामान्य रिपोर्ट",
  "screen.agenda": "कार्यसूची",
  "screen.calculator": "कैलकुलेटर",
  "screen.plans": "योजनाएँ",
  "screen.club": "ऑस्कर क्लब",
  "screen.settings": "सेटिंग्स",
  "objectives.subtitle": "अपने लक्ष्यों की प्रगति देखें",
  "Objetivos financeiros com evolução mês a mês":
      "महीने-दर-महीने प्रगति वाले वित्तीय लक्ष्य",
  "objectives.new": "नया लक्ष्य",
  "objectives.emptyTitle": "आपके लक्ष्य यहाँ से शुरू होते हैं",
  "objectives.emptyBody": "समय के साथ जमा और प्रगति देखने के लिए लक्ष्य बनाएँ।",
  "objectives.loadFailed": "आपके लक्ष्य लोड नहीं हो सके।",
  "objectives.retry": "फिर से कोशिश करें",
  "objectives.name": "लक्ष्य का नाम",
  "objectives.nameRequired": "लक्ष्य का नाम दर्ज करें।",
  "objectives.targetPeriod": "लक्ष्य की अवधि",
  "objectives.threeMonths": "3 महीने",
  "objectives.sixMonths": "6 महीने",
  "objectives.oneYear": "1 वर्ष",
  "objectives.fiveYears": "5 वर्ष",
  "objectives.tenYears": "10 वर्ष",
  "objectives.monthCount": "{count} महीने",
  "objectives.targetAmount": "लक्ष्य राशि",
  "objectives.targetRequired": "शून्य से अधिक राशि दर्ज करें।",
  "objectives.initialBalance": "पहले से बचाई गई राशि",
  "objectives.initialBalanceHelp": "नई जमा राशि से पहले अलग रखी गई मौजूदा रकम।",
  "objectives.contribution": "जमा",
  "objectives.addContribution": "जमा राशि जोड़ें",
  "objectives.contributionAmount": "जमा राशि",
  "objectives.saveContribution": "जमा राशि सहेजें",
  "objectives.contributionSaved":
      "लक्ष्य में जमा जोड़ी गई और खर्च में दर्ज की गई।",
  "objectives.exchangeUnavailable":
      "विनिमय दर उपलब्ध नहीं है; इस जमा राशि को परिवर्तित नहीं किया जा सका।",
  "Saldo reservado": "बचाई गई राशि",
  "Aportes acumulados": "कुल जमा",
  "Meta": "लक्ष्य",
  "Acompanhe sua meta na tela Objetivos":
      "अपनी आपातकालीन निधि की शेष राशि, जमा और प्रगति देखें",
  "Aporte · {name}": "जमा · {name}",
  "objectives.annualRate": "वार्षिक दर",
  "objectives.compoundInterest": "वार्षिक चक्रवृद्धि ब्याज",
  "objectives.annualRateShort": "वार्षिक दर",
  "objectives.lowerRate": "दर घटाएँ",
  "objectives.raiseRate": "दर बढ़ाएँ",
  "objectives.annualRateHelp": "अनुमान के लिए दर दर्ज करें या 0% रहने दें।",
  "objectives.rateTooHigh": "0% से 100% वार्षिक दर दर्ज करें।",
  "objectives.frequency": "जमा की आवृत्ति",
  "objectives.oneTime": "एक बार",
  "objectives.monthly": "हर महीने",
  "objectives.projectionDisclosure": "यह दर अनुमान देती है, लाइव भाव नहीं। इस महीने की जमा राशि खर्च में “जमा · लक्ष्य” के रूप में भी दिखेगी।",
  "objectives.create": "लक्ष्य बनाएँ",
  "objectives.cancel": "रद्द करें",
  "objectives.created": "लक्ष्य बनाया गया।",
  "objectives.goalActions": "लक्ष्य के विकल्प",
  "objectives.delete": "हटाएँ",
  "objectives.deleteTitle": "यह लक्ष्य हटाएँ?",
  "objectives.deleteBody": "लक्ष्य और उसकी प्रगति इस स्क्रीन से हट जाएगी। खर्च में जमा की प्रविष्टियाँ बनी रहेंगी।",
  "objectives.currentBalance": "इस महीने का अनुमानित बैलेंस",
  "objectives.contributions": "कुल जमा",
  "objectives.estimatedYield": "अनुमानित रिटर्न",
  "objectives.returnLabel": "रिटर्न",
  "objectives.progressSemantics": "लक्ष्य की प्रगति: {percent}%",
  "objectives.target": "लक्ष्य: {months} · {amount}",
  "objectives.percentComplete": "{percent}% पूरा",
  "objectives.importedHistory": "जमा का इतिहास खर्च से आयात किया गया। किसी रिटर्न का अनुमान नहीं जोड़ा गया।",
  "objectives.viewEvolution": "मासिक प्रगति",
  "objectives.chartDescription": "लक्ष्य बैलेंस की मासिक प्रगति का ग्राफ",
  "objectives.monthlyEvolution": "महीने-दर-महीने प्रगति",
  "objectives.estimatedYieldShort": "अनुमानित रिटर्न",
  "objectives.actualYieldShort": "रिटर्न",
  "objectives.closingBalance": "अंतिम बैलेंस",
  "objectives.projectionFootnote": "दर्ज वार्षिक दर ({rate}% प्रति वर्ष) पर आधारित अनुमान। लाइव भाव नहीं; वास्तविक बैलेंस अपने निवेश प्रदाता से जाँचें।",
  "foundation.ready": "अगले चरण के लिए संरचना तैयार है",
  "Brasil": "ब्राज़ील",
  "Clareza que transforma escolhas em patrimônio":
      "स्पष्टता जो विकल्पों को संपत्ति में बदलती है",
  "Fluxo do mês: Não calculado": "मासिक प्रवाह: गणना नहीं हुई",
  "Reserva: Não avaliada": "आपातकालीन निधि: मूल्यांकन नहीं हुआ",
  "Oscar Score: Não calculado": "Oscar Score: गणना नहीं हुई",
  "Reserva de Emergência: Não avaliada": "आपातकालीन निधि: मूल्यांकन नहीं हुआ",
  "Indisponível": "अनुपलब्ध",
  "home.block.financial": "वित्तीय डैशबोर्ड",
  "home.block.extraIncome": "अतिरिक्त आय",
  "home.block.investments": "निवेश",
  "home.block.emergencyFund": "आपातकालीन निधि",
  "home.block.objectives": "लक्ष्य",
  "Acompanhe o progresso das suas metas": "अपने लक्ष्यों की प्रगति देखें",
  "Saldo dos objetivos": "लक्ष्यों की शेष राशि",
  "Total acumulado": "कुल जमा राशि",
  "Meta total": "कुल लक्ष्य",
  "Últimas cotações salvas · atualização automática":
      "अंतिम सहेजी गई दरें · स्वचालित अपडेट",
  "Últimas cotações salvas · atualização automática indisponível":
      "अंतिम सहेजी गई दरें · स्वचालित अपडेट अनुपलब्ध",
  "legal.privacy.body": "Oscar Finanças आपके द्वारा दर्ज की गई राशियों, विवरणों, निवेशों और अपॉइंटमेंट का उपयोग वित्त व्यवस्थित करने के लिए करता है। इंस्टॉल किए गए ऐप में ये रिकॉर्ड डिवाइस पर रहते हैं; वेब संस्करण में वे इसी ब्राउज़र में स्थानीय रूप से सहेजे जाते हैं और पेज दोबारा लोड करने के बाद भी उपलब्ध रहते हैं। प्राथमिकताएँ भी स्थानीय रूप से सहेजी जाती हैं।\n\nभावों के लिए AwesomeAPI, HG Brasil, Alpha Vantage और CoinMarketCap का उपयोग होता है। अनुरोधों में मुद्रा और संपत्ति पहचानकर्ता जाते हैं; मात्रा, शेष, निवेशित राशि, विवरण या अपॉइंटमेंट नहीं जाते। कनेक्शन से जुड़े सेवाप्रदाता आईपी पता और तकनीकी मेटाडेटा प्राप्त कर सकते हैं।\n\nरिपोर्ट तभी अन्य ऐप या प्राप्तकर्ता को भेजी जाती है जब आप प्रिंट या साझा करना चुनते हैं। हम वित्तीय डेटा नहीं बेचते। इस संस्करण में दूरस्थ खाते के साथ सिंक्रनाइज़ेशन, विज्ञापन या व्यवहार विश्लेषण एसडीके नहीं है।\n\nआप रिकॉर्ड संपादित और हटा सकते हैं। हटाना पूर्ववत किया जा सकता है और हटाए गए चिह्न वाले स्थानीय रिकॉर्ड बने रह सकते हैं। वेब डेटा इसी ब्राउज़र में तब तक रहेगा जब तक आप उसे ऐप में हटाएँ या ब्राउज़र सेटिंग में इस साइट का डेटा साफ़ न करें। इंस्टॉल किए गए ऐप की पूरी स्थानीय डेटाबेस मिटाने के लिए सिस्टम सेटिंग में ऐप डेटा साफ़ करें। निर्यात की गई फ़ाइलें और बाहरी प्रतियाँ अलग से हटानी होंगी।",
  "legal.ads.body": "इस संस्करण में विज्ञापन नहीं दिखाए जाते और AdMob एसडीके शामिल नहीं है। वित्तीय रिकॉर्ड विज्ञापन लक्ष्यीकरण के लिए इस्तेमाल नहीं होते। विज्ञापन उपलब्ध होने पर सक्रिय करने से पहले यह नीति और गोपनीयता नियंत्रण अपडेट किए जाएँगे। जहाँ आवश्यक हो, विज्ञापन अनुरोधों से पहले गोपनीयता विकल्पों में सहमति चुनना और बदलना संभव होगा।",
  "legal.permissions.body": "अनुस्मारक स्थानीय सूचनाओं का उपयोग करते हैं और आवश्यकता होने पर सिस्टम की अनुमति लेते हैं। आप डिवाइस सेटिंग में अनुमति वापस ले सकते हैं। वित्त व्यवस्थित करने के लिए ऐप को संपर्क, सटीक स्थान, कैमरा या माइक्रोफ़ोन की आवश्यकता नहीं है। अनुमति न मिलने पर अनुस्मारक रुक सकते हैं, लेकिन वित्तीय प्रविष्टियाँ नहीं रुकतीं।",
  "Permissões e notificações": "अनुमतियाँ और सूचनाएँ",
  "legal.terms.body": "Oscar Finanças आपकी प्रविष्टियों से वित्त व्यवस्थित करता है और शैक्षिक गणनाएँ प्रदान करता है। यह पैसे नहीं भेजता, व्यापार आदेश नहीं चलाता, क्रिप्टोकरेंसी की अभिरक्षा नहीं करता और व्यक्तिगत निवेश सलाह नहीं देता। भाव देर से या अनुपलब्ध हो सकते हैं। बाजार मूल्य वास्तविक प्राप्त आय नहीं है।\n\nरिकॉर्ड जाँचना और डिवाइस तथा निर्यात की गई रिपोर्टों की पहुँच सुरक्षित रखना आपकी जिम्मेदारी है। अनुमान परिणामों की गारंटी नहीं हैं। इस संस्करण का मुद्रास्फीति अनुमान स्थानीय संदर्भ दर का उपयोग करता है और आपकी व्यक्तिगत मुद्रास्फीति नहीं दर्शाता। इस संस्करण में सदस्यता खरीद और मित्र आमंत्रण उपलब्ध नहीं हैं; योजना बटन कोई शुल्क नहीं लगाते।",
  "report.tagline": "स्पष्टता जो चुनावों को संपत्ति में बदलती है",
  "report.report": "वित्तीय रिपोर्ट",
  "Relatório financeiro": "वित्तीय रिपोर्ट",
  "report.personal": "व्यक्तिगत दस्तावेज़",
  "Documento pessoal": "व्यक्तिगत दस्तावेज़",
  "report.currency": "आधार मुद्रा",
  "moeda base": "आधार मुद्रा",
  "report.generated": "बनाया गया",
  "gerado em": "बनाया गया",
  "report.noMovement": "कोई लेनदेन नहीं",
  "report.mainIncome": "मुख्य आय",
  "Renda principal": "मुख्य आय",
  "report.extra": "पुष्ट अतिरिक्त आय",
  "Ganho Extra confirmado": "पुष्ट अतिरिक्त आय",
  "report.total": "कुल आय",
  "Entradas totais": "कुल आय",
  "report.expenses": "खर्च",
  "Despesas": "खर्च",
  "report.installments": "किस्तें",
  "Parcelas": "किस्तें",
  "report.balance": "उपलब्ध शेष",
  "Sobra disponível": "उपलब्ध शेष",
  "report.deficit": "घाटा",
  "report.health": "वित्तीय स्वास्थ्य",
  "Saúde financeira": "वित्तीय स्वास्थ्य",
  "report.notCalculated": "गणना नहीं हुई",
  "report.fund": "आपातकालीन निधि",
  "report.notEvaluated": "मूल्यांकन नहीं हुआ",
  "report.months": "महीने",
  "meses": "महीने",
  "report.mainExpenses": "दर्ज किए गए खर्च",
  "Principais gastos": "मुख्य खर्च",
  "report.noExpenses": "कोई खर्च दर्ज नहीं।",
  "Nenhum gasto cadastrado.": "कोई खर्च दर्ज नहीं।",
  "report.extraDetails": "अतिरिक्त आय का विवरण",
  "report.noExtraIncome": "कोई अतिरिक्त आय दर्ज नहीं।",
  "report.printUnavailable":
      "प्रिंट विंडो नहीं खुल सकी। PDF डाउनलोड करने के लिए साझा करें चुनें।",
  "report.printFallback": "प्रिंट विंडो नहीं खुली; PDF डाउनलोड कर दी गई है, अब इसे अपने व्यूअर से प्रिंट करें।",
  "report.investments": "निवेश और वास्तविक वृद्धि",
  "Investimentos e crescimento real": "निवेश और वास्तविक वृद्धि",
  "report.page": "पृष्ठ",
  "Página": "पृष्ठ",
  "report.of": "में से",
  "de": "में से",
  "report.critical": "गंभीर चेतावनी",
  "Alerta Crítico": "गंभीर चेतावनी",
  "report.attention": "ध्यान / तंग",
  "Atenção / Apertado": "ध्यान / तंग",
  "report.balanced": "संतुलित",
  "Equilibrado": "संतुलित",
  "report.healthy": "स्वस्थ",
  "Saudável": "स्वस्थ",
  "report.prosperous": "समृद्ध",
  "Próspero": "समृद्ध",
  "Parcela {current} de {total}": "{total} में से किस्त {current}",
  "Atenção": "ध्यान दें",
  "Alerta crítico": "गंभीर चेतावनी",
  "{date}, {count} compromissos": "{date}, {count} अपॉइंटमेंट",
  "Oscar Score, {score} de 100, {level}":
      "Oscar Score, 100 में से {score}, {level}",
  "Oscar Score não calculado. Cadastre uma entrada.":
      "Oscar Score की गणना नहीं हुई। आय जोड़ें।",
  "Painel financeiro, valores ocultos": "वित्तीय डैशबोर्ड, राशियाँ छिपी हैं",
  "Painel Financeiro": "वित्तीय डैशबोर्ड",
  "O mês pede proteção. Reveja os maiores compromissos.":
      "इस महीने सावधानी ज़रूरी है। अपने सबसे बड़े खर्चों की समीक्षा करें।",
  "Há pouco espaço de manobra. Pequenos ajustes podem abrir fôlego.":
      "गुंजाइश कम है। छोटे बदलाव राहत दे सकते हैं।",
  "Sua estrutura está equilibrada. Preserve a constância.":
      "आपकी वित्तीय स्थिति संतुलित है। निरंतरता बनाए रखें।",
  "Boa margem financeira. Continue fortalecendo sua reserva.":
      "आपके पास अच्छी वित्तीय गुंजाइश है। अपनी आपातकालीन निधि बढ़ाते रहें।",
  "Excelente capacidade de sobra. Direcione esse resultado com propósito.":
      "आपकी बचत क्षमता बहुत अच्छी है। इस अधिशेष का उद्देश्यपूर्ण उपयोग करें।",
  "Criptoativos": "क्रिप्टो परिसंपत्तियाँ",
  "Carteira de criptoativos": "क्रिप्टो परिसंपत्ति पोर्टफोलियो",
  "Sem anúncios": "विज्ञापन नहीं",
  "Criptoativos relacionados": "संबंधित क्रिप्टो परिसंपत्तियाँ",
  "Carteira": "पोर्टफोलियो",
  "comprometido": "प्रतिबद्ध",
  "Disponível no Plano {plan}.": "{plan} योजना में उपलब्ध है।",
  "Histórico indisponível": "इतिहास उपलब्ध नहीं है",
  "Início": "होम",
  "Resumo de {month}": "{month} का सारांश",
  "Painel financeiro": "वित्तीय डैशबोर्ड",
  "Sua vida financeira em um só lugar": "आपकी वित्तीय स्थिति एक ही जगह",
  "Saldo do mês": "महीने का शेष",
  "Ganhos extras": "अतिरिक्त आय",
  "Renda além do seu salário": "वेतन के अलावा आय",
  "Total no mês": "इस महीने कुल",
  "Investimentos": "निवेश",
  "Seu patrimônio trabalhando por você": "आपकी संपत्ति आपके लिए काम कर रही है",
  "Total investido": "कुल निवेश",
  "Ativos": "परिसंपत्तियाँ",
  "Variação indisponível": "बदलाव उपलब्ध नहीं",
  "investment.period.month": "माह",
  "24h": "24 घंटे",
  "{count} ativo": "{count} परिसंपत्ति",
  "{count} ativos": "{count} परिसंपत्तियाँ",
  "{count} criptoativo": "{count} क्रिप्टो परिसंपत्ति",
  "{count} criptoativos": "{count} क्रिप्टो परिसंपत्तियाँ",
  "{count} ativos na carteira": "पोर्टफोलियो में {count} संपत्तियाँ",
  "Carregando resumo…": "सारांश लोड हो रहा है…",
  "Resumo indisponível": "सारांश उपलब्ध नहीं",
  "screen.account": "मेरा खाता",
  "Dados do perfil": "प्रोफ़ाइल विवरण",
  "Data de nascimento": "जन्म तिथि",
  "Receber comunicações do Oscar Hive": "Oscar Hive के संदेश प्राप्त करें",
  "Opcional e independente da publicidade.":
      "वैकल्पिक और विज्ञापन से स्वतंत्र।",
  "Essa preferência fica salva neste aparelho.":
      "यह प्राथमिकता इस डिवाइस पर सहेजी जाती है।",
  "Perfil salvo neste dispositivo.": "प्रोफ़ाइल इस डिवाइस पर सहेजी गई।",
  "Não foi possível salvar o perfil.": "प्रोफ़ाइल सहेजी नहीं जा सकी।",
  "O acesso com Google ainda não está disponível nesta versão.":
      "इस संस्करण में Google साइन-इन अभी उपलब्ध नहीं है।",
  "Apple estará disponível em uma versão futura.":
      "Apple साइन-इन भविष्य के संस्करण में उपलब्ध होगा।",
  "Cópia de segurança e recuperação": "बैकअप और पुनर्प्राप्ति",
  "Seus dados ficam neste aparelho. A sincronização e a recuperação na nuvem ainda não estão disponíveis.": "आपका डेटा इस डिवाइस पर रहता है। क्लाउड सिंक और रिकवरी अभी उपलब्ध नहीं हैं।",
  "legal.account.profile.body": "आपका नाम, जन्मतिथि और संदेश संबंधी प्राथमिकता वैकल्पिक हैं और केवल इस डिवाइस पर सहेजी जाती हैं। यह जानकारी किसी दूरस्थ खाते पर नहीं भेजी जाती। इस संस्करण में कोई संदेश नहीं भेजा जाता।",
};
