// Reviewed product copy for this language only. No cross-language fallback.
const ptBrMessages = <String, String>{
  "Aplicado: {value}": "Aplicado: {value}",
  "Rendimento: {value}": "Rendimento: {value}",
  "Rendeu no mês: {value}": "Rendeu no mês: {value}",
  "Efeito estimado da inflação: {value}":
      "Efeito estimado da inflação: {value}",
  "Crescimento real estimado: {value}": "Crescimento real estimado: {value}",
  "Patrimônio estimado: {value}": "Patrimônio estimado: {value}",
  "Valor inicial ({currency})": "Valor inicial ({currency})",
  "Saldo atual: {value}": "Saldo atual: {value}",
  "{value} guardados": "{value} guardados",
  "Cobre aproximadamente {value} meses": "Cobre aproximadamente {value} meses",
  "Meta: {months} meses · {percent}%": "Meta: {months} meses · {percent}%",
  "Meta: {months} meses": "Meta: {months} meses",
  "meses de cobertura": "meses de cobertura",
  "da meta": "da meta",
  "Ajustar meta": "Ajustar meta",
  "Aporte entra nos gastos; zero salva só a meta.":
      "O aporte entra nos gastos; zero salva apenas a meta.",
  "O aporte deve ser maior que zero.": "O aporte deve ser maior que zero.",
  "Fluxo do mês: {value}/100": "Fluxo do mês: {value}/100",
  "Reserva: {value} meses": "Reserva: {value} meses",
  "Reserva de Emergência: {value} meses":
      "Reserva de Emergência: {value} meses",
  "{name} · {amount} será removido deste mês.":
      "{name} · {amount} será removido deste mês.",
  "{name} será removido de {month}.": "{name} será removido de {month}.",
  "Cadastrar “{name}” manualmente": "Cadastrar “{name}” manualmente",
  "Serviços · {value}%": "Serviços · {value}%",
  "Vendas · {value}%": "Vendas · {value}%",
  "Horário · {time}": "Horário · {time}",
  "Escolher {plan}": "Escolher {plan}",
  "Este período está disponível no Plano {plan}.":
      "Este período está disponível no Plano {plan}.",
  "Relatório · {count} folha": "Relatório · {count} folha",
  "Relatório · {count} folhas": "Relatório · {count} folhas",
  "Competência {month} · Página {page} de {total}":
      "Competência {month} · Página {page} de {total}",
  "Títulos públicos": "Títulos públicos",
  "Renda fixa bancária": "Renda fixa bancária",
  "Títulos empresariais": "Títulos empresariais",
  "Cadastro manual": "Cadastro manual",
  "Criptomoedas": "Criptomoedas",
  "Quantidade": "Quantidade",
  "Informe uma quantidade válida.": "Informe uma quantidade válida.",
  "Histórico em formação": "Histórico em formação",
  "Variação em 24 horas": "Variação em 24 horas",
  "O convite de amigos está indisponível nesta versão.":
      "O convite de amigos está indisponível nesta versão.",
  "Receba 30% de desconto quando um amigo indicado se cadastrar e contratar um plano anual. Assinaturas mensais não participam. Descontos não se acumulam: vale o maior desconto elegível.": "Receba 30% de desconto quando um amigo indicado se cadastrar e contratar um plano anual. Assinaturas mensais não participam. Descontos não se acumulam: vale o maior desconto elegível.",
  "Carteira de criptomoedas com cotações CoinMarketCap":
      "Carteira de criptomoedas com cotações CoinMarketCap",
  "Entradas": "Entradas",
  "Gastos": "Gastos",
  "Parcelas Longas": "Parcelas Longas",
  "Participação das despesas": "Participação das despesas",
  "Nova entrada": "Nova entrada",
  "Novo gasto": "Novo gasto",
  "Editar entrada": "Editar entrada",
  "Editar gasto": "Editar gasto",
  "Editar serviço": "Editar serviço",
  "Editar venda": "Editar venda",
  "Novo serviço": "Novo serviço",
  "Nova venda": "Nova venda",
  "Nova parcela": "Nova parcela",
  "Editar parcela": "Editar parcela",
  "Parcela atual": "Parcela atual",
  "Total de parcelas": "Total de parcelas",
  "Informe uma parcela válida, como 5 de 36.":
      "Informe uma parcela válida, como 5 de 36.",
  "Nome": "Nome",
  "Descrição": "Descrição",
  "Valor": "Valor",
  "Desconto": "Desconto",
  "Sem desconto": "Sem desconto",
  "Valor fixo": "Valor fixo",
  "Percentual": "Percentual",
  "Recorrente": "Recorrente",
  "Cancelar": "Cancelar",
  "Salvar": "Salvar",
  "Editar": "Editar",
  "Excluir": "Excluir",
  "Confirmar exclusão": "Confirmar exclusão",
  "Item removido.": "Item removido.",
  "Desfazer": "Desfazer",
  "Reserva de Emergência": "Reserva de Emergência",
  "Valor guardado": "Valor guardado",
  "1 mês": "1 mês",
  "3 meses": "3 meses",
  "6 meses": "6 meses",
  "Atualizar valor": "Atualizar valor",
  "Investimentos: Não avaliado": "Investimentos: Não avaliado",
  "Não foi possível carregar seus dados.":
      "Não foi possível carregar seus dados.",
  "Tentar novamente": "Tentar novamente",
  "Total realizado no mês": "Total realizado no mês",
  "Nenhum lançamento nesta categoria.": "Nenhum lançamento nesta categoria.",
  "Ganho recorrente": "Ganho recorrente",
  "Somar à renda extra da Tela 1": "Somar à renda extra da Tela 1",
  "Ganho removido.": "Ganho removido.",
  "Sem ganhos": "Sem ganhos",
  "Serviços": "Serviços",
  "Vendas": "Vendas",
  "Pesquisar ou adicionar investimento": "Pesquisar ou adicionar investimento",
  "Limpar pesquisa": "Limpar pesquisa",
  "Alocação de ativos": "Alocação de ativos",
  "Símbolo ou código": "Símbolo ou código",
  "Família": "Família",
  "Moeda original": "Moeda original",
  "Valor aplicado": "Valor aplicado",
  "Rendimento do mês": "Rendimento do mês",
  "Confirmar posição": "Confirmar posição",
  "Excluir esta posição?": "Excluir esta posição?",
  "Posição excluída.": "Posição excluída.",
  "Nenhuma posição nesta área e mês.": "Nenhuma posição nesta área e mês.",
  "Adicionar manualmente": "Adicionar manualmente",
  "Renda Fixa": "Renda Fixa",
  "Imobiliários": "Imobiliários",
  "Ações e ETFs": "Ações e ETFs",
  "Simulador": "Simulador",
  "Calculadora de juros compostos": "Calculadora de juros compostos",
  "Aporte mensal": "Aporte mensal",
  "Taxa (%)": "Taxa (%)",
  "Mensal": "Mensal",
  "Anual": "Anual",
  "Prazo em meses": "Prazo em meses",
  "Calcular cenário": "Calcular cenário",
  "Crescimento acima da inflação": "Crescimento acima da inflação",
  "Sua vida financeira": "Sua vida financeira",
  "em relatórios claros": "em relatórios claros",
  "Relatório do mês atual": "Relatório do mês atual",
  "Relatório dos últimos 3 meses": "Relatório dos últimos 3 meses",
  "Relatório dos últimos 6 meses": "Relatório dos últimos 6 meses",
  "Relatório anual": "Relatório anual",
  "Imprimir": "Imprimir",
  "Compartilhar": "Compartilhar",
  "Antes de compartilhar": "Antes de compartilhar",
  "Continuar": "Continuar",
  "Sem movimentação": "Sem movimentação",
  "Investimentos e crescimento real: Não avaliado":
      "Investimentos e crescimento real: Não avaliado",
  "Fechar": "Fechar",
  "Nenhum compromisso neste dia.": "Nenhum compromisso neste dia.",
  "Adicionar compromisso": "Adicionar compromisso",
  "Novo compromisso": "Novo compromisso",
  "Título *": "Título *",
  "Observação opcional": "Observação opcional",
  "Recorrência": "Recorrência",
  "Nenhuma": "Nenhuma",
  "Semanal": "Semanal",
  "Lembretes locais": "Lembretes locais",
  "Informe o título do compromisso.": "Informe o título do compromisso.",
  "Compromisso excluído.": "Compromisso excluído.",
  "Compromissos\npessoais": "Compromissos\npessoais",
  "Serviços\nagendados": "Serviços\nagendados",
  "Compromissos\nprofissionais": "Compromissos\nprofissionais",
  "Plano Básico": "Plano Básico",
  "Plano Plus": "Plano Plus",
  "Plano Pro": "Plano Pro",
  "Plano atual": "Plano atual",
  "Convidar": "Convidar",
  "Convide um Amigo": "Convide um Amigo",
  "Escolha a clareza que acompanha seu momento":
      "Escolha a clareza que acompanha seu momento",
  "Oscar Clube": "Oscar Clube",
  "Parceria remunerada": "Parceria remunerada",
  "Ver benefício": "Ver benefício",
  "Continuar para o parceiro": "Continuar para o parceiro",
  "Nenhum benefício válido disponível para sua região neste momento.":
      "Nenhum benefício válido disponível para sua região neste momento.",
  "Idioma, região e moeda": "Idioma, região e moeda",
  "Idioma": "Idioma",
  "Moeda principal": "Moeda principal",
  "Salvar alterações": "Salvar alterações",
  "Configurações atualizadas": "Configurações atualizadas",
  "Aparência": "Aparência",
  "Automático": "Automático",
  "Claro": "Claro",
  "Escuro": "Escuro",
  "Atualizar reserva de emergência": "Atualizar reserva de emergência",
  "Reserva de emergência": "Reserva de emergência",
  "Cadastre despesas para visualizar a participação na renda.":
      "Cadastre despesas para visualizar a participação na renda.",
  "Origem dos ganhos": "Origem dos ganhos",
  "Nenhum resultado local. O cadastro manual continua disponível.":
      "Nenhum resultado local. O cadastro manual continua disponível.",
  "Ela sairá da carteira, mas poderá ser restaurada por alguns segundos.":
      "Ela sairá da carteira, mas poderá ser restaurada por alguns segundos.",
  "Evolução patrimonial": "Evolução patrimonial",
  "1 ano": "1 ano",
  "Todo período": "Todo período",
  "Patrimônio registrado": "Patrimônio registrado",
  "Câmbio indisponível: não é possível somar investimentos em moedas diferentes.": "Câmbio indisponível: não é possível somar investimentos em moedas diferentes.",
  "Valorização acumulada": "Valorização acumulada",
  "Somente rendimentos registrados; não inclui variação de mercado.":
      "Somente rendimentos registrados; não inclui variação de mercado.",
  "Nenhum investimento registrado neste período.":
      "Nenhum investimento registrado neste período.",
  "Ver valores mês a mês": "Ver valores mês a mês",
  "Aplicado + rendimento confirmado": "Aplicado + rendimento confirmado",
  "Aportes e rendimentos registrados": "Aportes e rendimentos registrados",
  "Total registrado": "Total registrado",
  "Variação no período": "Variação no período",
  "Não inclui oscilações de mercado nem representa rentabilidade.":
      "Não inclui oscilações de mercado nem representa rentabilidade.",
  "Estimativa educacional. Não é promessa de rentabilidade nem recomendação.": "Estimativa educacional. Não é promessa de rentabilidade nem recomendação.",
  "Estimativa baseada em uma cesta média; não representa sua inflação pessoal.": "Estimativa baseada em uma cesta média; não representa sua inflação pessoal.",
  "A alocação aparecerá quando você cadastrar uma posição.":
      "A alocação aparecerá quando você cadastrar uma posição.",
  "Não foi possível gerar o relatório. Tente novamente.":
      "Não foi possível gerar o relatório. Tente novamente.",
  "Este documento contém informações financeiras pessoais. Compartilhe somente com pessoas de confiança.": "Este documento contém informações financeiras pessoais. Compartilhe somente com pessoas de confiança.",
  "O aplicativo agenda notificações locais. A entrega depende das permissões, economia de bateria, modo silencioso e políticas do aparelho.": "O aplicativo agenda notificações locais. A entrega depende das permissões, economia de bateria, modo silencioso e políticas do aparelho.",
  "Todos os planos preservam seus dados e a navegação completa. Recursos avançados são explicados no ponto de uso.": "Todos os planos preservam seus dados e a navegação completa. Recursos avançados são explicados no ponto de uso.",
  "Toque em um plano para visualizar os recursos disponíveis.":
      "Toque em um plano para visualizar os recursos disponíveis.",
  "Uma indicação elegível pode oferecer até 40% de desconto. Benefícios não são cumulativos: prevalece sempre o maior desconto válido.": "Uma indicação elegível pode oferecer até 40% de desconto. Benefícios não são cumulativos: prevalece sempre o maior desconto válido.",
  "O convite seguro será habilitado quando contas e validação do servidor estiverem disponíveis.": "O convite seguro será habilitado quando contas e validação do servidor estiverem disponíveis.",
  "Benefícios úteis e transparentes para apoiar sua educação, bem-estar e vida prática.": "Benefícios úteis e transparentes para apoiar sua educação, bem-estar e vida prática.",
  "O Oscar Finanças poderá receber uma comissão se você contratar ou comprar por este link. Você será direcionado ao ambiente do parceiro.": "O Oscar Finanças poderá receber uma comissão se você contratar ou comprar por este link. Você será direcionado ao ambiente do parceiro.",
  "O link deste parceiro ainda não está disponível.":
      "O link deste parceiro ainda não está disponível.",
  "Região": "Região",
  "Primeiro dia da semana": "Primeiro dia da semana",
  "Ocultar valores ao abrir": "Ocultar valores ao abrir",
  "As Telas 1, 2 e 3 começam protegidas.":
      "As Telas 1, 2 e 3 começam protegidas.",
  "Ocultar valores ao sair": "Ocultar valores ao sair",
  "Oculta os valores quando o aplicativo vai para segundo plano.":
      "Oculta os valores quando o aplicativo vai para segundo plano.",
  "Vibração e resposta tátil": "Vibração e resposta tátil",
  "Lembrete padrão para novos eventos": "Lembrete padrão para novos eventos",
  "Cotações e indicadores": "Cotações e indicadores",
  "O último snapshot válido é usado offline. Atualizações indisponíveis aparecem como desatualizadas.": "O último snapshot válido é usado offline. Atualizações indisponíveis aparecem como desatualizadas.",
  "O Oscar Finanças não se conecta a contas bancárias nem movimenta dinheiro. Informações, simulações e projeções têm caráter informativo e usam dados fornecidos por você e referências de mercado atualizadas. Cotações podem apresentar atrasos ou diferenças em relação ao mercado.": "O Oscar Finanças não se conecta a contas bancárias nem movimenta dinheiro. Informações, simulações e projeções têm caráter informativo e usam dados fornecidos por você e referências de mercado atualizadas. Cotações podem apresentar atrasos ou diferenças em relação ao mercado.",
  "Atualização oficial disponível após configurar os provedores.":
      "Atualização oficial disponível após configurar os provedores.",
  "Atualizar agora": "Atualizar agora",
  "Disponível em {tempo}": "Disponível em {tempo}",
  "Oscar Finanças — Clareza que transforma escolhas em patrimônio.":
      "Oscar Finanças — Clareza que transforma escolhas em patrimônio.",
  "Organiza receitas, despesas, ganhos extras, saúde financeira, relatórios, agenda e investimentos sem movimentar seu dinheiro nem oferecer recomendação individual.": "Organiza receitas, despesas, ganhos extras, saúde financeira, relatórios, agenda e investimentos sem movimentar seu dinheiro nem oferecer recomendação individual.",
  "Saldo atual": "Saldo atual",
  "Aporte deste mês": "Aporte deste mês",
  "O aporte será incluído na lista de gastos do mês.":
      "O aporte será incluído na lista de gastos do mês.",
  "Tipo de aporte": "Tipo de aporte",
  "Aporte único": "Aporte único",
  "Mensal fixo": "Mensal fixo",
  "Variável ou intermitente": "Variável ou intermitente",
  "Meta de cobertura": "Meta de cobertura",
  "Salário simulado": "Salário simulado",
  "Aluguel simulado": "Aluguel simulado",
  "Luz simulada": "Luz simulada",
  "Água simulada": "Água simulada",
  "Internet simulada": "Internet simulada",
  "Mercado simulado": "Mercado simulado",
  "Reserva de emergência simulada": "Reserva de emergência simulada",
  "Faculdade simulada": "Faculdade simulada",
  "Carro simulado": "Carro simulado",
  "TV simulada": "TV simulada",
  "Freelance de design simulado": "Freelance de design simulado",
  "Serviço freelance": "Serviço freelance",
  "Projeto ou atendimento do mês": "Projeto ou atendimento do mês",
  "Projeto pontual simulado": "Projeto pontual simulado",
  "Manutenção de computador simulada": "Manutenção de computador simulada",
  "Serviço técnico simulado": "Serviço técnico simulado",
  "Venda de bicicleta simulada": "Venda de bicicleta simulada",
  "Venda ocasional simulada": "Venda ocasional simulada",
  "Venda ocasional": "Venda ocasional",
  "Venda de item ou produto": "Venda de item ou produto",
  "Venda de doces simulada": "Venda de doces simulada",
  "Renda complementar simulada": "Renda complementar simulada",
  "Tesouro Selic simulado": "Tesouro Selic simulado",
  "CDB simulado": "CDB simulado",
  "Fundo imobiliário simulado": "Fundo imobiliário simulado",
  "Ação simulada": "Ação simulada",
  "Versão 0.1.0 · compilação 1": "Versão 0.1.0 · compilação 1",
  "Organização financeira essencial, sem custo.":
      "Organização financeira essencial, sem custo.",
  "Painel Financeiro completo, Reserva de Emergência e Oscar Score":
      "Painel Financeiro completo, Reserva de Emergência e Oscar Score",
  "Relatório mensal com impressão e compartilhamento":
      "Relatório mensal com impressão e compartilhamento",
  "Agenda completa com recorrência e lembretes locais":
      "Agenda completa com recorrência e lembretes locais",
  "Oscar Clube e Configurações": "Oscar Clube e Configurações",
  "Grátis": "Grátis",
  "Mais controle para quem transforma trabalho em renda.":
      "Mais controle para quem transforma trabalho em renda.",
  "Tudo do Plano Básico": "Tudo do Plano Básico",
  "Ganho Extra completo: Serviços, Vendas e recorrências":
      "Ganho Extra completo: Serviços, Vendas e recorrências",
  "Integração Agenda → Ganho Extra": "Integração Agenda → Ganho Extra",
  "Relatórios do mês e dos últimos 3 meses":
      "Relatórios do mês e dos últimos 3 meses",
  "Visão patrimonial completa, simples e internacional.":
      "Visão patrimonial completa, simples e internacional.",
  "Tudo do Plano Plus": "Tudo do Plano Plus",
  "Investimentos, busca internacional, ações e ETFs":
      "Investimentos, busca internacional, ações e ETFs",
  "Crescimento real e resumo em BRL, USD, EUR e INR":
      "Crescimento real e resumo em BRL, USD, EUR e INR",
  "Relatórios de 1, 3, 6 e 12 meses": "Relatórios de 1, 3, 6 e 12 meses",
  "Educação e Carreira": "Educação e Carreira",
  "Cursos, idiomas, livros, certificações e ferramentas profissionais.":
      "Cursos, idiomas, livros, certificações e ferramentas profissionais.",
  "Saúde, Beleza e Bem-estar": "Saúde, Beleza e Bem-estar",
  "Cuidados pessoais, academias, exames e soluções de bem-estar.":
      "Cuidados pessoais, academias, exames e soluções de bem-estar.",
  "Viagens e Experiências": "Viagens e Experiências",
  "Hospedagem, cultura, gastronomia, passeios e serviços relacionados.":
      "Hospedagem, cultura, gastronomia, passeios e serviços relacionados.",
  "Tecnologia e Vida Prática": "Tecnologia e Vida Prática",
  "Notificações": "Notificações",
  "Lançamentos recorrentes": "Lançamentos recorrentes",
  "Relatório mensal disponível": "Relatório mensal disponível",
  "Dados econômicos e câmbio": "Dados econômicos e câmbio",
  "Transparência e metodologia": "Transparência e metodologia",
  "Sobre o aplicativo": "Sobre o aplicativo",
  "Estados Unidos": "Estados Unidos",
  "Alemanha": "Alemanha",
  "França": "França",
  "Índia": "Índia",
  "No horário": "No horário",
  "1 dia antes e no horário": "1 dia antes e no horário",
  "3 dias antes, 1 dia antes e no horário":
      "3 dias antes, 1 dia antes e no horário",
  "Termos de Uso": "Termos de Uso",
  "Política de Privacidade": "Política de Privacidade",
  "Consentimento e tratamento de dados financeiros":
      "Consentimento e tratamento de dados financeiros",
  "Política de Anúncios": "Política de Anúncios",
  "Política de Parcerias e Benefícios": "Política de Parcerias e Benefícios",
  "Privacidade Internacional": "Privacidade Internacional",
  "Exclusão de dados": "Exclusão de dados",
  "Aviso financeiro": "Aviso financeiro",
  "Metodologia do Oscar Score": "Metodologia do Oscar Score",
  "Licenças e bibliotecas": "Licenças e bibliotecas",
  "O Oscar Finanças organiza informações fornecidas pelo usuário. Os cálculos e projeções são educacionais, podem conter limitações e não constituem consultoria financeira. O usuário é responsável pela exatidão dos dados cadastrados e pelo uso dos relatórios.": "O Oscar Finanças organiza informações fornecidas pelo usuário. Os cálculos e projeções são educacionais, podem conter limitações e não constituem consultoria financeira. O usuário é responsável pela exatidão dos dados cadastrados e pelo uso dos relatórios.",
  "Dados financeiros permanecem no aparelho nesta versão. Serviços públicos de câmbio e indicadores não recebem valores da carteira. Recursos externos devem declarar finalidade, retenção e fundamento legal antes da publicação.": "Dados financeiros permanecem no aparelho nesta versão. Serviços públicos de câmbio e indicadores não recebem valores da carteira. Recursos externos devem declarar finalidade, retenção e fundamento legal antes da publicação.",
  "O aplicativo aplica minimização, finalidade e controle do usuário. LGPD, GDPR e normas regionais serão observadas de acordo com o país de disponibilização.": "O aplicativo aplica minimização, finalidade e controle do usuário. LGPD, GDPR e normas regionais serão observadas de acordo com o país de disponibilização.",
  "Espaços publicitários futuros usarão um módulo isolado. Personalização dependerá de consentimento aplicável e nenhum anúncio receberá receitas, despesas, agenda, relatório ou carteira.": "Espaços publicitários futuros usarão um módulo isolado. Personalização dependerá de consentimento aplicável e nenhum anúncio receberá receitas, despesas, agenda, relatório ou carteira.",
  "O Oscar Finanças poderá receber comissão por links identificados. A transparência aparece antes da saída; critérios comerciais não alteram Oscar Score, relatórios ou cálculos.": "O Oscar Finanças poderá receber comissão por links identificados. A transparência aparece antes da saída; critérios comerciais não alteram Oscar Score, relatórios ou cálculos.",
  "Idioma, região e moeda são independentes. Transferências internacionais, quando existirem, deverão informar destino, proteção e direitos aplicáveis.": "Idioma, região e moeda são independentes. Transferências internacionais, quando existirem, deverão informar destino, proteção e direitos aplicáveis.",
  "A exclusão local exige confirmação forte e não deve ocorrer parcialmente. Exclusão de conta só será exibida quando contas e sincronização reais estiverem implementadas.": "A exclusão local exige confirmação forte e não deve ocorrer parcialmente. Exclusão de conta só será exibida quando contas e sincronização reais estiverem implementadas.",
  "O aplicativo não executa investimentos, não oferece custódia e não recomenda compra ou venda. Câmbio, inflação e rentabilidade podem variar; desempenho passado não garante resultado futuro.": "O aplicativo não executa investimentos, não oferece custódia e não recomenda compra ou venda. Câmbio, inflação e rentabilidade podem variar; desempenho passado não garante resultado futuro.",
  "O Oscar Score resume a sobra mensal em relação à renda bruta. Ele considera entradas confirmadas, despesas e déficit. Não é score de crédito e não determina acesso a produtos.": "O Oscar Score resume a sobra mensal em relação à renda bruta. Ele considera entradas confirmadas, despesas e déficit. Não é score de crédito e não determina acesso a produtos.",
  "O crescimento real estimado subtrai do rendimento nominal um efeito inflacionário baseado em índice oficial médio. Esse índice não representa a inflação pessoal de cada usuário.": "O crescimento real estimado subtrai do rendimento nominal um efeito inflacionário baseado em índice oficial médio. Esse índice não representa a inflação pessoal de cada usuário.",
  "Construído com Flutter e bibliotecas revisadas para gráficos, banco local, PDF, impressão e notificações. A relação final de licenças será gerada para a versão publicada.": "Construído com Flutter e bibliotecas revisadas para gráficos, banco local, PDF, impressão e notificações. A relação final de licenças será gerada para a versão publicada.",
  "Ativos relacionados": "Ativos relacionados",
  "Deslize para ver mais": "Deslize para ver mais",
  "Dados simulados": "Dados simulados",
  "Aguardando cotação": "Aguardando cotação",
  "Cotação atualizada": "Cotação atualizada",
  "Última cotação salva": "Última cotação salva",
  "Privacidade dos valores": "Privacidade dos valores",
  "Lembretes da Agenda": "Lembretes da Agenda",
  "Fechamento mensal": "Fechamento mensal",
  "Plano e assinatura": "Plano e assinatura",
  "Domingo": "Domingo",
  "Segunda-feira": "Segunda-feira",
  "Escolher": "Escolher",
  "por mês": "por mês",
  "mês": "mês",
  "por ano": "por ano",
  "equivalente a": "equivalente a",
  "economize": "economize",
  "Serviços do mês": "Serviços do mês",
  "Vendas do mês": "Vendas do mês",
  "Adicionar serviço": "Adicionar serviço",
  "Adicionar venda": "Adicionar venda",
  "Somado à Tela 1": "Somado à Tela 1",
  "Nenhuma entrada neste mês.": "Nenhuma entrada neste mês.",
  "Sem movimentações para exibir": "Sem movimentações para exibir",
  "Nenhum gasto neste mês.": "Nenhum gasto neste mês.",
  "Nenhuma parcela neste mês.": "Nenhuma parcela neste mês.",
  "Adicionar entrada": "Adicionar entrada",
  "Adicionar gasto": "Adicionar gasto",
  "Adicionar parcela": "Adicionar parcela",
  "Sobra": "Sobra",
  "Déficit": "Déficit",
  "Não calculado": "Não calculado",
  "Não avaliado": "Não avaliado",
  "Não avaliada": "Não avaliada",
  "Cadastre uma entrada para calcular seu Oscar Score.":
      "Cadastre uma entrada para calcular seu Oscar Score.",
  "Cadastre gastos para calcular a cobertura":
      "Cadastre gastos para calcular a cobertura",
  "Valor do desconto": "Valor do desconto",
  "Ações": "Ações",
  "Cotações indisponíveis": "Cotações indisponíveis",
  "Cotações atualizadas com sucesso.": "Cotações atualizadas com sucesso.",
  "Não foi possível atualizar as cotações.":
      "Não foi possível atualizar as cotações.",
  "Sem conexão. O último valor disponível foi mantido.":
      "Sem conexão. O último valor disponível foi mantido.",
  "Cotações demonstrativas desatualizadas · dados reais serão atualizados por adaptador seguro": "Cotações demonstrativas desatualizadas · dados reais serão atualizados por adaptador seguro",
  "Cotações atualizadas · fonte de mercado":
      "Cotações atualizadas · fonte de mercado",
  "Aviso educacional financeiro": "Aviso educacional financeiro",
  "Como funciona o Oscar Score": "Como funciona o Oscar Score",
  "Dispositivos, software, conectividade, casa, estudo e trabalho.":
      "Dispositivos, software, conectividade, casa, estudo e trabalho.",
  "DOM": "DOM",
  "SEG": "SEG",
  "TER": "TER",
  "QUA": "QUA",
  "QUI": "QUI",
  "SEX": "SEX",
  "SÁB": "SÁB",
  "entry.welcome": "Sua vida financeira com clareza, privacidade e propósito.",
  "entry.google": "Entrar com Google",
  "entry.apple": "Entrar com Apple",
  "entry.guest": "Continuar sem conta",
  "entry.disclaimer": "Seus dados financeiros permanecem neste aparelho.",
  "drawer.close": "Fechar menu",
  "privacy.hide": "Ocultar valores",
  "privacy.show": "Exibir valores",
  "month.previous": "Mês anterior",
  "month.next": "Próximo mês",
  "screen.financial": "Painel Financeiro",
  "screen.extraIncome": "Ganho Extra",
  "screen.investments": "Investimentos",
  "screen.objectives": "Objetivos",
  "screen.reports": "Relatório Geral",
  "screen.agenda": "Agenda",
  "screen.calculator": "Calculadora",
  "screen.plans": "Planos",
  "screen.club": "Oscar Clube",
  "screen.settings": "Configurações",
  "objectives.subtitle": "Acompanhe o progresso das suas metas",
  "Objetivos financeiros com evolução mês a mês":
      "Objetivos financeiros com evolução mês a mês",
  "objectives.new": "Novo Objetivo",
  "objectives.emptyTitle": "Suas metas começam aqui",
  "objectives.emptyBody":
      "Crie um objetivo para acompanhar aportes e evolução ao longo do tempo.",
  "objectives.loadFailed": "Não foi possível carregar seus objetivos.",
  "objectives.retry": "Tentar novamente",
  "objectives.name": "Nome do objetivo",
  "objectives.nameRequired": "Informe um nome para o objetivo.",
  "objectives.targetPeriod": "Prazo da meta",
  "objectives.threeMonths": "3 meses",
  "objectives.sixMonths": "6 meses",
  "objectives.oneYear": "1 ano",
  "objectives.fiveYears": "5 anos",
  "objectives.tenYears": "10 anos",
  "objectives.monthCount": "{count} meses",
  "objectives.targetAmount": "Valor total da meta",
  "objectives.targetRequired": "Informe um valor maior que zero.",
  "objectives.initialBalance": "Saldo inicial já guardado",
  "objectives.initialBalanceHelp":
      "Valor que já está reservado, antes dos novos aportes.",
  "objectives.contribution": "Aporte",
  "objectives.addContribution": "Adicionar aporte",
  "objectives.contributionAmount": "Valor do aporte",
  "objectives.saveContribution": "Salvar aporte",
  "objectives.contributionSaved":
      "Aporte adicionado ao objetivo e registrado em Gastos.",
  "objectives.exchangeUnavailable":
      "Cotação indisponível; não foi possível converter este aporte.",
  "Saldo reservado": "Saldo reservado",
  "Aportes acumulados": "Aportes acumulados",
  "Meta": "Meta",
  "Acompanhe sua meta na tela Objetivos":
      "Veja o saldo, os aportes e o progresso da sua reserva",
  "Aporte · {name}": "Aporte · {name}",
  "objectives.annualRate": "Taxa anual",
  "objectives.compoundInterest": "Juros compostos ao ano",
  "objectives.annualRateShort": "Taxa anual",
  "objectives.lowerRate": "Diminuir taxa",
  "objectives.raiseRate": "Aumentar taxa",
  "objectives.annualRateHelp":
      "Use a taxa que deseja considerar na projeção. Pode deixar em 0%.",
  "objectives.rateTooHigh": "Informe uma taxa entre 0% e 100% ao ano.",
  "objectives.frequency": "Frequência deste aporte",
  "objectives.oneTime": "Único",
  "objectives.monthly": "Mensal recorrente",
  "objectives.projectionDisclosure": "A taxa gera uma estimativa, não uma cotação real. O aporte deste mês também aparece em Gastos como “Aporte · objetivo”.",
  "objectives.create": "Criar objetivo",
  "objectives.cancel": "Cancelar",
  "objectives.created": "Objetivo criado.",
  "objectives.goalActions": "Ações do objetivo",
  "objectives.delete": "Excluir",
  "objectives.deleteTitle": "Excluir este objetivo?",
  "objectives.deleteBody": "O objetivo e sua evolução sairão desta tela. Os lançamentos de aporte em Gastos serão preservados.",
  "objectives.currentBalance": "Saldo projetado no mês atual",
  "objectives.contributions": "Aportes acumulados",
  "objectives.estimatedYield": "Rendimento estimado",
  "objectives.returnLabel": "Rendimento",
  "objectives.progressSemantics": "Progresso da meta: {percent}%",
  "objectives.target": "Meta: {months} · {amount}",
  "objectives.percentComplete": "{percent}% atingido",
  "objectives.importedHistory": "Histórico de aportes importado dos seus gastos. Nenhum rendimento foi presumido.",
  "objectives.viewEvolution": "Evolução mensal",
  "objectives.chartDescription":
      "Gráfico da evolução mensal do saldo do objetivo",
  "objectives.monthlyEvolution": "Evolução mês a mês",
  "objectives.estimatedYieldShort": "Rendimento est.",
  "objectives.actualYieldShort": "Rendimento",
  "objectives.closingBalance": "Saldo final",
  "objectives.projectionFootnote": "Estimativa pela taxa anual informada ({rate}% a.a.). Sem cotação automática; confira o saldo real no seu investimento.",
  "foundation.ready": "Estrutura preparada para a próxima etapa",
  "Brasil": "Brasil",
  "Clareza que transforma escolhas em patrimônio":
      "Clareza que transforma escolhas em patrimônio",
  "Fluxo do mês: Não calculado": "Fluxo do mês: Não calculado",
  "Reserva: Não avaliada": "Reserva: Não avaliada",
  "Oscar Score: Não calculado": "Oscar Score: Não calculado",
  "Reserva de Emergência: Não avaliada": "Reserva de Emergência: Não avaliada",
  "Indisponível": "Indisponível",
  "home.block.financial": "Painel Financeiro",
  "home.block.extraIncome": "Ganhos Extras",
  "home.block.investments": "Investimentos",
  "home.block.emergencyFund": "Reserva de Emergência",
  "home.block.objectives": "Objetivos",
  "Acompanhe o progresso das suas metas":
      "Acompanhe o progresso dos seus objetivos",
  "Saldo dos objetivos": "Saldo dos objetivos",
  "Total acumulado": "Total acumulado",
  "Meta total": "Meta total",
  "Últimas cotações salvas · atualização automática":
      "Últimas cotações salvas · atualização automática",
  "Últimas cotações salvas · atualização automática indisponível":
      "Últimas cotações salvas · atualização automática indisponível",
  "legal.privacy.body": "Oscar Finanças usa os valores, descrições, investimentos e compromissos que você cadastra para organizar suas finanças. No aplicativo instalado, esses registros ficam no aparelho; na versão web, ficam armazenados localmente neste navegador e continuam disponíveis após recarregar a página. As preferências também ficam salvas localmente.\n\nPara obter cotações, usamos AwesomeAPI, HG Brasil, Alpha Vantage e CoinMarketCap. As consultas enviam moedas e identificadores de ativos; não enviam quantidades, saldos, valores aplicados, descrições ou compromissos. Os serviços envolvidos na conexão podem receber endereço IP e metadados técnicos.\n\nRelatórios só são enviados a outros aplicativos ou destinatários quando você escolhe imprimir ou compartilhar. Não vendemos seus dados financeiros. Esta versão não sincroniza registros com uma conta remota nem possui publicidade ou análise de comportamento por SDK.\n\nVocê pode editar e remover registros. A remoção de itens permite desfazer e pode manter registros locais marcados como excluídos. Os dados web permanecem neste navegador até você removê-los no app ou limpar os dados do site nas configurações do navegador. No aplicativo instalado, use a opção de limpar os dados do aplicativo nas configurações do sistema para apagar a base local. Arquivos exportados e cópias externas precisam ser apagados separadamente.",
  "legal.ads.body": "Esta versão não exibe anúncios e não integra o SDK do AdMob. Seus registros financeiros não são usados para segmentação publicitária. Se anúncios forem disponibilizados, esta política e os controles de privacidade serão atualizados antes da ativação. Quando exigido, você poderá escolher e revisar o consentimento nas opções de privacidade antes de solicitações de anúncios.",
  "legal.permissions.body": "Lembretes usam notificações locais, mediante permissão do sistema quando necessária. Você pode revogar essa permissão nas configurações do aparelho. O app não precisa acessar seus contatos, sua localização precisa, câmera ou microfone para organizar suas finanças. Permissões não concedidas podem impedir lembretes, mas não impedem o cadastro financeiro.",
  "Permissões e notificações": "Permissões e notificações",
  "legal.terms.body": "Oscar Finanças oferece organização financeira e cálculos educacionais a partir dos dados cadastrados. Não movimenta dinheiro, executa ordens, guarda criptomoedas ou fornece recomendação individual de investimento. Cotações podem estar atrasadas ou indisponíveis. Valores de mercado não equivalem a rendimento realizado.\n\nVocê é responsável por conferir seus registros e proteger o acesso ao aparelho e aos relatórios que exporta. Projeções não garantem resultados. A estimativa de inflação desta versão usa uma taxa de referência local e não representa sua inflação pessoal. Compras de assinaturas e convites de amigos estão indisponíveis nesta versão; nenhum botão de plano realiza cobrança.",
  "report.documentSummary.one": "{months} mês · {pages} páginas PDF",
  "report.documentSummary.many": "{months} meses · {pages} páginas PDF",
  "report.monthLabel": "Competência",
  "report.pdfPagesLabel": "Páginas do PDF",
  "report.summary": "Resumo geral",
  "report.incomeSection": "Renda e ganhos",
  "report.assets": "Ativos",
  "report.cryptoassets": "Criptoativos",
  "report.objectives": "Objetivos",
  "report.ofTarget": "da meta",
  "report.quantity": "Quantidade",
  "report.monthlyReturn": "Rendimento mensal",
  "report.target": "Meta",
  "report.monthlyYield": "Rendimento do mês",
  "report.estimated": "estimado",
  "report.confirmed": "realizado",
  "report.footerNote": "Valores registrados no mês",
  "report.demoFirst100k": "Meus primeiros 100K",
  "report.tagline": "Clareza que transforma escolhas em patrimônio",
  "report.report": "Relatório financeiro",
  "Relatório financeiro": "Relatório financeiro",
  "report.personal": "Documento pessoal",
  "Documento pessoal": "Documento pessoal",
  "report.currency": "moeda base",
  "moeda base": "moeda base",
  "report.generated": "gerado em",
  "gerado em": "gerado em",
  "report.noMovement": "Sem movimentação",
  "report.mainIncome": "Renda principal",
  "Renda principal": "Renda principal",
  "report.extra": "Ganho Extra confirmado",
  "Ganho Extra confirmado": "Ganho Extra confirmado",
  "report.total": "Entradas totais",
  "Entradas totais": "Entradas totais",
  "report.expenses": "Despesas",
  "Despesas": "Despesas",
  "report.installments": "Parcelas",
  "Parcelas": "Parcelas",
  "report.balance": "Sobra disponível",
  "Sobra disponível": "Sobra disponível",
  "report.deficit": "Déficit",
  "report.health": "Saúde financeira",
  "Saúde financeira": "Saúde financeira",
  "report.notCalculated": "Não calculado",
  "report.fund": "Reserva de Emergência",
  "report.notEvaluated": "Não avaliada",
  "report.months": "meses",
  "meses": "meses",
  "report.mainExpenses": "Gastos registrados",
  "Principais gastos": "Principais gastos",
  "report.noExpenses": "Nenhum gasto cadastrado.",
  "Nenhum gasto cadastrado.": "Nenhum gasto cadastrado.",
  "report.extraDetails": "Detalhamento dos ganhos extras",
  "report.noExtraIncome": "Nenhum ganho extra cadastrado.",
  "report.printUnavailable": "Não foi possível abrir a impressão. Tente Compartilhar para baixar o PDF.",
  "report.printFallback": "A impressão não abriu; baixei o PDF para você imprimir pelo visualizador.",
  "report.investments": "Investimentos e crescimento real",
  "Investimentos e crescimento real": "Investimentos e crescimento real",
  "report.page": "Página",
  "Página": "Página",
  "report.of": "de",
  "de": "de",
  "report.critical": "Alerta Crítico",
  "Alerta Crítico": "Alerta Crítico",
  "report.attention": "Atenção / Apertado",
  "Atenção / Apertado": "Atenção / Apertado",
  "report.balanced": "Equilibrado",
  "Equilibrado": "Equilibrado",
  "report.healthy": "Saudável",
  "Saudável": "Saudável",
  "report.prosperous": "Próspero",
  "Próspero": "Próspero",
  "Parcela {current} de {total}": "Parcela {current} de {total}",
  "Atenção": "Atenção",
  "Alerta crítico": "Alerta crítico",
  "{date}, {count} compromissos": "{date}, {count} compromissos",
  "Oscar Score, {score} de 100, {level}":
      "Oscar Score, {score} de 100, {level}",
  "Oscar Score não calculado. Cadastre uma entrada.":
      "Oscar Score não calculado. Cadastre uma entrada.",
  "Painel financeiro, valores ocultos": "Painel financeiro, valores ocultos",
  "Painel Financeiro": "Painel Financeiro",
  "O mês pede proteção. Reveja os maiores compromissos.":
      "O mês pede proteção. Reveja os maiores compromissos.",
  "Há pouco espaço de manobra. Pequenos ajustes podem abrir fôlego.":
      "Há pouco espaço de manobra. Pequenos ajustes podem abrir fôlego.",
  "Sua estrutura está equilibrada. Preserve a constância.":
      "Sua estrutura está equilibrada. Preserve a constância.",
  "Boa margem financeira. Continue fortalecendo sua reserva.":
      "Boa margem financeira. Continue fortalecendo sua reserva.",
  "Excelente capacidade de sobra. Direcione esse resultado com propósito.":
      "Excelente capacidade de sobra. Direcione esse resultado com propósito.",
  "Criptoativos": "Criptoativos",
  "Carteira de criptoativos": "Carteira de criptoativos",
  "Sem anúncios": "Sem anúncios",
  "Criptoativos relacionados": "Criptoativos relacionados",
  "Carteira": "Carteira",
  "comprometido": "comprometido",
  "Disponível no Plano {plan}.": "Disponível no Plano {plan}.",
  "Histórico indisponível": "Histórico indisponível",
  "Início": "Início",
  "Resumo de {month}": "Resumo de {month}",
  "Painel financeiro": "Painel financeiro",
  "Sua vida financeira em um só lugar": "Sua vida financeira em um só lugar",
  "Saldo do mês": "Saldo do mês",
  "Ganhos extras": "Ganhos extras",
  "Renda além do seu salário": "Renda além do seu salário",
  "Total no mês": "Total no mês",
  "Investimentos": "Investimentos",
  "Seu patrimônio trabalhando por você": "Seu patrimônio trabalhando por você",
  "Total investido": "Total investido",
  "Ativos": "Ativos",
  "Variação indisponível": "Variação indisponível",
  "investment.period.month": "mês",
  "24h": "24h",
  "{count} ativo": "{count} ativo",
  "{count} ativos": "{count} ativos",
  "{count} criptoativo": "{count} criptoativo",
  "{count} criptoativos": "{count} criptoativos",
  "{count} ativos na carteira": "{count} ativos na carteira",
  "Carregando resumo…": "Carregando resumo…",
  "Resumo indisponível": "Resumo indisponível",
  "screen.account": "Minha Conta",
  "Dados do perfil": "Dados do perfil",
  "Data de nascimento": "Data de nascimento",
  "Receber comunicações do Oscar Hive": "Receber comunicações do Oscar Hive",
  "Opcional e independente da publicidade.":
      "Opcional e independente da publicidade.",
  "Essa preferência fica salva neste aparelho.":
      "Essa preferência fica salva neste aparelho.",
  "Perfil salvo neste dispositivo.": "Perfil salvo neste dispositivo.",
  "Não foi possível salvar o perfil.": "Não foi possível salvar o perfil.",
  "O acesso com Google ainda não está disponível nesta versão.":
      "O acesso com Google ainda não está disponível nesta versão.",
  "Apple estará disponível em uma versão futura.":
      "Apple estará disponível em uma versão futura.",
  "Cópia de segurança e recuperação": "Cópia de segurança e recuperação",
  "Seus dados ficam neste aparelho. A sincronização e a recuperação na nuvem ainda não estão disponíveis.": "Seus dados ficam neste aparelho. A sincronização e a recuperação na nuvem ainda não estão disponíveis.",
  "legal.account.profile.body": "Nome, data de nascimento e preferência por comunicações são opcionais e ficam salvos apenas neste aparelho. Esses dados não são enviados a uma conta remota. Nesta versão, nenhum envio de comunicações é realizado.",
};
